Makefile: change default to use podman
ceph/ceph-csi pull request #1402
Opened 2020-08-18 13:27 UTC by pkalever

# Describe what this PR does #

With '# make image-cephcsi GOARCH=amd64'
On Fedora observed errors like:
```
[...]
 ---> Running in 3e2dbf48ebc6
OCI runtime create failed: this version of runc doesn't work on cgroups
v2: unknown
make: *** [Makefile:175: image-cephcsi] Error 1
```

hence it is recommended to switch to podman if available.

2020-08-18 13:43 UTC, Yuggupta27 commented
@yati1998 , is this the same issue you were facing?

2020-08-18 14:01 UTC, Madhu-1 commented
/test commitlint

2020-08-18 14:03 UTC, Madhu-1 commented
CI commitlint issue
> commitlint-travis
⧗   input: Makefile: change default to use podman
⚠   type must be one of [build, cephfs, ci, cleanup, deploy, doc, e2e, helm, journal, rbd, rebase, revert, util] [type-enum]
⚠   found 0 problems, 1 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
The command "commitlint-travis" exited with 0.

@nixpanic we need to configure commitlint bot to fail on warning?

2020-08-18 14:19 UTC, Madhu-1 commented
> CI commitlint issue
> 
> > commitlint-travis
> > ⧗   input: Makefile: change default to use podman
> > warning   type must be one of [build, cephfs, ci, cleanup, deploy, doc, e2e, helm, journal, rbd, rebase, revert, util] [type-enum]
> > warning   found 0 problems, 1 warnings
> > ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
> > The command "commitlint-travis" exited with 0.
> 
> @nixpanic we need to configure commitlint bot to fail on warning?

https://github.com/ceph/ceph-csi/blob/master/.commitlintrc.yml#L16 need to set to 2

2020-08-19 05:52 UTC, Madhu-1 requested changes
please fix the component name in commit heading

2020-08-19 07:39 UTC, Madhu-1 approved these changes

2020-08-19 08:24 UTC, nixpanic approved these changes

2020-08-19 11:52 UTC, merged