Sidecar
ceph/ceph-csi pull request #1451
Opened 2020-09-02 12:01 UTC by humblec

# Describe what this PR does #

Provide some context for the reviewer

## Is there anything that requires special attention ##

Do you have any questions?

Is the change backward compatible?

Are there concerns around backward compatibility?

Provide any external context for the change, if any.

For example:

* Kubernetes links that explain why the change is required
* CSI spec related changes/catch-up that necessitates this patch
* golang related practices that necessitates this change

## Related issues ##

Mention any github issues relevant to this PR. Adding below line
will help to auto close the issue once the PR is merged.

Fixes: #issue_number

## Future concerns ##

List items that are not part of the PR and do not impact it's
functionality, but are work items that can be taken up subsequently.

2020-09-02 12:06 UTC, Madhu-1 reviewed
few questions

* does this work on all kubernetes version we are currently supporting? 
* as its a major version upgrade don't we need any RBAC changes or something else?
* is this backward compatible?

2020-09-15 04:28 UTC, humblec commented
@Madhu-1 there are changes on RBAC required for some of the sidecars .  so that will be updated and all the things we require to get latest sidecars will be taken care. Backward compability is broken for some of the sidecars. So I am looking into those as well and also splitting it to different commits/PRs.

2020-09-15 12:22 UTC, nixpanic commented
> @Madhu-1 there are changes on RBAC required for some of the sidecars . so that will be updated and all the things we require to get latest sidecars will be taken care. Backward compability is broken for some of the sidecars. So I am looking into those as well and also splitting it to different commits/PRs.

Marked this as **draft** because it still seems to be a work in progress.

2020-09-26 11:30 UTC, Madhu-1 requested changes
Any reason why resizer and snapshotter images are not updated?

2020-09-26 11:30 UTC, Madhu-1 commented on scripts/minikube.sh
> +    copy_image_to_cluster "${K8S_IMAGE_REPO}"/csi-provisioner:v1.4.0 "${K8S_IMAGE_REPO}"/csi-provisioner:v1.6.0
why are we retagging 1.4.0 as 1.6.0?

2020-10-12 12:56 UTC, humblec commented
/retest all

2020-10-13 04:59 UTC, humblec commented
@Madhu-1 @nixpanic ptal .

2020-10-13 05:02 UTC, Madhu-1 requested changes
please update helm charts

2020-10-13 05:53 UTC, humblec commented
@Madhu-1 updated. ptal .

2020-10-13 06:06 UTC, Madhu-1 approved these changes

2020-10-13 06:10 UTC, humblec commented
@nixpanic ptal.

2020-10-13 12:12 UTC, nixpanic approved these changes

2020-10-13 12:34 UTC, merged