ci: create jobs for cephfs and rbd upgrade testing
ceph/ceph-csi pull request #1489
Opened 2020-09-17 08:23 UTC by Yuggupta27

Add Snapshot and PVC to PVC cloning test cases
to rbd and cephfs upgrade testing.
Moving these jobs to centos ci will enable us to
completely transition to centos ci.

2020-09-17 08:25 UTC, Yuggupta27 commented
After this PR is merged, jobs can be run on test cases here https://github.com/ceph/ceph-csi/pull/1464

2020-09-17 08:25 UTC, Madhu-1 reviewed
can we have a single grovy file for both cephfs and rbd upgrade testing?

2020-09-17 08:33 UTC, Yuggupta27 commented
> can we have a single grovy file for both cephfs and rbd upgrade testing?

Yes. It is better to have just one. Thanks for the suggestion.

2020-09-21 13:07 UTC, nixpanic requested changes

2020-09-21 13:07 UTC, nixpanic commented on upgrade-tests.groovy
> +				ssh "export UPGRADE_VERSION=$(source build.env ; echo ${UPGRADE_VERSION})"
This command does not make sense. Running an `export` over ssh without any commands will just return. The `export` affects the current shell, which is terminated when ssh returned.

2020-09-21 13:07 UTC, nixpanic commented on upgrade-tests.groovy
> +				ssh "cd /opt/build/go/src/github.com/ceph/ceph-csi && scripts/travis-functest.sh ${k8s_release} --upgrade-version=${UPGRADE_VERSION} ${upgrade_args}"
if you want to use `${UPGRADE_VERSION}` from `build.env` you need to source the file on this command line.

2020-09-22 07:13 UTC, nixpanic approved these changes

2020-09-22 07:24 UTC, Madhu-1 approved these changes

2020-09-22 07:25 UTC, merged