ci: require upgrade tests to pass for merging
ceph/ceph-csi pull request #1529
Opened 2020-09-28 12:58 UTC by Yuggupta27

Add passing of upgrade tests as a necessary condition
for merging PRs.
See: https://github.com/ceph/ceph-csi/pull/1464

Signed-off-by: Yug <yuggupta27@gmail.com>

2020-09-28 13:05 UTC, nixpanic requested changes
This also requires the CI job to get started automatically for all PRs. Marking -1 until that is done.

2020-09-29 06:33 UTC, nixpanic approved these changes
Marking **[DNM]** until #1530 is merged

2020-09-30 19:30 UTC, pkalever approved these changes

2020-10-01 07:20 UTC, Madhu-1 approved these changes

2020-10-01 07:22 UTC, merged