ci: Trigger upgrade test jobs automatically
ceph/ceph-csi pull request #1530
Opened 2020-09-28 13:05 UTC by Yuggupta27

Since upgrade tests will become a necessity to
merge PRs, it is better to trigger them
automatically now.

See: https://github.com/ceph/ceph-csi/pull/1529 https://github.com/ceph/ceph-csi/pull/1464

Signed-off-by: Yug <yuggupta27@gmail.com>

2020-09-28 13:06 UTC, nixpanic requested changes

2020-09-28 13:06 UTC, nixpanic commented on jobs/upgrade-tests.yaml
> +          only-trigger-phrase: false
Just delete this line

2020-09-29 06:26 UTC, nixpanic approved these changes

2020-09-29 06:31 UTC, nixpanic commented
Marking **[DNM]** until #1464 is merged

2020-09-29 08:01 UTC, Madhu-1 approved these changes

2020-09-30 19:25 UTC, Yuggupta27 commented
@Madhu-1 @nixpanic , should we get rid of DNM label as #1464 is merged ?
Also see: https://github.com/ceph/ceph-csi/pull/1529

2020-09-30 19:29 UTC, pkalever approved these changes

2020-10-01 07:19 UTC, merged