rbd: make sure csi rbd pv encryption  defaulting to luks2 version
ceph/ceph-csi pull request #1565
Opened 2020-10-09 05:49 UTC by humblec

Fix# https://github.com/ceph/ceph-csi/issues/1564

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

2020-10-09 05:49 UTC, humblec commented
@vasyl-purchel @dillaman ptal.

2020-10-12 12:48 UTC, nixpanic requested changes
Change the commit to include `Fixes: #...` , not `Fix`.

2020-10-12 12:51 UTC, nixpanic commented
Do you know if this is backwards compatible? Can existing encrypted volumes (`luks1`) be decrypted with `luks2`? Please update the commit message and PR description with such kind of details.

2020-10-12 13:19 UTC, nixpanic requested changes
So close!

    Fixes # #1564

should be

    Fixes: #1564

Once updated, the issue will be linked in the right side on the PR.

2020-10-12 13:21 UTC, humblec commented
@nixpanic ah.. can you revisit :)

2020-10-12 13:30 UTC, nixpanic approved these changes

2020-10-12 14:24 UTC, nixpanic commented
/retest ci/centos/mini-e2e/k8s-1.18

2020-10-13 04:38 UTC, humblec commented
@Madhu-1 ptal.

2020-10-13 04:48 UTC, Madhu-1 approved these changes

2020-10-13 05:11 UTC, merged