rbd: volJournal.Connect() return wrong error code
ceph/ceph-csi pull request #1605
Opened 2020-10-19 13:12 UTC by humblec

volJournal.Connect() got the error on `err2` variable, however
the return was on variable `err` which hold the error return of
DecomposeCSIID() which is wrong. This cause the error return wrongly
parsed and pushed from the caller.

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

2020-10-19 13:39 UTC, nixpanic requested changes

2020-10-19 13:39 UTC, nixpanic commented on internal/rbd/nodeserver.go
>  		j, err2 := volJournal.Connect(volOptions.Monitors, volOptions.RadosNamespace, cr)
Just drop `err2` and use `err`.

2020-10-19 13:46 UTC, humblec commented on internal/rbd/nodeserver.go
>  		j, err2 := volJournal.Connect(volOptions.Monitors, volOptions.RadosNamespace, cr)
@nixpanic done.. ptal

2020-10-19 14:06 UTC, nixpanic approved these changes

2020-10-20 02:44 UTC, humblec commented
/retest all

2020-10-20 02:45 UTC, humblec commented
@Mergifyio rebase

2020-10-20 04:44 UTC, humblec commented
@Madhu-1 ptal . :+1:

2020-10-20 05:00 UTC, humblec commented
/retest all

2020-10-20 06:27 UTC, nixpanic approved these changes
/retest ci/centos/upgrade-tests-rbd

2020-10-20 08:10 UTC, nixpanic commented
/retest ci/centos/upgrade-tests-rbd

2020-10-20 10:46 UTC, humblec commented
@Madhu-1 please review

2020-10-20 10:49 UTC, Madhu-1 approved these changes

2020-10-20 12:45 UTC, merged