e2e: validate the error return instead of object for consitency
ceph/ceph-csi pull request #1611
Opened 2020-10-20 09:58 UTC by humblec

If loadPVC() fails, it return error and we expect the PVC object to be nil too. In many places we check on the error and exit. however in few places we are looking at PVC object. This commit make the condition check on `err` instead of `PVC` object for consistency.

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

2020-10-20 12:56 UTC, nixpanic requested changes
the rbd changes are not related to e2e, and should probably be in their own PR

2020-10-20 13:03 UTC, Madhu-1 requested changes
PR description and PR details need to be updated as the few changes are in rbd code, or please create a new PR for it

please correct the same check in `resizePVCAndValidateSize` `createPVCAndAppBinding` `checkDataPersist` and upgrade-cephfs.go

2020-10-20 14:07 UTC, humblec commented
@nixpanic @Madhu-1 mainly kept the e2e changes , however clubbed all these to single commit. Please let me know if I need to split the e2e changes to different commits as they are on different sources. otherwise please review.

2020-10-20 14:36 UTC, nixpanic commented
> @nixpanic @Madhu-1 mainly kept the e2e changes , however clubbed all these to single commit. Please let me know if I need to split the e2e changes to different commits as they are on different sources. otherwise please review.

This is fine, these are all e2e changes.

2020-10-20 14:36 UTC, nixpanic approved these changes

2020-10-21 06:38 UTC, pkalever approved these changes

2020-10-21 06:40 UTC, humblec commented
@Madhu-1 ptal

2020-10-21 06:40 UTC, humblec commented
/retest ci/centos/mini-e2e/k8s-1.18.9

2020-10-21 06:44 UTC, pkalever approved these changes
LGTM. Covered all calls to loadPVC()  :+1:

2020-10-21 07:24 UTC, Madhu-1 approved these changes

2020-10-21 08:10 UTC, nixpanic commented
/retest ci/centos/mini-e2e-helm/k8s-1.19.2

2020-10-21 08:10 UTC, nixpanic commented
/retest ci/centos/mini-e2e/k8s-1.18.9

2020-10-21 09:54 UTC, nixpanic commented
/retest ci/centos/mini-e2e/k8s-1.18.9

2020-10-21 09:54 UTC, nixpanic commented
/retest ci/centos/mini-e2e-helm/k8s-1.19.2

2020-10-21 13:15 UTC, humblec commented
@nixpanic not sure why its taking long time to merge :)..

2020-10-21 13:56 UTC, merged