ci: fix shellcheck in test-go
ceph/ceph-csi pull request #1635
Opened 2020-10-27 05:07 UTC by Madhu-1

Fixed shellcheck in test-go script

fixes https://github.com/ceph/ceph-csi/issues/1634

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

2020-10-27 05:14 UTC, Yuggupta27 requested changes
Double quotes are required for variables which can either be empty or contain whitespace. To solve the shellcheck issue for the script, just the following changes should be fine.

2020-10-27 05:14 UTC, Yuggupta27 commented on scripts/test-go.sh
> +		exit "${failed}"
this

2020-10-27 05:14 UTC, Yuggupta27 commented on scripts/test-go.sh
> +exit "${failed}"
and this

2020-10-27 05:17 UTC, Yuggupta27 commented
Also, using quotes more is also a safer approach, so you can keep the changes

2020-10-27 05:17 UTC, Yuggupta27 approved these changes

2020-10-27 15:24 UTC, nixpanic commented on scripts/test-go.sh
> +	go test "${GO_TAGS}" -mod=vendor -v "${GOTESTOPTS}" "${gopackage}" || ((failed += 1))
I have updated this PR with a fix to use an array for `${GOTESTOPTS}`. Local testing suggests it works...

2020-10-27 15:27 UTC, nixpanic commented
Hmm, **ci/centos/containerized-tests** detects this as a `doc change only`... That is not really correct :-1:

2020-10-27 15:29 UTC, nixpanic approved these changes
Approving this, looks good to me (but I also made a minor correction).

2020-10-27 17:03 UTC, nixpanic commented
Marking this `[ready-to-merge]` so that other PRs get unblocked.

2020-10-27 17:04 UTC, merged

2020-11-06 03:28 UTC, Madhu-1 commented
@mergifyio backport release-v3.1