ci: add codespell for spell check
ceph/ceph-csi pull request #1718
Opened 2020-11-24 11:44 UTC by Madhu-1

adding a GitHub action to check the spelling mistakes in the code.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

2020-11-24 11:56 UTC, Madhu-1 commented
This will be a good addition to our CI

2020-11-24 12:36 UTC, nixpanic commented on internal/rbd/clone.go
> +	// as the temp clone doesn't exists,check snapshot exists on parent volume
`does not exist` (not exists)

2020-11-24 12:36 UTC, nixpanic commented on internal/rbd/controllerserver.go
> +			return nil, nil, status.Errorf(codes.NotFound, "%s snapshot does not exists", snapshotID)
`does not exist` - again `exists` with an `s`

2020-11-24 12:36 UTC, nixpanic commented on .github/workflows/codespell.yaml
> +# Referance https://github.com/codespell-project/actions-codespell
you might want to add a little description of the test too?

2020-11-24 12:37 UTC, nixpanic commented on .github/workflows/codespell.yaml
> +      - "master"
Decide if you need `"master"` with, or without quotes, and use the same everywhere

2020-11-24 12:39 UTC, nixpanic commented
Moving simple checks from Travis CI to GitHub CI might be good. Note that **ci/centos/containerized-tests** could get extended as well.

2020-11-24 16:26 UTC, nixpanic requested changes
still not all issues addressed, but almost good to go :+1:

2020-11-24 16:26 UTC, nixpanic commented on Makefile
> +# executable. The e2e.test executable is not checked as a dependencies in the
`dependency` should be single here

2020-11-24 16:26 UTC, nixpanic commented on Makefile
> +# create a (cached) container image with dependency for testing cephcsi
`dependencies` was corrected on line 182, the same should be done here

2020-11-26 07:31 UTC, nixpanic approved these changes

2020-11-26 07:35 UTC, nixpanic commented
Actually, lets wait with `[ready-to-merge]` until #1644 has passed CI (finally) and is merged

2020-11-29 07:17 UTC, Madhu-1 commented
Manually merging as GitHub workflow is added and Mergify cannot merge if GitHub flows are added/modified

2020-11-29 07:17 UTC, merged