doc: remove redundant word
ceph/ceph-csi pull request #1829
Opened 2021-01-11 03:59 UTC by iliul

Signed-off-by: liulei3 <liulei3@360.cn>

# Describe what this PR does #

remove redundant text "the"

## Is there anything that requires special attention ##

Do you have any questions?

Is the change backward compatible?

Are there concerns around backward compatibility?

Provide any external context for the change, if any.

For example:

* Kubernetes links that explain why the change is required
* CSI spec related changes/catch-up that necessitates this patch
* golang related practices that necessitates this change

## Related issues ##

Mention any github issues relevant to this PR. Adding below line
will help to auto close the issue once the PR is merged.

Fixes: #issue_number

## Future concerns ##

List items that are not part of the PR and do not impact it's
functionality, but are work items that can be taken up subsequently.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

2021-01-11 06:00 UTC, Yuggupta27 requested changes
Thanks for the PR @iliul ! Just some minor nit.

2021-01-11 06:02 UTC, Yuggupta27 commented
Also, U can consider removing the additional text in the PR description if you want :)

2021-01-11 09:54 UTC, nixpanic requested changes

2021-01-11 09:54 UTC, nixpanic commented on examples/csi-config-map-sample.yaml
> +# within the radosNamespace.
This now fails `yamlllint` with the following error:
```
 ./examples/csi-config-map-sample.yaml
  16:81     error    line too long (83 > 80 characters)  (line-length)
```

You can run `make containerized-test` to run the verification locally.

2021-01-19 05:32 UTC, Madhu-1 commented
/retest ci/centos/mini-e2e/k8s-1.20

2021-01-20 08:37 UTC, nixpanic submitted a review, later dismissed

2021-01-20 12:29 UTC, Madhu-1 approved these changes

2021-01-25 09:56 UTC, nixpanic approved these changes

2021-01-25 09:57 UTC, merged