cephfs: add subvolume path to volume context
ceph/ceph-csi pull request #1858
Opened 2021-02-08 07:21 UTC by Madhu-1

There are many use-cases with adding the subvolume path to the PV object. the volume context returned in the createVolumeResponse is added to the PV object by the external provisioner.

More Details about the use cases are in the below link
https://github.com/rook/rook/issues/5471

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

2021-02-08 09:02 UTC, humblec commented
Thanks @Madhu-1 . The use case https://github.com/rook/rook/issues/5471#issuecomment-774485869 looks like a valid one and I believe its good to record it in the PV object as in this case if it helps some customers.

2021-02-08 11:58 UTC, Madhu-1 commented
>Message: "etcdserver: request timed out"

/test ci/centos/upgrade-tests-cephfs

2021-02-08 11:58 UTC, Madhu-1 commented
/test ci/centos/upgrade-tests-cephfs

2021-02-08 12:02 UTC, Madhu-1 commented
/retest ci/centos/upgrade-tests-cephfs

2021-02-09 05:55 UTC, humblec commented
Code looks good to me. The test failure looks to be due to `etcdserver: request timed out`.

2021-02-09 06:59 UTC, humblec submitted a review, later dismissed

2021-02-09 09:18 UTC, nixpanic requested changes
Missing e2e test :sob:

This should also get documented somewhere (but that can be an other PR).

2021-02-09 11:54 UTC, Madhu-1 commented
>Warning: Permanently added 'n12.pufty.ci.centos.org,172.19.3.76' (ECDSA) to the list of known hosts.
Error from server: etcdserver: request timed out

2021-02-09 11:54 UTC, Madhu-1 commented
/test ci/centos/mini-e2e-helm/k8s-1.20

2021-02-09 12:31 UTC, nixpanic commented
Installation through Helm charts failed:
```
+ ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@n14.pufty.ci.centos.org 'cd /opt/build/go/src/github.com/ceph/ceph-csi && ./scripts/install-helm.sh install-cephcsi '\''cephcsi-e2e-52be7e504159'\'''
...
Checking Deployment status for label app=ceph-csi-cephfs in Namespace cephcsi-e2e-52be7e504159
Total replicas 1 is not equal to ready count 
Error from server: etcdserver: request timed out
script returned exit code 1
```

2021-02-09 12:32 UTC, nixpanic commented
/retest ci/centos/mini-e2e-helm/k8s-1.20

2021-02-09 15:15 UTC, nixpanic requested changes
just a few nits, almost there!

2021-02-09 15:15 UTC, nixpanic commented on internal/cephfs/controllerserver.go
> +
unneeded extra empty line

2021-02-09 15:15 UTC, nixpanic commented on e2e/cephfs.go
> +	subVolume := pv.Spec.CSI.VolumeAttributes["subvolumeName"]
If these values are not set, you can error out already with a useful message

2021-02-10 08:29 UTC, humblec approved these changes

2021-02-10 08:32 UTC, Madhu-1 commented
>failed to validate encrypted pvc with error timed out waiting for the condition

tests failed for encryption

2021-02-10 08:32 UTC, Madhu-1 commented
/retest ci/centos/mini-e2e-helm/k8s-1.19

2021-02-10 08:32 UTC, Madhu-1 commented
/retest ci/centos/mini-e2e/k8s-1.19

2021-02-11 09:39 UTC, Madhu-1 commented
@nixpanic PTAL

2021-02-11 10:07 UTC, nixpanic approved these changes

2021-02-11 11:31 UTC, merged