cleanup: correct misspelling in rbd/clone.go
ceph/ceph-csi pull request #1952
Opened 2021-04-05 07:16 UTC by humblec

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

2021-04-05 07:24 UTC, Madhu-1 commented on internal/rbd/clone.go
> -		// create new resources for clearner approach
It should be cleaner?

2021-04-05 07:33 UTC, Yuggupta27 requested changes

2021-04-05 07:33 UTC, Yuggupta27 commented on internal/rbd/clone.go
> +		// create new resources for clearer approach
```suggestion
		// create new resources for a cleaner approach
```

2021-04-05 07:36 UTC, humblec commented on internal/rbd/clone.go
> -		// create new resources for clearner approach
Yeah, I was confused too. Looks like cleaner is better.. accommodated..  Thanks  PTAL.

2021-04-05 07:36 UTC, humblec commented on internal/rbd/clone.go
> +		// create new resources for clearer approach
@Yuggupta27 Thanks.. Updated. ptal

2021-04-05 07:47 UTC, Yuggupta27 approved these changes

2021-04-05 09:15 UTC, Madhu-1 approved these changes

2021-04-05 09:34 UTC, merged

2021-04-14 06:28 UTC, Madhu-1 commented
@humblec return-6 branch is created on the main repo can you please delete it.

2021-04-14 06:54 UTC, humblec commented
> @humblec return-8 branch is created on the main repo can you please delete it.

@Madhu-1 not seeing it here https://github.com/ceph/ceph-csi/branches,

2021-04-14 06:55 UTC, Madhu-1 commented
i deleted it before few minutes

2021-04-14 06:56 UTC, humblec commented
> i deleted it before few minutes

Ah.. Thanks :+1: