cleanup: correct typo in travis scripts
ceph/ceph-csi pull request #2000
Opened 2021-04-21 08:05 UTC by humblec

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

2021-04-21 08:12 UTC, Madhu-1 requested changes

2021-04-21 08:12 UTC, Madhu-1 commented on scripts/travis-functest.sh
> +# against different kubernetes version
```suggestion
# against different Kubernetes version
```

2021-04-21 08:12 UTC, Madhu-1 commented on scripts/travis-helmtest.sh
> +# against different kubernetes version
```suggestion
# against different Kubernetes version
```

2021-04-21 08:21 UTC, humblec commented
@Madhu-1 addressed the comment, ptal.  Thanks

2021-04-21 08:22 UTC, Madhu-1 approved these changes

2021-04-21 08:47 UTC, Yuggupta27 approved these changes

2021-04-21 09:22 UTC, merged

2021-06-16 05:18 UTC, Madhu-1 commented
@mergifyio backport release-v3.3