e2e: update sidecar images to latest release.
ceph/ceph-csi pull request #2217
Opened 2021-06-29 04:58 UTC by Rakshith-R

This commit  updates sidecar images to latest release.

Signed-off-by: Rakshith R <rar@redhat.com>

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

2021-06-29 05:28 UTC, Madhu-1 commented
@Rakshith-R please fix commitlint

2021-06-29 06:34 UTC, nixpanic requested changes

2021-06-29 06:34 UTC, nixpanic commented on scripts/minikube.sh
> +    copy_image_to_cluster "${K8S_IMAGE_REPO}"/csi-resizer:v1.2.0 "${K8S_IMAGE_REPO}"/csi-resizer:v1.2.0
This is really easy to forget to update. Please make it easier to see by setting the versions in a variable in `build.env` and use a current version when the variable is not set.

You will need to export the new variables in the `ci/centos` branch too

https://github.com/ceph/ceph-csi/blob/0786d159518286a87fe96d1bcc45f99871dd0ce6/single-node-k8s.sh#L58-L79

2021-06-29 08:04 UTC, Rakshith-R commented on scripts/minikube.sh
> +    copy_image_to_cluster "${K8S_IMAGE_REPO}"/csi-resizer:v1.2.0 "${K8S_IMAGE_REPO}"/csi-resizer:v1.2.0
ok, i'll do that.

2021-07-19 13:01 UTC, humblec commented
@Rakshith-R can you please revisit this PR ?

2021-08-16 08:16 UTC, Rakshith-R commented
> @Rakshith-R can you please revisit this PR ?

Made necessary changes PTAL @humblec @nixpanic

2021-08-16 09:06 UTC, Madhu-1 commented on build.env
> +ATTACHER_VERSION=v3.2.1
add CSI as prefix for all the variables?

2021-08-16 09:06 UTC, Madhu-1 commented on build.env
> +DRIVER_REGISTRAR_VERSION=v2.2.0
NODE_DRIVER_REGISTRAR_VERSION?

2021-08-16 11:15 UTC, nixpanic approved these changes

2021-08-16 11:16 UTC, Madhu-1 approved these changes

2021-08-16 11:17 UTC, merged