doc: update helm chart documentations
ceph/ceph-csi pull request #2236
Opened 2021-07-01 12:51 UTC by yati1998

This commit updates the helm chart documentations
with the configurations available while deploying
these helm charts.

Signed-off-by: Yati Padia <ypadia@redhat.com>

2021-07-05 13:23 UTC, nixpanic commented
@Yuggupta27 , #1786 adds extra options too. These need to be documented when this PR is merged. Maybe review this now, and rebase your PR once this is merged?

2021-07-06 04:46 UTC, Yuggupta27 requested changes
Follow similar suggestions for rbd too.

2021-07-06 04:46 UTC, Yuggupta27 commented on charts/ceph-csi-cephfs/README.md
> +| `serviceAccounts.nodeplugin.create` | Specifies whether a ServiceAccount should be created | `true` |
This seems generic, please specify which ServiceAccount

2021-07-06 04:46 UTC, Yuggupta27 commented on charts/ceph-csi-cephfs/README.md
> +| `serviceAccounts.provisioner.name` | The name of the ServiceAccount to use. If not set and create is true, a name is generated using the fullname | "" |
same everywhere here.

2021-07-06 04:46 UTC, Yuggupta27 commented on charts/ceph-csi-cephfs/README.md
> +| `nodeplugin.name` | Specifies the name | `nodeplugin` |
`Specifies the name` seems general. Please specify which name.

2021-07-06 04:46 UTC, Yuggupta27 commented on charts/ceph-csi-cephfs/README.md
> +| `nodeplugin.plugin.image.repository` | Image | `quay.io/cephcsi/cephcsi` |
`Image` doesn't seem to describe anything. Maybe `Image Repository`?

2021-07-06 04:46 UTC, Yuggupta27 commented on charts/ceph-csi-cephfs/README.md
> +| `nodeplugin.registrar.image.repository` | Image | `k8s.gcr.io/sig-storage/csi-node-driver-registrar` |
`Image` doesn't seem to describe anything. Maybe `Image Repository`?

2021-07-06 04:46 UTC, Yuggupta27 commented on charts/ceph-csi-cephfs/README.md
> +| `provisioner.priorityClassName` | set user created priorityclassName for csi provisioner pods. default is system-cluster-critical which is less priority than system-node-critical | `system-cluster-
```suggestion
| `provisioner.priorityClassName` | Set user created priorityclassName for csi provisioner pods. default is system-cluster-critical which is less priority than system-node-critical | `system-cluster-critical` |
```

2021-07-06 04:46 UTC, Yuggupta27 commented on charts/ceph-csi-cephfs/README.md
> +| `provisioner.priorityClassName` | set user created priorityclassName for csi provisioner pods. default is system-cluster-critical which is less priority than system-node-critical | `system-cluster-
Follow a similar format throughout the Description column. It looks much clear ;)

2021-07-06 04:56 UTC, Yuggupta27 commented
> @Yuggupta27 , #1786 adds extra options too. These need to be documented when this PR is merged. Maybe review this now, and rebase your PR once this is merged?

Sure @nixpanic. Since #1786 is just on the verge of getting merged along with https://github.com/ceph/ceph-csi/pull/2242 , I would prefer not to block that PR as it is up for quite some time. Since this is a doc change, once #1786 is merged, I can add a commit here on this PR to keep the doc changes at the same place. Wdyt?

2021-07-06 12:18 UTC, Yuggupta27 requested changes

2021-07-06 12:18 UTC, Yuggupta27 commented on charts/ceph-csi-cephfs/README.md
> +| `topology.domainLabels`                    | domainLabels define which node labels to use as domains for CSI nodeplugins to advertise their domains                                           | `{}`
```suggestion
| `topology.domainLabels`                    | DomainLabels define which node labels to use as domains for CSI nodeplugins to advertise their domains                                           | `{}`                                               |
```

2021-07-06 12:18 UTC, Yuggupta27 commented on charts/ceph-csi-rbd/README.md
> +| `nodeplugin.priorityClassName`             | set user created priorityclassName for csi plugin pods. default is system-node-critical which is highest priority                                | `syst
```suggestion
| `nodeplugin.priorityClassName`             | Set user created priorityclassName for csi plugin pods. default is system-node-critical which is highest priority                                | `system-node-critical`                             |
```

2021-07-06 12:18 UTC, Yuggupta27 commented on charts/ceph-csi-rbd/README.md
> +| `nodeplugin.podSecurityPolicy.enabled`     | If true, create & use Pod Security [Policy resources](https://kubernetes.io/docs/concepts/policy/pod-security-policy/).                          | `fals
```suggestion
| `nodeplugin.podSecurityPolicy.enabled`     | If true, create & use [Pod Security Policy resources](https://kubernetes.io/docs/concepts/policy/pod-security-policy/).                          | `false`                                            |
```

2021-07-06 12:18 UTC, Yuggupta27 commented on charts/ceph-csi-rbd/README.md
> +| `provisioner.skipForceFlatten`             | skip image flattening if kernel support mapping of rbd images which has the deep-flatten feature                                                 | `fals
```suggestion
| `provisioner.skipForceFlatten`             | Skip image flattening if kernel support mapping of rbd images which has the deep-flatten feature                                                 | `false`                                            |
```

2021-07-06 12:18 UTC, Yuggupta27 commented on charts/ceph-csi-rbd/README.md
> +| `provisioner.priorityClassName`            | Set user created priorityclassName for csi provisioner pods. default is system-cluster-critical which is less priority than system-node-critical | `syst
```suggestion
| `provisioner.priorityClassName`            | Set user created priorityclassName for csi provisioner pods. Default is `system-cluster-critical` which is less priority than `system-node-critical` | `system-cluster-critical`                          |
```

2021-07-07 11:39 UTC, Madhu-1 reviewed
Reviewed cephfs same comments applicable for RBD also.

2021-07-07 11:39 UTC, Madhu-1 commented on charts/ceph-csi-cephfs/README.md
> +| `nodeplugin.registrar.image.repository`    | Image Repository
mention which image Repository? ex node-registrar image repo URL

2021-07-07 11:39 UTC, Madhu-1 commented on charts/ceph-csi-cephfs/README.md
> +| `nodeplugin.tolerations`                   | List of Kubernetes `tolerations` to add to the Deployment                                                                                        | `{}`
its daemonset not deployment?

2021-07-07 11:39 UTC, Madhu-1 commented on charts/ceph-csi-cephfs/README.md
> +| `provisioner.timeout`                      | Timeout for waiting for creation or deletion of a volume                                                                                         | `60s`
mention as GRPC timeout?

2021-07-07 11:39 UTC, Madhu-1 commented on charts/ceph-csi-cephfs/README.md
> +| `provisioner.resizer.image.repository`     | Specifies the csi-resizer sidecar                                                                                                                | `k8s.
keep it similar to another comment about repository

2021-07-07 11:39 UTC, Madhu-1 commented on charts/ceph-csi-cephfs/README.md
> +| `provisioner.affinity`                     | Specifies the affinity                                                                                                                           | `{}`
mentiond about provisioner like ` Specify node selector  for provisioner deployment`

2021-07-07 11:39 UTC, Madhu-1 commented on charts/ceph-csi-cephfs/README.md
> +| `configMapName`                            | Name of the configmap used for state                                                                                                             | `ceph
Name of the configmap which contains cluster configuration

2021-07-07 11:39 UTC, Madhu-1 commented on charts/ceph-csi-cephfs/README.md
> +Specify each parameter using the --set key=value argument to helm install.
provide an example here?

2021-07-08 09:05 UTC, nixpanic approved these changes

2021-07-08 09:19 UTC, Madhu-1 approved these changes

2021-07-08 09:44 UTC, merged