doc: Updates the helm doc
ceph/ceph-csi pull request #2257
Opened 2021-07-08 15:25 UTC by yati1998

This commit updates the helm doc with
storageclass and secret configurations.

Fixes: #2255

Signed-off-by: Yati Padia <ypadia@redhat.com>

2021-07-08 15:28 UTC, nixpanic requested changes
Can you please update the subject of the commit? The title should mention the added options a little instead of the uninformative "updates helm doc".

2021-07-09 08:00 UTC, nixpanic submitted a review, later dismissed

2021-07-09 09:16 UTC, Yuggupta27 requested changes
To configure the deployment of StorageClass ad Secrets, apart from just `name` and `create`, there are multiple parameters that can be set by the user. Can you please add those too?
See [this](https://github.com/ceph/ceph-csi/blob/devel/charts/ceph-csi-rbd/values.yaml#L235) for reference

2021-07-09 09:16 UTC, Yuggupta27 commented on charts/ceph-csi-cephfs/README.md
> +| `storageClass.create`                      | Specifies whether the Storage class should be created                                                                                                | `
```suggestion
| `storageClass.create`                      | Specifies whether the StorageClass should be created                                                                                                | `false`                                            |
```

2021-07-09 09:16 UTC, Yuggupta27 commented on charts/ceph-csi-rbd/README.md
> +| `storageClass.create`                      | Specifies whether the Storage class should be created                                                                                                | `
```suggestion
| `storageClass.create`                      | Specifies whether the StorageClass should be created                                                                                                | `false`                                            |
```

2021-07-09 10:30 UTC, yati1998 commented
> To configure the deployment of StorageClass ad Secrets, apart from just `name` and `create`, there are multiple parameters that can be set by the user. Can you please add those too?
> See [this](https://github.com/ceph/ceph-csi/blob/devel/charts/ceph-csi-rbd/values.yaml#L235) for reference

Sure

2021-07-09 13:43 UTC, nixpanic approved these changes

2021-07-12 11:41 UTC, humblec approved these changes

2021-07-12 12:03 UTC, merged