rbd: fix vol.VolID in cloneFromSnapshot()
ceph/ceph-csi pull request #2260
Opened 2021-07-09 09:12 UTC by Rakshith-R

Volume generated from snap using genrateVolFromSnap
already copies volume ID correctly, therefore removing
`vol.VolID = rbdVol.VolID` which wrongly copies parent
Volume ID instead leading to error from copyEncryption()
on parent and clone volume ID being equal.

Signed-off-by: Rakshith R <rar@redhat.com>

<details>
<summary>
Logs
</summary>

```
I0709 05:48:19.899510       1 identityserver-default.go:38] ID: 20 Using default GetPluginInfo
I0709 05:48:19.899585       1 utils.go:182] ID: 20 GRPC response: {"name":"rook-ceph.rbd.csi.ceph.com","vendor_version":"canary"}
I0709 05:48:19.903851       1 utils.go:171] ID: 21 Req-ID: snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 GRPC call: /csi.v1.Controller/CreateSnapshot
I0709 05:48:19.904174       1 utils.go:175] ID: 21 Req-ID: snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 GRPC request: {"name":"snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2","parameters":{"clusterID":"rook-ceph"},"secrets":"***stripped***","source_volume_id":"0001-0009-rook-ceph-0000000000000001-9c4c4997-e078-11eb-9aa0-0242ac110005"}
I0709 05:48:19.918382       1 omap.go:84] ID: 21 Req-ID: snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 got omap values: (pool="replicapool", namespace="", name="csi.volume.9c4c4997-e078-11eb-9aa0-0242ac110005"): map[csi.imageid:116b87d2743c csi.imagename:csi-vol-9c4c4997-e078-11eb-9aa0-0242ac110005 csi.volname:pvc-4dc3aa8b-1fea-4e78-9f85-9beecf39639a csi.volume.encryptKMS:user-ns-secrets-metadata-test csi.volume.owner:rook-ceph]
E0709 05:48:19.937789       1 omap.go:77] ID: 21 Req-ID: snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 omap not found (pool="replicapool", namespace="", name="csi.snaps.default"): rados: ret=-2, No such file or directory
I0709 05:48:19.952186       1 omap.go:148] ID: 21 Req-ID: snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 set omap keys (pool="replicapool", namespace="", name="csi.snaps.default"): map[csi.snap.snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2:43e1f4b4-e079-11eb-bda3-0242ac110005])
I0709 05:48:19.954816       1 omap.go:148] ID: 21 Req-ID: snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 set omap keys (pool="replicapool", namespace="", name="csi.snap.43e1f4b4-e079-11eb-bda3-0242ac110005"): map[csi.imagename:csi-snap-43e1f4b4-e079-11eb-bda3-0242ac110005 csi.snapname:snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 csi.source:csi-vol-9c4c4997-e078-11eb-9aa0-0242ac110005 csi.volume.encryptKMS:user-ns-secrets-metadata-test csi.volume.owner:rook-ceph])
I0709 05:48:19.954834       1 rbd_journal.go:408] ID: 21 Req-ID: snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 generated Volume ID (0001-0009-rook-ceph-0000000000000001-43e1f4b4-e079-11eb-bda3-0242ac110005) and image name (csi-snap-43e1f4b4-e079-11eb-bda3-0242ac110005) for request name (snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2)
I0709 05:48:19.954868       1 rbd_util.go:1142] ID: 21 Req-ID: snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 rbd: snap create replicapool/csi-vol-9c4c4997-e078-11eb-9aa0-0242ac110005@csi-snap-43e1f4b4-e079-11eb-bda3-0242ac110005 using mon 192.168.39.136:6789
I0709 05:48:20.162401       1 rbd_util.go:1199] ID: 21 Req-ID: snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 rbd: clone replicapool/csi-vol-9c4c4997-e078-11eb-9aa0-0242ac110005@csi-snap-43e1f4b4-e079-11eb-bda3-0242ac110005 replicapool/csi-snap-43e1f4b4-e079-11eb-bda3-0242ac110005 (features: [layering deep-flatten]) using mon 192.168.39.136:6789
I0709 05:48:20.201395       1 rbd_util.go:1154] ID: 21 Req-ID: snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 rbd: snap rm replicapool/csi-vol-9c4c4997-e078-11eb-9aa0-0242ac110005@csi-snap-43e1f4b4-e079-11eb-bda3-0242ac110005 using mon 192.168.39.136:6789
I0709 05:48:20.423415       1 encryption.go:75] image replicapool/csi-vol-9c4c4997-e078-11eb-9aa0-0242ac110005 encrypted state metadata reports "encryptionPrepared"
I0709 05:48:20.498974       1 omap.go:148] ID: 21 Req-ID: snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 set omap keys (pool="replicapool", namespace="", name="csi.snap.43e1f4b4-e079-11eb-bda3-0242ac110005"): map[csi.imageid:11c953ba8286])
I0709 05:48:20.529096       1 rbd_util.go:677] ID: 21 Req-ID: snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 clone depth is (1), configured softlimit (4) and hardlimit (8) for replicapool/csi-snap-43e1f4b4-e079-11eb-bda3-0242ac110005
I0709 05:48:20.529362       1 utils.go:182] ID: 21 Req-ID: snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 GRPC response: {"snapshot":{"creation_time":{"nanos":176795825,"seconds":1625809700},"size_bytes":1073741824,"snapshot_id":"0001-0009-rook-ceph-0000000000000001-43e1f4b4-e079-11eb-bda3-0242ac110005","source_volume_id":"0001-0009-rook-ceph-0000000000000001-9c4c4997-e078-11eb-9aa0-0242ac110005"}}
I0709 05:48:20.568957       1 utils.go:171] ID: 22 GRPC call: /csi.v1.Identity/GetPluginInfo
I0709 05:48:20.568997       1 utils.go:175] ID: 22 GRPC request: {}
I0709 05:48:20.569020       1 identityserver-default.go:38] ID: 22 Using default GetPluginInfo
I0709 05:48:20.569040       1 utils.go:182] ID: 22 GRPC response: {"name":"rook-ceph.rbd.csi.ceph.com","vendor_version":"canary"}
I0709 05:48:20.569539       1 utils.go:171] ID: 23 Req-ID: snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 GRPC call: /csi.v1.Controller/CreateSnapshot
I0709 05:48:20.569608       1 utils.go:175] ID: 23 Req-ID: snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 GRPC request: {"name":"snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2","parameters":{"clusterID":"rook-ceph"},"secrets":"***stripped***","source_volume_id":"0001-0009-rook-ceph-0000000000000001-9c4c4997-e078-11eb-9aa0-0242ac110005"}
I0709 05:48:20.570437       1 omap.go:84] ID: 23 Req-ID: snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 got omap values: (pool="replicapool", namespace="", name="csi.volume.9c4c4997-e078-11eb-9aa0-0242ac110005"): map[csi.imageid:116b87d2743c csi.imagename:csi-vol-9c4c4997-e078-11eb-9aa0-0242ac110005 csi.volname:pvc-4dc3aa8b-1fea-4e78-9f85-9beecf39639a csi.volume.encryptKMS:user-ns-secrets-metadata-test csi.volume.owner:rook-ceph]
I0709 05:48:20.596760       1 omap.go:84] ID: 23 Req-ID: snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 got omap values: (pool="replicapool", namespace="", name="csi.snaps.default"): map[csi.snap.snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2:43e1f4b4-e079-11eb-bda3-0242ac110005]
I0709 05:48:20.597293       1 omap.go:84] ID: 23 Req-ID: snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 got omap values: (pool="replicapool", namespace="", name="csi.snap.43e1f4b4-e079-11eb-bda3-0242ac110005"): map[csi.imageid:11c953ba8286 csi.imagename:csi-snap-43e1f4b4-e079-11eb-bda3-0242ac110005 csi.snapname:snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 csi.source:csi-vol-9c4c4997-e078-11eb-9aa0-0242ac110005 csi.volume.encryptKMS:user-ns-secrets-metadata-test csi.volume.owner:rook-ceph]
I0709 05:48:20.639290       1 rbd_util.go:1142] ID: 23 Req-ID: snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 rbd: snap create replicapool/csi-vol-9c4c4997-e078-11eb-9aa0-0242ac110005@csi-snap-43e1f4b4-e079-11eb-bda3-0242ac110005 using mon 192.168.39.136:6789
E0709 05:48:21.169785       1 utils.go:180] ID: 23 Req-ID: snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 GRPC error: rpc error: code = Internal desc = snapshot not found: snap replicapool/csi-vol-9c4c4997-e078-11eb-9aa0-0242ac110005@csi-snap-43e1f4b4-e079-11eb-bda3-0242ac110005 not found
I0709 05:48:21.179357       1 utils.go:171] ID: 24 GRPC call: /csi.v1.Identity/GetPluginInfo
I0709 05:48:21.179534       1 utils.go:175] ID: 24 GRPC request: {}
I0709 05:48:21.179545       1 identityserver-default.go:38] ID: 24 Using default GetPluginInfo
I0709 05:48:21.179605       1 utils.go:182] ID: 24 GRPC response: {"name":"rook-ceph.rbd.csi.ceph.com","vendor_version":"canary"}
I0709 05:48:21.182207       1 utils.go:171] ID: 25 Req-ID: snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 GRPC call: /csi.v1.Controller/CreateSnapshot
I0709 05:48:21.182402       1 utils.go:175] ID: 25 Req-ID: snapshot-bba33d6c-d407-4bfa-a6c9-e6238e6750c2 GRPC request: {"name":"snapshot-bba33d [...]

2021-07-09 09:17 UTC, Madhu-1 commented
@Rakshith-R just a question if this can be easily reproduced why didn't get caught in CI? can you see anything we are missing in CI and anything need to be added?

2021-07-09 09:20 UTC, humblec commented
> @Rakshith-R just a question if this can be easily reproduced why didn't get caught in CI? can you see anything we are missing in CI and anything need to be added?

yeah, interesting that it was not caught on r our e2e... 
@Rakshith-R while you say `will happen when number of snapshots hits flatten limit` -> what is the limit you are mentioning ?

2021-07-09 09:20 UTC, Rakshith-R commented
> @Rakshith-R just a question if this can be easily reproduced why didn't get caught in CI? can you see anything we are missing in CI and anything need to be added?

Basically, most of our tests pass in one go in ci (a single request). 

This can only be caught when snapshotting process either returns a `readyTouse=false` (have to flatten) or process is killed in between(in some precise step of the control flow) basically leaving some omap entry/snaps/clones to continue from.

2021-07-09 09:21 UTC, nixpanic submitted a review, later dismissed
Indeed strange that this was not caught earlier. Maybe e2e testing is not complete?

2021-07-09 09:25 UTC, Rakshith-R commented
> > @Rakshith-R just a question if this can be easily reproduced why didn't get caught in CI? can you see anything we are missing in CI and anything need to be added?
> 
> yeah, interesting that it was not caught on r our e2e...
> @Rakshith-R while you say `will happen when number of snapshots hits flatten limit` -> what is the limit you are mentioning ?

Scratch ~~number of snapshots~~ , I meant what this function does https://github.com/ceph/ceph-csi/blob/b27d6319ca8b16004ecbc00f71393821594de712/internal/rbd/rbd_util.go#L663

2021-07-09 09:29 UTC, Rakshith-R commented
https://github.com/ceph/ceph-csi/blob/devel/docs/design/proposals/rbd-snap-clone.md#rbd-cli-commands-to-create-snapshot
This step, which would trigger a follow up request from external-snapshotter
```
// check the depth, if the depth is greater than configured hardlimit add a
// task to flatten the cloned image, return snapshot status ready as `false`,
// if the depth is greater than softlimit add a task to flatten the image
// and return success
ceph rbd task add flatten <RBD image for temporary snap image>
```
Or can also be caused from a very well(or very ill) timed container restart.

2021-07-09 09:32 UTC, Madhu-1 commented
https://github.com/ceph/ceph-csi/blob/680a7bf411b58858d88f56d5a5a045baa2e743bb/scripts/install-helm.sh#L176

```
--set provisioner.maxSnapshotsOnImage=3 --set provisioner.minSnapshotsOnImage=2
```

I think we are missing to `rbdhardmaxclonedepth` and `rbdsoftmaxclonedepth` to 1 or 2 and see this can be caught in CI?

* Create PVC
* Create PVC clone (if required create chain of  clones)
* Create snapshot from clone -> this will cause the flatten to happen

can you see this helps?

2021-07-09 09:37 UTC, Rakshith-R commented
> https://github.com/ceph/ceph-csi/blob/680a7bf411b58858d88f56d5a5a045baa2e743bb/scripts/install-helm.sh#L176
> 
> ```
> --set provisioner.maxSnapshotsOnImage=3 --set provisioner.minSnapshotsOnImage=2
> ```
> 
> I think we are missing to `rbdhardmaxclonedepth` and `rbdsoftmaxclonedepth` to 1 or 2 and see this can be caught in CI?
> 
> * Create PVC
> * Create PVC clone (if required create chain of  clones)
> * Create snapshot from clone -> this will cause the flatten to happen
> 
> can you see this helps?

Or creating a long chain of snapshot /& clones. 
This ideally should trigger both soft and hard limit.


And as to snapshot limit, it is flattened at the very begining of request https://github.com/ceph/ceph-csi/blob/b27d6319ca8b16004ecbc00f71393821594de712/internal/rbd/controllerserver.go#L934 . I don't think it matters much. (referred to this instead of rbd image chain Depth by mistake :sweat_smile: )

2021-07-09 09:40 UTC, Madhu-1 commented
> > https://github.com/ceph/ceph-csi/blob/680a7bf411b58858d88f56d5a5a045baa2e743bb/scripts/install-helm.sh#L176
> > 
> > ```
> > --set provisioner.maxSnapshotsOnImage=3 --set provisioner.minSnapshotsOnImage=2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think we are missing to `rbdhardmaxclonedepth` and `rbdsoftmaxclonedepth` to 1 or 2 and see this can be caught in CI?
> > 
> > * Create PVC
> > * Create PVC clone (if required create chain of  clones)
> > * Create snapshot from clone -> this will cause the flatten to happen
> > 
> > can you see this helps?
> 
> Or creating a long chain of snapshot /& clones.
> This ideally should trigger both soft and hard limit.
> 
> And as to snapshot limit, it is flattened at the very begining of request
> 
> https://github.com/ceph/ceph-csi/blob/b27d6319ca8b16004ecbc00f71393821594de712/internal/rbd/controllerserver.go#L934
> 
> . I don't think it matters much. (referred to this instead of rbd image chain Depth by mistake 😅 )

Yes that also helps. Can you please add it

2021-07-09 09:44 UTC, Madhu-1 commented
Can you also add a commit to set hard and soft limit to lower values in helm? This will avoid creating larger chain to test this one

2021-07-09 12:15 UTC, humblec commented
> Or creating a long chain of snapshot /& clones.
> This ideally should trigger both soft and hard limit.
> 
> And as to snapshot limit, it is flattened at the very begining of request
> 
> https://github.com/ceph/ceph-csi/blob/b27d6319ca8b16004ecbc00f71393821594de712/internal/rbd/controllerserver.go#L934
> . I don't think it matters much. (referred to this instead of rbd image chain Depth by mistake sweat_smile )

Yeah, that clarifies it, :+1:

2021-07-09 14:24 UTC, agarwal-mudit commented
/retest ci/centos/k8s-e2e-external-storage/1.21

2021-07-09 14:24 UTC, agarwal-mudit commented
/retest ci/centos/mini-e2e-helm/k8s-1.21

2021-07-09 14:44 UTC, agarwal-mudit commented
/retest ci/centos/mini-e2e-helm/k8s-1.21

2021-07-09 14:59 UTC, obnoxxx commented
> > @Rakshith-R just a question if this can be easily reproduced why didn't get caught in CI? can you see anything we are missing in CI and anything need to be added?
> 
> Basically, most of our tests pass in one go in ci (a single request).
> 
> This can only be caught when snapshotting process either returns a `readyTouse=false` (have to flatten) or process is killed in between(in some precise step of the control flow) basically leaving some omap entry/snaps/clones to continue from.

If I had anything to say here, I would request a fix like this to be accompanied by a commit adding or expanding a test case to prove that the pre-fix state is wrong, in this very PR! 😄 

More thoughts:

* If there is no regular/deterministic way of creating a snapshot resulting in `readyToUse = false`, then we should create this possibility in the test code.
* My gut feeling says it should be possible to cover this with a unit / subsystem test, should not require e2e test.

2021-07-09 15:14 UTC, obnoxxx requested changes
I don't really have a voice here, but I would request to add a test case (as a separate commit in this same PR) for this if possible.

2021-07-09 15:16 UTC, Rakshith-R commented
> If I had anything to say here, I would request a fix like this to be accompanied by a commit adding or expanding a test case to prove that the pre-fix state is wrong, in this very PR! 

Modified args 
```
            - '--rbdhardmaxclonedepth=1'
            - '--rbdsoftmaxclonedepth=0'
```
Which will flatten all the clones/snaps/restores. 
> More thoughts:
> 
> * If there is no regular/deterministic way of creating a snapshot resulting in `readyToUse = false`, then we should create this possibility in the test code.

This will surely result in `readyToUse = false`, :crossed_fingers: hope e2e does not timeout though

> * My gut feeling says it should be possible to cover this with a unit / subsystem test, should not require e2e test.

Needs interaction with ceph cluster, so not possible.

2021-07-09 15:19 UTC, Rakshith-R commented
> I don't really have a voice here, but I would request to add a test case (as a separate commit in this same PR) for this if possible.

We also add a task to flatten image(during snap/clone/restore), so cannot effectively guarantee depth of image to be a certain value(at a certain time). 
But we can decrease the limit as I've done in helm_install.sh so it should act as e2e test.

2021-07-09 15:24 UTC, obnoxxx commented
> > I don't really have a voice here, but I would request to add a test case (as a separate commit in this same PR) for this if possible.
> 
> We also add a task to flatten image(during snap/clone/restore), so cannot effectively guarantee depth of image to be a certain value(at a certain time).
> But we can decrease the limit as I've done in helm_install.sh so it should act as e2e test.

But this is not an explicit test for this error, right? An explicit test would check the vo-ids after `cloneFromSnapshot` function. Are we sure this will fail e2e tests without the code fix?

2021-07-09 15:29 UTC, Rakshith-R commented
> But this is not an explicit test for this error, right? An explicit test would check the vo-ids after `cloneFromSnapshot` function. 
>Are we sure this will fail e2e tests without the code fix?

yes, it will fail. 
Tested with those arguments and here's the logs https://hackmd.io/7pDqtCupRtiZrRlrz_fHDw

2021-07-12 03:32 UTC, Madhu-1 commented on scripts/install-helm.sh
> +    "${HELM}" install --namespace ${NAMESPACE} --set provisioner.fullnameOverride=csi-rbdplugin-provisioner --set nodeplugin.fullnameOverride=csi-rbdplugin --set configMapName=ceph-csi-config --set p
set these values to 2 and 3 respectively. or else https://github.com/ceph/ceph-csi/blob/devel/internal/rbd/nodeserver.go#L301-L306 will not get tested in nodeserver

2021-07-12 03:34 UTC, Madhu-1 commented on scripts/install-helm.sh
> +    "${HELM}" install --namespace ${NAMESPACE} --set provisioner.fullnameOverride=csi-rbdplugin-provisioner --set nodeplugin.fullnameOverride=csi-rbdplugin --set configMapName=ceph-csi-config --set p
okay, discard this one. this will get tested in the non-helm scenario

2021-07-12 03:35 UTC, Madhu-1 approved these changes

2021-07-12 03:36 UTC, Madhu-1 commented
/test ci/centos/mini-e2e-helm/k8s-1.20

2021-07-12 03:45 UTC, Madhu-1 commented
@Rakshith-R can you please check PVC clones e2e.

2021-07-12 04:14 UTC, Madhu-1 requested changes

2021-07-12 04:14 UTC, Madhu-1 commented on scripts/install-helm.sh
> +    "${HELM}" install --namespace ${NAMESPACE} --set provisioner.fullnameOverride=csi-rbdplugin-provisioner --set nodeplugin.fullnameOverride=csi-rbdplugin --set configMapName=ceph-csi-config --set p
okay with this change a real bug was caught, looks like the Pvc-pvc clone is not working as expected and an image leak is happening.

2021-07-12 05:24 UTC, humblec commented
> > But this is not an explicit test for this error, right? An explicit test would check the vo-ids after `cloneFromSnapshot` function.
> > Are we sure this will fail e2e tests without the code fix?
> 
> yes, it will fail.
> Tested with those arguments and here's the logs https://hackmd.io/7pDqtCupRtiZrRlrz_fHDw

Tweaking the soft/hard  limits or both with allowed values would be one good to way to bring up the failure scenarios here. Looks like  we need to add few test cases here with different values which could help us to reveal the flow we are going wrong.

2021-07-15 12:28 UTC, Rakshith-R commented
Both the following e2e is failing at `validate clones in different pool` e2e. 
[helm-1.21](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.21/detail/mini-e2e-helm_k8s-1.21/320/pipeline/ ) ,
[helm-1.20](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.20/detail/mini-e2e-helm_k8s-1.20/1655/pipeline/)

Also https://github.com/ceph/ceph-csi/issues/1883 is hit at 

```
I0715 11:13:56.839829       1 utils.go:171] ID: 707 Req-ID: pvc-4e5cbe5f-1623-402e-982a-26a08b6da064 GRPC call: /csi.v1.Controller/CreateVolume
I0715 11:13:56.840227       1 utils.go:175] ID: 707 Req-ID: pvc-4e5cbe5f-1623-402e-982a-26a08b6da064 GRPC request: {"accessibility_requirements":{"preferred":[{"segments":{"topology.rbd.csi.ceph.com/region":"testregion","topology.rbd.csi.ceph.com/zone":"testzone"}}],"requisite":[{"segments":{"topology.rbd.csi.ceph.com/region":"testregion","topology.rbd.csi.ceph.com/zone":"testzone"}}]},"capacity_range":{"required_bytes":1073741824},"name":"pvc-4e5cbe5f-1623-402e-982a-26a08b6da064","parameters":{"clusterID":"cd8b81d5-27be-44a3-8230-d3e1a2369def","csi.storage.k8s.io/pv/name":"pvc-4e5cbe5f-1623-402e-982a-26a08b6da064","csi.storage.k8s.io/pvc/name":"rbd-32741","csi.storage.k8s.io/pvc/namespace":"rbd-3274","imageFeatures":"layering","pool":"clone-test","thickProvision":"false"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["discard"]}},"access_mode":{"mode":1}}],"volume_content_source":{"Type":{"Snapshot":{"snapshot_id":"0001-0024-cd8b81d5-27be-44a3-8230-d3e1a2369def-0000000000000002-60e3ec6e-e55d-11eb-9cdd-5ef793f1116d"}}}}
I0715 11:13:56.840502       1 rbd_util.go:1067] ID: 707 Req-ID: pvc-4e5cbe5f-1623-402e-982a-26a08b6da064 setting disableInUseChecks: false image features: [layering] mounter: rbd
E0715 11:13:56.841579       1 omap.go:77] ID: 707 Req-ID: pvc-4e5cbe5f-1623-402e-982a-26a08b6da064 omap not found (pool="replicapool", namespace="", name="csi.snap.60e3ec6e-e55d-11eb-9cdd-5ef793f1116d"): rados: ret=-2, No such file or directory
W0715 11:13:56.841620       1 voljournal.go:672] ID: 707 Req-ID: pvc-4e5cbe5f-1623-402e-982a-26a08b6da064 unable to read omap keys: pool or key missing: key not found: rados: ret=-2, No such file or directory
E0715 11:13:56.841643       1 controllerserver.go:682] ID: 707 Req-ID: pvc-4e5cbe5f-1623-402e-982a-26a08b6da064 failed to get backend snapshot for 0001-0024-cd8b81d5-27be-44a3-8230-d3e1a2369def-0000000000000002-60e3ec6e-e55d-11eb-9cdd-5ef793f1116d: key not found: no snap source in omap for "csi.snap.60e3ec6e-e55d-11eb-9cdd-5ef793f1116d"
E0715 11:13:56.841725       1 utils.go:180] ID: 707 Req-ID: pvc-4e5cbe5f-1623-402e-982a-26a08b6da064 GRPC error: rpc error: code = Internal desc = key not found: no snap source in omap for "csi.snap.60e3ec6e-e55d-11eb-9cdd-5ef793f1116d"
```

2021-07-16 13:21 UTC, Rakshith-R commented
/retest all

2021-07-16 13:21 UTC, Rakshith-R commented
> /retest all

resesting to capture more such fails.

2021-07-22 08:03 UTC, Madhu-1 commented
@Rakshith-R PR need manual rebase

2021-07-27 08:20 UTC, nixpanic requested changes
no issues that I can spot, except for the commit messages that need correcting

2021-07-27 08:20 UTC, nixpanic commented on internal/rbd/clone.go
> +	err := tempClone.checkSnapExists(snap)
the commit `rbd: fix clone problem` does not contain any description. It would be good to describe what problem is fixed (and how).

2021-07-27 08:20 UTC, nixpanic commented on internal/rbd/controllerserver.go
> +	"fmt"
several typos in the description of commit `rbd: fix snapshot id idempotency issue`

2021-07-30 08:56 UTC, Rakshith-R commented
Removed commit to `set hard and soft limit to lower values in helm`, as this may trigger https://github.com/ceph/ceph-csi/issues/2327 and cause instability in our ci. 

@nixpanic @humblec @Madhu-1 PTAL

2021-08-03 08:09 UTC, humblec submitted a review, later dismissed

2021-08-03 11:00 UTC, Rakshith-R commented
/restest ci/centos/mini-e2e-helm

2021-08-03 11:02 UTC, Rakshith-R commented
/retest ci/centos/mini-e2e-helm

2021-08-03 11:03 UTC, Rakshith-R commented
> /retest ci/centos/mini-e2e-helm

`Aug  3 09:47:08.230: INFO: At 2021-08-03 09:37:17 +0100 BST - event for pod-run-as-non-root: {kubelet minikube} Failed: Failed to pull image "registry.centos.org/centos:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://registry.centos.org/v2/: x509: certificate has expired or is not yet valid`

https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.19/detail/mini-e2e-helm_k8s-1.19/2287/pipeline/
https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.20/detail/mini-e2e-helm_k8s-1.20/1880/pipeline/

2021-08-03 15:31 UTC, nixpanic commented on e2e/rbd.go
> +						map[string]string{
There is no test without encryption anymore? If encryption is needed to be tested with this combination, a new test should be added.

2021-08-04 08:40 UTC, Madhu-1 commented
@Rakshith-R is this PR also fixing https://github.com/ceph/ceph-csi/issues/1883 if yes please add Fixes to the PR description.

2021-08-06 05:15 UTC, Rakshith-R commented
> @Rakshith-R is this PR also fixing #1883 if yes please add Fixes to the PR description.

Done, PTAL @nixpanic @Madhu-1 @humblec

2021-08-06 06:58 UTC, nixpanic approved these changes

2021-08-06 08:46 UTC, humblec approved these changes

2021-08-06 10:19 UTC, Rakshith-R commented
@Mergifyio rebase

2021-08-06 12:18 UTC, Rakshith-R commented
/retest ci/centos/upgrade-tests-rbd

2021-08-06 12:19 UTC, Rakshith-R commented
> /retest ci/centos/upgrade-tests-rbd

failed due to #2264  
[logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/upgrade-tests-rbd/detail/upgrade-tests-rbd/2581/pipeline)

2021-08-06 12:38 UTC, Rakshith-R commented
/retest ci/centos/mini-e2e/k8s-1.20

2021-08-06 12:38 UTC, Rakshith-R commented
> /retest ci/centos/mini-e2e/k8s-1.20

failed due to #2264
[logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.20/detail/mini-e2e_k8s-1.20/1996/pipeline/70)

2021-08-09 05:08 UTC, Rakshith-R commented
@Madhu-1 ,This pr is waiting for your final review/approval PTAL 
Thanks!

2021-08-09 05:15 UTC, Madhu-1 approved these changes

2021-08-09 05:15 UTC, Madhu-1 commented on internal/rbd/rbd_journal.go
> +	// TODO: check image needs flattening and completed?
create an issue to track this one.

2021-08-09 05:50 UTC, Rakshith-R commented
/retest ci/centos/mini-e2e/k8s-1.21

2021-08-09 05:52 UTC, Rakshith-R commented
> /retest ci/centos/mini-e2e/k8s-1.21

failed due to #2264 
[logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.21/detail/mini-e2e_k8s-1.21/671/pipeline)

2021-08-09 07:28 UTC, merged