fix incorrect beta apiVersion for csidriver used in older kubernetes versions
ceph/ceph-csi pull request #2281
Opened 2021-07-13 19:25 UTC by thojkooi

# Describe what this PR does #

Ran into this when installing this on a 1.17 cluster.
This MR fixes a typo for installing the CSIDriver resource in Kubernetes versions before 1.18. This should have been `storage.k8s.io/v1beta1`.
See: https://kubernetes-csi.github.io/docs/csi-driver-object.html#changes-from-alpha-to-beta

## Is there anything that requires special attention ##

n/a

## Related issues ##

n/a

## Future concerns ##

n/a

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

2021-07-14 02:56 UTC, Madhu-1 commented
> * [new branch]          devel      -> origin/devel
commitlint --verbose --from origin/devel
⧗   input: fix incorrect beta apiVersion for csidriver used in older kubernetes versions
See: https://kubernetes-csi.github.io/docs/csi-driver-object.html#changes-from-alpha-to-beta
Signed-off-by: Thomas Kooi <t.j.kooi@avisi.nl>
✖   header must not be longer than 72 characters, current length is 77 [header-max-length]
✖   subject may not be empty [subject-empty]
⚠   body's lines must not be longer than 80 characters [body-max-line-length]

✖   found 2 problems, 1 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
make: *** [Makefile:151: commitlint] Error 1
make: *** [Makefile:189: containerized-test] Error 2
Error: Process completed with exit code 2.

@thojkooi can you please fix the commitlint

2021-07-14 04:43 UTC, Rakshith-R commented
hey @thojkooi , Thanks for the pr ! 

Can you modify ur commit message to something similar to 
`cleanup: fix incorrect beta apiVersion for csidriver`
Refer to https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#commit-messages for more details . 

Otherwise, this pr look good to me !

2021-07-14 09:00 UTC, Rakshith-R commented
@thojkooi please fix the following too 
```
⧗   input: fix incorrect beta apiVersion for csidriver used in older kubernetes versions

See: https://kubernetes-csi.github.io/docs/csi-driver-object.html#changes-from-alpha-to-beta

Signed-off-by: Thomas Kooi <t.j.kooi@avisi.nl>
✖   header must not be longer than 72 characters, current length is 77 [header-max-length]
✖   subject may not be empty [subject-empty]
⚠   body's lines must not be longer than 80 characters [body-max-line-length]
```
ideally, shorter header message and truncated body lines like
 ```
 cleanup: fix incorrect beta apiVersion for csidrive
 
 This MR fixes a typo for installing the CSIDriver resource
 in Kubernetes versions before 1.18. 
This should have been storage.k8s.io/v1beta1.

Signed-off-by: Thomas Kooi <t.j.kooi@avisi.nl> 
 ```
Thanks

2021-07-14 10:54 UTC, thojkooi commented
Sorry, should be fixed now! Thanks for the help.

2021-07-14 10:58 UTC, yati1998 approved these changes
LGTM

2021-07-14 11:17 UTC, Madhu-1 approved these changes

2021-07-14 11:50 UTC, Yuggupta27 approved these changes

2021-07-14 14:36 UTC, nixpanic commented
@mergifyio rebase

More changes were merged recently, including better failure handling for some CI issues.

2021-07-14 14:56 UTC, Madhu-1 commented
@thojkooi can you please provide access to allow changes to this pull request https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork. so Mergify bot can rebase and merge this PR

2021-07-14 15:11 UTC, pkalever requested changes
Could you also fix the matching comments?
```
examples/cephfs/snapshot.yaml:# v1betav1:
examples/cephfs/snapshotclass.yaml:# v1betav1:
examples/rbd/snapshot.yaml:# v1betav1:
examples/rbd/snapshotclass.yaml:# v1betav1:
```

2021-07-15 05:52 UTC, Yuggupta27 commented
/retest ci/centos/mini-e2e/k8s-1.21

2021-07-15 12:30 UTC, nixpanic commented
@thojkooi this project uses mergify.io for rebasing all PRs on top of the branch before they get merged. That means, PRs get only merged when there have been no recent changes to the base branch (`devel`), and all required tests have passed.

For the Mergify-bot, it is required that you allow the maintainers of this project to update the branch that was used to create this PR. You can enable that on the right side of the PR, there is a checkbox like this:

![image](https://user-images.githubusercontent.com/400257/125787931-b146fa8e-f43a-40c9-88bf-dde63d73cf61.png)

If for whatever reason you can not accept/enable that, let us know and we can create a new PR with your change for you.

Thanks!

2021-07-21 06:48 UTC, nixpanic commented
@mergifyio rebase

Checking if the permissions of the PR have been corrected. When mergify can rebase the PR, it will merge it once tests have passed.

2021-07-21 06:52 UTC, nixpanic commented
#2310 is a replacement for this PR. Once it is merged, this one will automatically be closed.

2021-07-22 09:12 UTC, closed without merging