build: install specific commitlint version
ceph/ceph-csi pull request #2333
Opened 2021-07-29 10:51 UTC by Madhu-1

commitlint 13.1.0 is causing issues when PR is backported from devel branch to release branch https://github.com/ceph/ceph-csi/pull/2332#issuecomment-888325775. Let's revert back to commitlint 12.1.4 where we have not seen any issue with backports to release branch.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

2021-07-29 10:54 UTC, pkalever commented on scripts/Dockerfile.test
> +    && npm install @commitlint/cli@"{COMMITLINT_VERSION}" \
Should we use "${COMMITLINT_VERSION}" ?

2021-07-29 10:56 UTC, pkalever requested changes
This probably need some adjustments @Madhu-1

2021-07-29 10:57 UTC, Madhu-1 commented on scripts/Dockerfile.test
> +    && npm install @commitlint/cli@"{COMMITLINT_VERSION}" \
Yes correct. fixed now.

2021-07-29 11:02 UTC, pkalever approved these changes
LGTM.
nit: the cleanup could have been molded into a new commit ;-)

2021-07-29 11:03 UTC, Madhu-1 commented
> LGTM.
> nit: the cleanup could have been molded into a new commit ;-)

:facepalm: This is because the VSCode settings will bring it back

2021-07-29 11:11 UTC, pkalever approved these changes
Thanks @Madhu-1, LGTM now.

2021-07-29 12:54 UTC, nixpanic approved these changes
please open an issue with upstream commitlint so that it can be tracked and we can update the version at a later time.

I think conventional-changelog/commitlint#2578 or similar introduced this issue. Maybe the automated `(cherry picked from commit ` message can be configured somehow.

2021-07-30 06:47 UTC, humblec approved these changes

2021-07-30 07:06 UTC, merged

2021-07-31 04:33 UTC, Madhu-1 commented
@mergifyio rebase

2021-07-31 04:34 UTC, Madhu-1 commented
@mergifyio refresh