ci: remove create & delete namespace commands from helm jobs
ceph/ceph-csi pull request #2378
Opened 2021-08-09 06:35 UTC by Rakshith-R

Since this will be done internally by intall_helm.sh script
with kubectl_retry.

Fixes: #2309
Depends-on: #2377

Signed-off-by: Rakshith R <rar@redhat.com>

2021-08-09 06:42 UTC, Yuggupta27 requested changes
afaik creating namespaces is required as we provide a custom namespace where we want to install cephcsi in. It is a configurable option that allows us to deploy ceph-csi in any namespace. Any specific reason for removing namespace creation?

2021-08-09 06:44 UTC, Rakshith-R commented
> afaik creating namespaces is required as we provide a custom namespace where we want to install cephcsi in. It is a configurable option that allows us to deploy ceph-csi in any namespace. Any specific reason for removing namespace creation?

PTAL at the linked issue & pr.

2021-08-09 06:56 UTC, Yuggupta27 commented
Sure, please update the PR description to `Skip namespace creation in the job since this will be done internally by intall_helm.sh script with kubectl_retry.` so that it provides a clear idea for the change suggested.

2021-08-09 07:59 UTC, nixpanic commented
Looks ok, but you need to make sure #2377 gets backported to all active branches

2021-08-10 15:03 UTC, Rakshith-R commented
This needs to go in before #2377 because of kubectl delete namespace in ci job step comes after the install_helm script cleanup.

#2377 needs to be immediately merged in all active branches after getting this change in, otherwise helm e2e will be in fail state.

2021-08-12 04:14 UTC, Madhu-1 commented
@Rakshith-R can we merge this one? all dependent PR's are merged?

2021-08-12 04:15 UTC, Rakshith-R commented
> @Rakshith-R can we merge this one? all dependent PR's are merged?

Yes, was just about to comment it. 

Needed prs' merged in devel, release v3.3 & release v3.4, so we're all good to merge this one.

2021-08-12 04:16 UTC, Madhu-1 approved these changes

2021-08-12 04:17 UTC, merged