correct interface name and typos in source code
ceph/ceph-csi pull request #2417
Opened 2021-08-17 14:56 UTC by humblec

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

2021-08-18 05:30 UTC, Madhu-1 submitted a review, later dismissed
@humblec I  see `controller.ContollerManager` doesnot seems good so you are changing it to `controller.Manager`

but please update the PR description and commit message with details like 
* what  is the Need for this one
* Is it caught with some CI tool
* If this is violating some standards, please update the development guide also

The above helps us to avoid doing mistakes again

2021-08-18 06:10 UTC, humblec commented
> @humblec I see `controller.ContollerManager` doesnot seems good so you are changing it to `controller.Manager`
> 
> but please update the PR description and commit message with details like
> 
>     * what  is the Need for this one
> 
>     * Is it caught with some CI tool

@Madhu-1 sure, there is actually a small story here, `ContollerManager` had a typo in it, and if we correct it linter ( CI was failing) will fail and suggest not to use `controller.ControllerManager` as it is redundant , so got rid of it with `manager` as the inferface name.  Updated the PR description with these details. 
 
> 
>     * If this is violating some standards, please update the development guide also
> 
> 
> The above helps us to avoid doing mistakes again

2021-08-18 09:39 UTC, nixpanic requested changes, later dismissed
Please describe in the commit message why this is needed. The PR description explains it well, but having that in the git history is important too.

2021-08-18 11:13 UTC, humblec commented
@nixpanic @Madhu-1 commit message also updated, ptal..

2021-08-18 11:14 UTC, Madhu-1 approved these changes

2021-08-18 12:42 UTC, nixpanic approved these changes

2021-08-18 15:14 UTC, humblec commented
/retest ci/centos/mini-e2e-helm/k8s-1.21

2021-08-19 02:19 UTC, humblec commented
/retest all

2021-08-19 02:20 UTC, humblec commented
@Merjifyio rebase

2021-08-19 02:20 UTC, humblec commented
@Mergifyio rebase

2021-08-19 04:19 UTC, merged