ci: tag ceph image with quay.io
ceph/ceph-csi pull request #2420
Opened 2021-08-18 11:54 UTC by Madhu-1

added if-else check to check the image starting with quay.io. If yes, pull and tag the image with quay.io

currently, https://github.com/ceph/ceph-csi/pull/2419 is failing with the below error message 

```
+ ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@n26.dusty.ci.centos.org 'podman pull --authfile=~/.podman-auth.json registry-ceph-csi.apps.ocp.ci.centos.org/quay.io/ceph/ceph:v16 && podman tag registry-ceph-csi.apps.ocp.ci.centos.org/quay.io/ceph/ceph:v16 quay.io/ceph/ceph:v16 docker.io/quay.io/ceph/ceph:v16'

Warning: Permanently added 'n26.dusty.ci.centos.org,172.19.2.90' (ECDSA) to the list of known hosts.

Trying to pull registry-ceph-csi.apps.ocp.ci.centos.org/quay.io/ceph/ceph:v16...

Error: Error initializing source docker://registry-ceph-csi.apps.ocp.ci.centos.org/quay.io/ceph/ceph:v16: Error reading manifest v16 in registry-ceph-csi.apps.ocp.ci.centos.org/quay.io/ceph/ceph: manifest unknown: manifest unknown

script returned exit code 125
```

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

Note:- just changed in one place. If the changes looks okay i will make changes in other places also

2021-08-18 12:39 UTC, nixpanic requested changes
Might be easier to use short names (without `quay.io` or `docker.io`) in `build.env` and other placed?

Update https://github.com/ceph/ceph-csi/blob/ci/centos/mirror/images.txt to push the updated images to the local CI cache.

2021-08-18 12:39 UTC, nixpanic commented on containerized-tests.groovy
> +					if (base_image.startsWith(quay)){
indention is off...

This most likely needs to be changed in other groovy files too.

2021-08-19 12:43 UTC, nixpanic commented
Things might be easier, and only a change to the `images.txt` could work.

https://github.com/ceph/ceph-csi/pull/2419#issuecomment-901881830 pushed the ceph image to a new location in the CI registry, maybe that works too?

2021-08-20 07:21 UTC, Rakshith-R requested changes
executed and verified at 
https://www.tutorialspoint.com/execute_groovy_online.php
![image](https://user-images.githubusercontent.com/31369230/130195790-d451d902-2ad3-4f42-9e8d-64c385f5f34d.png)

2021-08-20 07:21 UTC, Rakshith-R commented on containerized-tests.groovy
>  					def d_io_regex = ~"^docker.io/"
```suggestion
					def io_regex = ~"(^docker.io/)|(^quay.io/)"
```

2021-08-20 07:21 UTC, Rakshith-R commented on containerized-tests.groovy
> +
```suggestion
					podman_pull(ci_registry, docker , "${base_image}" io_regex)
					}

```

2021-08-24 07:22 UTC, Madhu-1 commented
Will revist this one tomorrow. Need to discuss few things in today's standup

2021-10-08 21:05 UTC, closed without merging