rbd: migration secret support
ceph/ceph-csi pull request #2562
Opened 2021-10-11 17:07 UTC by humblec

rbd: parse migration secret and set it for CSI driver operations
    
    The intree secret has a data field called "key" which is the base64
    admin secret key. The ceph CSI driver currently expect the secret to
    contain data field "UserKey" for the equivalant. The CSI driver also
    expect the "UserID" field which is not available in the in-tree secret
    by deafult. This missing userID will be filled (if the username differ
    than 'admin') in the migration secret as 'adminId' field in the
    migration request, this commit adds the logic to parse this migration
    secret as below:
    
    "key" field value will be picked up from the migraion secret to "UserKey"
    field.
    "adminId" field value will be picked up from the migration secret to "UserID"
    field
    
    if `adminId` field is nil or not set, `UserID` field will be filled with
    default value ie `admin`.The above logic get activated only when the secret
    is a migration secret, otherwise skipped to the normal workflow as we have
    today.

Note:
E2E tests are added to make sure migration kind of secret is passed in tests.

Additional note:
The initial plan was to ask the admin to adjust the secret as a pre-upgrade step
for migration which avoid this change in the CSI driver, however taking out admin burden
is the main ask from kubernetes community so this change is introduced. None of the
existing workflow is broken for CSI driver with this change.

Updates #2509 

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

2021-10-12 05:24 UTC, Madhu-1 commented
@humblec this was not part of the original plan as per https://github.com/ceph/ceph-csi/issues/2509#issue-996778874 why we are adding this one? Do we have a clear design doc/plan about the changes required in cephcsi? IMHO we are adding more complexity to cephcsi to support migration.

2021-10-12 05:34 UTC, humblec commented
> @humblec this was not part of the original plan as per [#2509 (comment)](https://github.com/ceph/ceph-csi/issues/2509#issue-996778874) why we are adding this one? Do we have a clear design doc/plan about the changes required in cephcsi? IMHO we are adding more complexity to cephcsi to support migration.

@Madhu-1 I will add details about this  change in the PR description and commit ..etc, thats why I kept this in draft atm . I have already added this change in the tracker and can add some more details there as well which explain how this  helps. This looks to be pretty much the last change (unless some minor change comes up while doing complete e2e testing which cover kube.etc).  To give some context the initial plan was to ask this change as part of the pre upgrade step,  but  found a way to help admin to stay away from this change mostly and we can take care of it from csi driver code itself without breaking any existing functionality. Reg# documentation, it is there in the todo as well. Thanks :+1:

2021-10-13 12:58 UTC, humblec commented
/retest ci/centos/mini-e2e-helm/k8s-1.20

2021-10-13 12:59 UTC, humblec commented
/retest ci/centos/mini-e2e-helm/k8s-1.22

2021-10-19 05:03 UTC, Madhu-1 submitted a review, later dismissed
@humblec as its a migration work, why not ask the admin to recreate the secret and use it or take another route as we did for clusterID generation? IMO these changes make the cephcsi logic ugly to handle the migration.

2021-10-19 05:03 UTC, Madhu-1 commented on e2e/ceph_user.go
> +	keyringRBDMigrationNodePluginUsername  = "cephcsi-rbd-mig-node"
do we need to create a new ceph user for this one? why not use existing users?

2021-10-19 05:03 UTC, Madhu-1 commented on e2e/migration.go
> +	}
what action we are taking if the username is admin?  i don't see its getting added to the secret template

2021-10-19 05:03 UTC, Madhu-1 commented on e2e/migration.go
> +	}
IMO this validation is not required here.

2021-10-19 05:03 UTC, Madhu-1 commented on e2e/migration.go
> +	}
move this outside of this function as  this  function is a helper to create  the Secret and SC

2021-10-19 05:03 UTC, Madhu-1 commented on e2e/migration.go
> +		return fmt.Errorf("failed to create storageclass with error %w", err)
`failed to create storageclass with error %w` to `failed to create storageclass: %w`  we stopped adding `with  error` to the logs/error message

2021-10-19 05:03 UTC, Madhu-1 commented on e2e/migration.go
> +}
IMO this block is not needed if we reuse the existing user and just create the secret and use it.

2021-10-19 05:03 UTC, Madhu-1 commented on internal/rbd/controllerserver.go
> +		req.Secrets = passedSecretMap
IMHO this is becoming more ugly. we should not manipulate the input request and again assign the manipulated input to the request.

2021-10-19 05:03 UTC, Madhu-1 commented on internal/rbd/controllerserver.go
>  		}
why this change is required?

2021-10-19 05:03 UTC, Madhu-1 commented on internal/rbd/migration.go
> +// of a migration volume request.
the comment doesn't actually explains what exactly we are doing it.

2021-10-19 05:22 UTC, humblec commented
> @humblec as its a migration work, why not ask the admin to recreate the secret and use it or take another route as we did for clusterID generation? IMO these changes make the cephcsi logic ugly to handle the migration.

@Madhu-1 as mentioned in the other PR comment #2562 (comment), this was the initial thought ie let admin patch the secret. Then after some discussions with community folks , it was recommended that, take care of it maximum from the CSI side . So this PR, the advantage with this PR is that, admin Dont want to patch the secret at all, if the admin user is not different from admin which is mostly the case.

2021-10-19 05:23 UTC, humblec commented on internal/rbd/controllerserver.go
>  		}
It is just an adjustment or not really part of this the change this PR did, but good to have.  @Madhu-1 do I need to put it as a seperate PR or commit ?

2021-10-19 05:25 UTC, humblec commented on internal/rbd/controllerserver.go
> +		req.Secrets = passedSecretMap
I dont think so.  Again, we are just adjusting it in while we are in migration context, otherwise none of the code paths are touched. This is pretty shim change compared to the things we do here for other code paths, for ex:  chaning the entire nodestage request itself and intercpting the call and re issuing ...etc whlie we are in healer context .

2021-10-19 05:26 UTC, humblec commented on internal/rbd/migration.go
> +// of a migration volume request.
sure .. will address it next refresh

2021-10-19 05:28 UTC, humblec commented on e2e/ceph_user.go
> +	keyringRBDMigrationNodePluginUsername  = "cephcsi-rbd-mig-node"
we can , however this is the same pattern it has followed for radosnamespace test. so imo, its good to have a seperate user for this migration test alone.  wdyt?

2021-10-19 05:30 UTC, humblec commented on e2e/migration.go
> +	}
if its admin, no changes required, we just need to get the Key which is already part of the secret. Thats why this PR and to make the migration effort even smoother.

2021-10-19 05:41 UTC, humblec commented on e2e/ceph_user.go
> +	keyringRBDMigrationNodePluginUsername  = "cephcsi-rbd-mig-node"
as discussed, will try to stick to the existing users for now .. addressing it.

2021-10-19 06:41 UTC, humblec commented on e2e/migration.go
> +	}
Done

2021-10-19 06:41 UTC, humblec commented on e2e/migration.go
> +		return fmt.Errorf("failed to create storageclass with error %w", err)
Done.

2021-10-19 06:42 UTC, humblec commented on e2e/migration.go
> +}
as discussed the user key fetch is still required, so keeping it there for now.

2021-10-19 06:43 UTC, humblec commented on e2e/ceph_user.go
> +	keyringRBDMigrationNodePluginUsername  = "cephcsi-rbd-mig-node"
Done. thanks.

2021-10-19 06:47 UTC, humblec commented on internal/rbd/migration.go
> +// of a migration volume request.
Done.

2021-10-19 06:56 UTC, humblec commented on internal/rbd/controllerserver.go
>  		}
as discussed, added this logic to its own commit.. thanks.

2021-10-19 07:08 UTC, humblec commented
@Madhu-1 all the comments are addressed as per the discussion, ptal.. Thanks :+1:

2021-10-19 09:26 UTC, humblec commented
/retest ci/centos/mini-e2e-helm/k8s-1.21

2021-10-21 16:08 UTC, nixpanic submitted a review, later dismissed

2021-10-21 16:08 UTC, nixpanic commented on internal/rbd/controllerserver.go
> +		req.Secrets = passedSecretMap
Changing the `*csi.DeleteVolumeRequest` that has been passed by the caller does not seem right. Better so something like

```go
secrets := req.GetSecrets()
if isMigrationSecret(secrets) {
    secrets, err = parseAndSetSecretMapFromMigSecret(secrets)
    ...
}

cr, err := util.NewUserCredentials(secrets)
```

2021-10-21 16:08 UTC, nixpanic commented on internal/rbd/migration.go
> +	if len(passedSecretMap) != 0 {
if you really want to check for this error, return something on failure and have the happy-path of the function continue under the failure detection. This way you reduce indention, can add more failure detections easily and improve readability.

2021-10-21 16:08 UTC, nixpanic commented on internal/rbd/migration.go
> +func parseAndSetSecretMapFromMigSecret(passedSecretMap map[string]string) (map[string]string, error) {
New functions should have a comment. Specially a function that does some parsing/conversion. The input and output needs to be documented.

2021-10-21 16:08 UTC, nixpanic commented on internal/rbd/rbd_util.go
> +	migUserKey = "key"
this is also used as "key" in the map, can you use something that is more descriptive? it would surely help when printing the map in logs or such.

2021-10-21 16:08 UTC, nixpanic commented on internal/util/credentials.go
> +	CredUserID           = "userID"
this surely should be internal. If there really is a need for other functions to use this, move the function to this file.

2021-10-21 16:08 UTC, nixpanic commented on internal/rbd/controllerserver.go
>  	rbdVol, err := genVolFromVolID(ctx, volumeID, cr, req.GetSecrets())
unneeded change, just keep the empty line

2021-10-21 16:08 UTC, nixpanic commented on internal/rbd/nodeserver.go
> +		req.Secrets = newSecretMap
don't do this, anywhere

2021-10-25 04:21 UTC, humblec commented
/retest ci/centos/mini-e2e/k8s-1.21

2021-10-25 05:05 UTC, humblec commented on internal/rbd/nodeserver.go
> +		req.Secrets = newSecretMap
addressed

2021-10-25 05:05 UTC, humblec commented on internal/rbd/controllerserver.go
>  	rbdVol, err := genVolFromVolID(ctx, volumeID, cr, req.GetSecrets())
done.

2021-10-25 05:05 UTC, humblec commented on internal/util/credentials.go
> +	CredUserID           = "userID"
done.thanks

2021-10-25 05:05 UTC, humblec commented on internal/rbd/rbd_util.go
> +	migUserKey = "key"
unfortunately this is the field in the in the intree secret. so have to stay with it.

2021-10-25 05:06 UTC, humblec commented on internal/rbd/migration.go
> +func parseAndSetSecretMapFromMigSecret(passedSecretMap map[string]string) (map[string]string, error) {
done.

2021-10-25 05:06 UTC, humblec commented on internal/rbd/controllerserver.go
> +		req.Secrets = passedSecretMap
Done.thanks.

2021-10-25 05:07 UTC, humblec commented on internal/rbd/migration.go
> +	if len(passedSecretMap) != 0 {
Done.

2021-10-25 07:28 UTC, nixpanic submitted a review, later dismissed
Not much of functional comments, I guess. These are mostly related to maintainability and readability of the code.

2021-10-25 07:28 UTC, nixpanic commented on internal/util/credentials.go
> +func ParseAndSetSecretMapFromMigSecret(secretmap map[string]string) (map[string]string, error) {
Is there a reason why there is no unit-test for this function?

2021-10-25 07:28 UTC, nixpanic commented on internal/rbd/migration.go
> +func isMigrationSecret(passedSecretMap map[string]string) bool {
Did I  not suggest to move this function to the `utils` package where the Credentials struct lives?

2021-10-25 07:28 UTC, nixpanic commented on internal/util/credentials.go
> +	}
Use the validation of `isMigrationSecret()`?

2021-10-25 07:28 UTC, nixpanic commented on internal/rbd/migration.go
> +		return fmt.Errorf("migration volume details are %v", parsedMigHandle)
these two lines are rather inconsistent... one explicitly reports `nil`, the other uses the variable (which is `nil`). Might be cleaner to create an error instance, log it and then return it.

2021-10-25 07:28 UTC, nixpanic commented on internal/rbd/nodeserver.go
> +	cr *util.Credentials, secrets map[string]string) (*rbdVolume, error) {
I think the coding guidelines suggest to place this on a new line

2021-10-25 07:28 UTC, nixpanic commented on internal/rbd/nodeserver.go
> +	cr *util.Credentials, secrets map[string]string) (*rbdVolume, error) {
Is there really a need to pass `Credentials` and `secrets`? They would usually contain the same details, I think... If it is required, explain the reason in the comment above the function.

2021-10-25 07:28 UTC, nixpanic commented on internal/rbd/nodeserver.go
> +		secrets, err = util.ParseAndSetSecretMapFromMigSecret(secrets)
`ParseAndSetSecretMapFromMigSecret()` could use `isMigrationSecret()` and this code gets a little nicer too.

2021-10-25 07:28 UTC, nixpanic commented on internal/rbd/nodeserver.go
> +	staticVol bool, cr *util.Credentials) (stageTransaction, error) {
on a new line? maybe directly after `req` so that similar parameters are grouped together

2021-10-25 07:28 UTC, nixpanic commented on e2e/migration.go
> +	sc, err := getSecret(scPath)
`sc` usually refers to StorageClass, maybe use `sec` or `secret` instead?

2021-10-25 07:28 UTC, nixpanic commented on e2e/migration.go
> +func createRBDMigrationSecret(f *framework.Framework, secretName, userName, userKey string) error {
can you not use `createRBDSecret()` here?

2021-10-25 07:28 UTC, nixpanic commented on e2e/migration.go
> +// with it based on the arg values of 'provSecret' and 'nodeSecret'.
After reading more of the test case, I now understand that `provSecret` refers to `provisioner`, not `provided`. Better spell out the whole name, or at least make it clear in the comment.

2021-10-25 07:28 UTC, nixpanic commented on e2e/migration.go
> +			return fmt.Errorf("failed to create user %s with error %w", keyringRBDProvisionerUsername, err)
try not to introduce new error reporting that contains `with error`, that is unneeded long and as it is an error, rather unneeded. Use `"failed to create user %q: %w"` instead.

2021-10-25 07:28 UTC, nixpanic commented on e2e/migration.go
> +			return fmt.Errorf("failed to create provisioner secret with error %w", err)
same here, and more below.

2021-10-25 09:20 UTC, humblec commented on internal/util/credentials.go
> +func ParseAndSetSecretMapFromMigSecret(secretmap map[string]string) (map[string]string, error) {
no specific reason, but added that too.

2021-10-25 09:20 UTC, humblec commented on internal/rbd/migration.go
> +func isMigrationSecret(passedSecretMap map[string]string) bool {
actually not, but I moved in this refresh :)

2021-10-25 09:20 UTC, humblec commented on internal/util/credentials.go
> +	}
done.

2021-10-25 09:21 UTC, humblec commented on internal/rbd/migration.go
> +		return fmt.Errorf("migration volume details are %v", parsedMigHandle)
Done.

2021-10-25 09:21 UTC, humblec commented on internal/rbd/nodeserver.go
> +	cr *util.Credentials, secrets map[string]string) (*rbdVolume, error) {
contents are different, I have added the comment above the function too.

2021-10-25 09:21 UTC, humblec commented on e2e/migration.go
> +	sc, err := getSecret(scPath)
done.

2021-10-25 09:21 UTC, humblec commented on e2e/migration.go
> +			return fmt.Errorf("failed to create user %s with error %w", keyringRBDProvisionerUsername, err)
Done.

2021-10-25 09:22 UTC, humblec commented on e2e/migration.go
> +// with it based on the arg values of 'provSecret' and 'nodeSecret'.
Done. renamed to provisionersecret..

2021-10-25 09:22 UTC, humblec commented on e2e/migration.go
> +			return fmt.Errorf("failed to create provisioner secret with error %w", err)
Done.

2021-10-25 09:22 UTC, humblec commented on internal/rbd/nodeserver.go
> +		secrets, err = util.ParseAndSetSecretMapFromMigSecret(secrets)
done,

2021-10-25 09:23 UTC, humblec commented on internal/rbd/nodeserver.go
> +	staticVol bool, cr *util.Credentials) (stageTransaction, error) {
Done.

2021-10-25 09:25 UTC, humblec commented on e2e/migration.go
> +func createRBDMigrationSecret(f *framework.Framework, secretName, userName, userKey string) error {
with the changes by introducing flags in args...etc , we can change, but considering there are many callers for createRBDSecret at this time, and also having a seperate function helps to make it clean, this is used atm.

2021-10-25 09:30 UTC, humblec commented
> Not much of functional comments, I guess. These are mostly related to maintainability and readability of the code.

Sure, addressed those comments too :+1:  ptal. thanks @nixpanic .

2021-10-25 09:58 UTC, nixpanic commented on internal/util/credentials_test.go
> +package util
add copyright notice and license header please

2021-10-25 09:58 UTC, nixpanic commented on internal/util/credentials.go
> +	}
I still wonder why this is not part of `IsMigrationSecret()`.

2021-10-25 09:58 UTC, nixpanic commented on internal/util/credentials.go
> +	migUserKey           = "key"
as asked before, does this really need to be `key`, can it not be something specific for migration? Using `key` as key is a little confusing, it will make logs or debugging less easy to understand.

2021-10-25 10:58 UTC, humblec commented on internal/util/credentials.go
> +	}
can be part of.. moved it .

2021-10-25 10:58 UTC, humblec commented on internal/util/credentials_test.go
> +package util
done.

2021-10-25 11:00 UTC, humblec commented on internal/util/credentials.go
> +	migUserKey           = "key"
unfortunately this has to be 'key', this is the field in existing intree secret which is untouched at time of migration , so we have to keep the same field.. thanks.

2021-10-25 11:20 UTC, humblec commented
/retest ci/centos/mini-e2e-helm/k8s-1.22

2021-10-26 06:32 UTC, nixpanic reviewed
Is there a design document for the tasks that are needed to be done, or is https://github.com/ceph/ceph-csi/projects/18 the only description that is available? It would be good to have a document that contains the steps the migration takes, with that we can validate that the code does what is required. This current PR looks close to complete, but I would like to know what the general plan is.

2021-10-26 06:32 UTC, nixpanic commented on internal/util/credentials.go
> +	migUserKey           = "key"
ok, thanks. This could have been added as a comment to make it clearer. The commit message has some details, but ideally some of that can be found in the sources too.

2021-10-26 06:32 UTC, nixpanic commented on e2e/migration.go
> +			return fmt.Errorf("failed to delete provisioner secret with error %w", err)
missed a couple of these `... with error: %v` strings

2021-10-26 08:17 UTC, humblec commented
>Is there a design document for the tasks that are needed to be done, or is https://github.com/ceph/ceph-csi/projects/18 the only description that is available?

The tracker issue ( https://github.com/ceph/ceph-csi/issues/2509) carry the changes identified based on the discussions so far. Unless something comes at e2e testing with kubernetes changes , thats pretty much done. 

> It would be good to have a document that contains the steps the migration takes, with that we can validate that the code does what is required. 

Indeed thats the plan, I have documentation in todo , also wrapping up the changes in kubernetes , so that e2e testing and examples ..etc can be captured to a doc.  and update here in this repo too.

2021-10-26 08:21 UTC, humblec commented on e2e/migration.go
> +			return fmt.Errorf("failed to delete provisioner secret with error %w", err)
adjusted these too.. ptal.. thanks.

2021-10-27 09:00 UTC, nixpanic submitted a review, later dismissed

2021-10-27 09:00 UTC, nixpanic commented on e2e/rbd.go
> +					e2elog.Failf("failed to delete migration users and Secrets associated with error %v", err)
*sigh* more `with error` reporting. If this PR needs an update, please clean them up too.

2021-10-27 09:03 UTC, humblec commented on e2e/rbd.go
> +					e2elog.Failf("failed to delete migration users and Secrets associated with error %v", err)
sure @nixpanic . Thanks!

2021-10-27 09:08 UTC, yati1998 submitted a review, later dismissed

2021-10-27 09:09 UTC, Madhu-1 submitted a review, later dismissed

2021-10-27 09:09 UTC, Madhu-1 commented on e2e/migration.go
> +	}
if the user name is admin the secret will contain only the key?

2021-10-27 09:14 UTC, humblec commented on e2e/migration.go
> +	}
yes @Madhu-1

2021-10-27 09:16 UTC, Madhu-1 commented
@humblec please don't dismiss the requested review as am reviewing the PR. this can make the PR to be merged

2021-10-27 09:32 UTC, Madhu-1 requested changes

2021-10-27 09:32 UTC, Madhu-1 commented on e2e/migration.go
> +func deleteProvNodeMigrationSecret(f *framework.Framework, provisionerSecret, nodeSecret bool) error {
do we need `provisionerSecret, nodeSecret` secret arguments here? i don't see apart from this testing no one is going to use this one

2021-10-27 09:32 UTC, Madhu-1 commented on e2e/rbd.go
> +				}
why create and delete and re-create the user in multiple tests? cant we create why in BeforeEach and Delete it in AfterEach?

2021-10-27 09:32 UTC, Madhu-1 commented on internal/rbd/migration.go
> +func DeleteMigratedVolume(ctx context.Context, parsedMigHandle *migrationVolID, cr *util.Credentials) error {
no need to expose this function its internal

2021-10-27 09:32 UTC, Madhu-1 commented on internal/rbd/controllerserver.go
> +		pErr = DeleteMigratedVolume(ctx, pmVolID, cr)
we are passing the pmVolID here but I don't see when parseMigrationVolID can return both error as nil and volID as nil?

2021-10-27 09:32 UTC, Madhu-1 commented on internal/util/credentials.go
> +		return nil, fmt.Errorf("passed secret map does not contain user key or it is nil")
use errors.New as formatting is not requested

2021-10-27 09:32 UTC, Madhu-1 commented on internal/util/credentials.go
> +	var err error
why we need this err variable in this function as we are not using it instead just returning at end

2021-10-27 10:20 UTC, humblec commented on internal/rbd/controllerserver.go
> +		pErr = DeleteMigratedVolume(ctx, pmVolID, cr)
sure, the nil check was additional measure, however removed.

2021-10-27 10:21 UTC, humblec commented on internal/util/credentials.go
> +	var err error
can be removed. done.

2021-10-27 10:21 UTC, humblec commented on internal/rbd/migration.go
> +func DeleteMigratedVolume(ctx context.Context, parsedMigHandle *migrationVolID, cr *util.Credentials) error {
sure.

2021-10-27 10:23 UTC, humblec commented on e2e/rbd.go
> +				}
as discussed,  will do as a follow up PR along with `with error` changes.

2021-10-27 10:23 UTC, Madhu-1 commented on e2e/rbd.go
> +				}
@humblec please add this to your TODO list

2021-10-27 10:24 UTC, humblec commented on internal/util/credentials.go
> +		return nil, fmt.Errorf("passed secret map does not contain user key or it is nil")
done.

2021-10-27 10:25 UTC, Madhu-1 approved these changes

2021-10-27 10:26 UTC, humblec commented on e2e/rbd.go
> +				}
sure.. added madhu..thansk

2021-10-27 10:50 UTC, humblec commented
/retest ci/centos/mini-e2e/k8s-1.21

2021-10-27 11:11 UTC, humblec commented
/retest ci/centos/mini-e2e/k8s-1.21

2021-10-27 11:20 UTC, humblec commented
/retest ci/centos/mini-e2e-helm/k8s-1.22

2021-10-27 11:57 UTC, yati1998 approved these changes

2021-10-27 13:36 UTC, humblec commented
@Mergifyio rebase

2021-10-27 16:03 UTC, humblec commented
/retest all

2021-10-27 18:35 UTC, merged

2021-10-27 18:36 UTC, humblec commented
@Madhu-1 removed DNM on your behalf :+1: