ci: disable rook deployed csi drivers to speed up e2e
ceph/ceph-csi pull request #2568
Opened 2021-10-14 06:32 UTC by Rakshith-R

Signed-off-by: Rakshith R <rar@redhat.com>

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

2021-10-14 06:36 UTC, humblec submitted a review, later dismissed

2021-10-14 06:45 UTC, yati1998 submitted a review, later dismissed

2021-10-14 06:49 UTC, nixpanic requested changes

2021-10-14 06:49 UTC, nixpanic commented on scripts/rook.sh
> +        sed -i "s|ROOK_CSI_ENABLE_CEPHFS: \"true\"|ROOK_CSI_ENABLE_CEPHFS: \"false\"|g" "${TEMP_DIR}/operator.yaml"
please drop the escaping of quotes to make it more readable, use `'` in the outer string:
```
sed -i 's|ROOK_CSI_ENABLE_CEPHFS: "true"|ROOK_CSI_ENABLE_CEPHFS: "false"|g' "${TEMP_DIR}/operator.yaml"
````

2021-10-14 07:30 UTC, nixpanic approved these changes

2021-10-14 08:31 UTC, Madhu-1 approved these changes

2021-10-14 09:12 UTC, yati1998 approved these changes

2021-10-14 09:15 UTC, Rakshith-R commented
/retest ci/centos/mini-e2e-helm/k8s-1.20

2021-10-14 09:15 UTC, Rakshith-R commented
> /retest ci/centos/mini-e2e-helm/k8s-1.20

failed due to timeout.
https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.20/detail/mini-e2e-helm_k8s-1.20/2796/pipeline

2021-10-14 10:42 UTC, nixpanic commented
added `[DNM]` label so that #2571 can get merged as early as possible

2021-10-15 09:11 UTC, nixpanic commented
@mergifyio refresh

2021-10-15 11:15 UTC, merged