ci: use only latest version of test status in retest action
ceph/ceph-csi pull request #2670
Opened 2021-11-23 04:42 UTC by Rakshith-R

Github's list statuses returns list of all status, possibly
containing dupicates and previously failed statuses.
Use "UpdatedAt" timestamp to only get the latest status
for each test.

Signed-off-by: Rakshith R <rar@redhat.com>

Ex logs https://github.com/ceph/ceph-csi/runs/4294922427?check_suite_focus=true

2021-11-23 05:28 UTC, humblec submitted a review, later dismissed

2021-11-23 07:53 UTC, nixpanic requested changes

2021-11-23 07:53 UTC, nixpanic commented on actions/retest/main.go
> +				// get latest version of each status.
please put this in in a helper function describing why it is needed (similar to the commit message)

2021-11-23 14:37 UTC, nixpanic approved these changes

2021-11-24 09:30 UTC, Rakshith-R commented
@mergifyio rebase

@humblec Can you please take another look here? 
(so we can enable `retest action` )

2021-11-24 12:36 UTC, Yuggupta27 approved these changes

2021-11-24 12:37 UTC, merged