rbd: remove retrieving volumeHandle from PV annotation
ceph/ceph-csi pull request #2711
Opened 2021-12-14 11:41 UTC by Madhu-1

we have added clusterID mapping to identify the volumes in case of a failover in Diaster recovery in #1946. with #2314 we are moving to a configuration in configmap for clusterID and poolID mapping. and with #2314 we have all the required information
to identify the image mappings.

This commit removes the workaround implementation done in #1946.

closes #2328 

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

2021-12-15 16:26 UTC, nixpanic requested changes
Just need to fix the typo `Diaster` in the commit message, :+1: for the rest.

2021-12-15 16:28 UTC, Madhu-1 commented
@nixpanic done PTAL

2021-12-16 19:52 UTC, nixpanic approved these changes

2021-12-17 03:37 UTC, humblec approved these changes

2021-12-17 03:38 UTC, merged