cephfs: resize cloned, restored volume if required
ceph/ceph-csi pull request #2753
Opened 2022-01-10 05:53 UTC by Madhu-1

Currently, as a workaround, we are calling the resize volume on the cloned, restore volumes to adjust the cloned, restored volumes. With this fix, we are calling the resize volume only if there is a size mismatch with requested and the volume from which the new volume needs to be created.

fixes https://github.com/ceph/ceph-csi/issues/1439
fixes https://github.com/ceph/ceph-csi/issues/1254
    
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

2022-01-10 12:35 UTC, Madhu-1 commented
This is not targeted for 3.5.0 it will be for 3.5.x as still some corner cases to be addressed. Marking it as Draft for the same reason

2022-01-10 14:22 UTC, Madhu-1 commented
/retest ci/centos/mini-e2e-helm/k8s-1.22

2022-01-10 14:22 UTC, Madhu-1 commented
/retest ci/centos/mini-e2e-helm/k8s-1.21

2022-01-11 03:25 UTC, yati1998 requested changes
Just a small nit, everything else looks good to me.

2022-01-11 03:25 UTC, yati1998 commented on internal/cephfs/core/volume.go
> +// ExpandVolume will expand the volume if the requested size if greater than
if the requested size if greater than  -> if the requested size "is" greater than

2022-01-11 06:06 UTC, yati1998 approved these changes

2022-01-12 07:14 UTC, nixpanic approved these changes

2022-01-12 08:25 UTC, Madhu-1 commented
@mergifyio rebase

2022-01-12 08:26 UTC, Madhu-1 commented
```
Jan 12 08:06:59.747: FAIL: backend images not matching kubernetes resource count,image count 22 kubernetes resource count 21
backend image Info:
 [csi-vol-7cfd1cf0-737e-11ec-b659-fecc23c87f09 csi-vol-89fb2ce3-737e-11ec-b659-fecc23c87f09 csi-vol-89fb2ce3-737e-11ec-b659-fecc23c87f09-temp csi-vol-8a194c60-737e-11ec-b659-fecc23c87f09-temp csi-vol-8a37ec1b-737e-11ec-b659-fecc23c87f09 csi-vol-8a37ec1b-737e-11ec-b659-fecc23c87f09-temp csi-vol-8a65a438-737e-11ec-b659-fecc23c87f09 csi-vol-8a65a438-737e-11ec-b659-fecc23c87f09-temp csi-vol-8a9c30ee-737e-11ec-b659-fecc23c87f09 csi-vol-8a9c30ee-737e-11ec-b659-fecc23c87f09-temp csi-vol-8ac6b911-737e-11ec-b659-fecc23c87f09 csi-vol-8ac6b911-737e-11ec-b659-fecc23c87f09-temp csi-vol-8ad8e70d-737e-11ec-b659-fecc23c87f09 csi-vol-8ad8e70d-737e-11ec-b659-fecc23c87f09-temp csi-vol-8ae79cdd-737e-11ec-b659-fecc23c87f09 csi-vol-8ae79cdd-737e-11ec-b659-fecc23c87f09-temp csi-vol-9092b6af-737e-11ec-b659-fecc23c87f09 csi-vol-9092b6af-737e-11ec-b659-fecc23c87f09-temp csi-vol-90be1b24-737e-11ec-b659-fecc23c87f09 csi-vol-90be1b24-737e-11ec-b659-fecc23c87f09-temp csi-vol-94899f34-737e-11ec-b659-fecc23c87f09 csi-vol-94899f34-737e-11ec-b659-fecc23c87f09-temp]
[AfterEach] RBD
```

hitting https://github.com/ceph/ceph-csi/issues/2327 again in bot tests

2022-01-12 08:26 UTC, Madhu-1 commented
/retest ci/centos/mini-e2e-helm/k8s-1.22

2022-01-12 08:26 UTC, Madhu-1 commented
/retest ci/centos/mini-e2e-helm/k8s-1.23

2022-01-12 10:44 UTC, merged