Update templates for v3.5.0 release
ceph/ceph-csi pull request #2771
Opened 2022-01-13 04:48 UTC by humblec

This PR update the required template changes for v3.5.0 release.

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

2022-01-13 04:49 UTC, humblec commented
closing this as it got opened against wrong branch

2022-01-13 05:03 UTC, humblec commented
/retest ci/centos/mini-e2e/k8s-1.22

2022-01-13 05:03 UTC, Madhu-1 requested changes, later dismissed
where is upgrade documentation for 3.5 release?

2022-01-13 05:03 UTC, Madhu-1 commented on deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
> +          # for stable functionality replace v3.5.0 with latest release version
why this change is required?

2022-01-13 05:03 UTC, Madhu-1 commented on deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
> +          # for stable functionality replace v3.5.0 with latest release version
same here

2022-01-13 05:03 UTC, humblec commented
/retest ci/centos/upgrade-tests-cephfs

2022-01-13 05:08 UTC, humblec commented
> where is upgrade documentation for 3.5 release?

it will be a follow up PR @Madhu-1

2022-01-13 05:13 UTC, Madhu-1 commented
> > where is upgrade documentation for 3.5 release?
> 
> it will be a follow up PR @Madhu-1

@humblec usually during all releases the document changes are part of the template changes or before that not after the release.

2022-01-13 05:25 UTC, humblec commented
> > > where is upgrade documentation for 3.5 release?
> > 
> > 
> > it will be a follow up PR @Madhu-1
> 
> @humblec usually during all releases the document changes are part of the template changes or before that not after the release.

@Madhu-1 the release is not rolled out, I was saying the document PR can be a follow up PR.

2022-01-13 05:27 UTC, Madhu-1 commented
> > > where is upgrade documentation for 3.5 release?
> > 
> > 
> > it will be a follow up PR @Madhu-1
> 
> @humblec usually during all releases the document changes are part of the template changes or before that not after the release.

sent doc PR to devel first and backport it to release-3.5 and do a release? if we backport it after merging this PR. The docker image will be pushed 2 times.

2022-01-13 05:56 UTC, humblec commented
> > > > where is upgrade documentation for 3.5 release?
> > > 
> > > 
> > > it will be a follow up PR @Madhu-1
> > 
> > 
> > @humblec usually during all releases the document changes are part of the template changes or before that not after the release.
> 
> sent doc PR to devel first and backport it to release-3.5 and do a release? if we backport it after merging this PR. The docker image will be pushed 2 times.

#upgrade#2773 should cover it.

2022-01-13 07:10 UTC, humblec commented
```    [91mJan 13 06:12:25.598: backend images not matching kubernetes resource count,image count 22 kubernetes resource count 21``` 

Jan 13 06:12:25.618: INFO: At 2022-01-13 06:10:01 +0000 GMT - event for rbd-32744: {kubelet minikube} FailedMount: MountVolume.MountDevice failed for volume "pvc-e7b62504-408e-43c1-ab69-b85da701ac8f" : rpc error: code = Internal desc = flatten in progress: flatten is in progress for image csi-vol-69831ce5-7437-11ec-b802-cee966cc1967

 https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.21/detail/mini-e2e-helm_k8s-1.21/2446/pipeline

2022-01-13 07:25 UTC, humblec commented
/retest ci/centos/mini-e2e-helm/k8s-1.21

2022-01-13 07:26 UTC, humblec commented
/retest ci/centos/mini-e2e-helm/k8s-1.22

2022-01-13 10:44 UTC, humblec commented
@Madhu-1 the doc, mergify PRs are merged. ptal .. Thanks!

2022-01-14 12:40 UTC, nixpanic approved these changes
looks reasonable to me

2022-01-14 13:38 UTC, yati1998 approved these changes

2022-01-14 16:26 UTC, merged