deploy: revert deploy template changes for release-3.5
ceph/ceph-csi pull request #2783
Opened 2022-01-17 04:19 UTC by humblec

This commit revert the template changes brought in for release-3.5
and making it refer to canary.

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

2022-01-17 04:28 UTC, Madhu-1 reviewed
We have not done an image tag change in helm charts?

2022-01-17 04:30 UTC, Madhu-1 commented
Looks like released helm charts are still pointing to canary version  https://github.com/ceph/ceph-csi/blob/43182b39fee7bb1a6bf408b0be3cc09faa572cd8/charts/ceph-csi-rbd/values.yaml#L111-L113

2022-01-17 04:30 UTC, humblec commented
> Looks like released helm charts are still pointing to canary version
> 
> https://github.com/ceph/ceph-csi/blob/43182b39fee7bb1a6bf408b0be3cc09faa572cd8/charts/ceph-csi-rbd/values.yaml#L111-L113

Looks like , that commit got dropped somehow, tagging it now.

2022-01-17 10:49 UTC, Madhu-1 reviewed
changes are done for 3.5.0 in helm charts https://github.com/ceph/ceph-csi/pull/2784 reverting is missing in this PR. make 3.5.1 release and then revert the changes?

2022-01-17 11:29 UTC, humblec commented
> changes are done for 3.5.0 in helm charts #2784 reverting is missing in this PR. make 3.5.1 release and then revert the changes?

yeah, have to release 3.5.1 and then revert or get this PR refereshed on top of 3.5.1

2022-01-17 12:37 UTC, humblec commented
@Madhu-1 as discussed, considering the chart is auto refreshed, this pr refreshed accordingly and good to go. ptal.

2022-01-18 05:51 UTC, Madhu-1 reviewed
helm chart changes are still missing?

2022-01-18 06:00 UTC, humblec commented
> helm chart changes are still missing?

@Madhu-1 forgot to push :) , should be there now.. thanks.. ptal.

2022-01-18 06:54 UTC, Madhu-1 requested changes
changes are not done in minikube.sh https://github.com/ceph/ceph-csi/blob/release-v3.5/scripts/minikube.sh#L286-L287

2022-01-18 07:47 UTC, humblec commented
> changes are not done in minikube.sh https://github.com/ceph/ceph-csi/blob/release-v3.5/scripts/minikube.sh#L286-L287

ptal.

2022-01-18 07:55 UTC, Madhu-1 approved these changes

2022-01-18 08:05 UTC, yati1998 approved these changes

2022-01-18 11:38 UTC, humblec commented
@Mergifyio rebase

2022-01-18 11:45 UTC, humblec commented
@Mergifyio refresh

2022-01-18 11:46 UTC, humblec commented
/retest ci/centos/mini-e2e-helm/k8s-1.21

2022-01-18 11:46 UTC, humblec commented
/retest ci/centos/mini-e2e/k8s-1.23

2022-01-18 11:46 UTC, humblec commented
/retest ci/centos/mini-e2e/k8s-1.22

2022-01-18 11:47 UTC, humblec commented
/retest ci/centos/mini-e2e/k8s-1.21

2022-01-18 11:47 UTC, humblec commented
/retest ci/centos/mini-e2e-helm/k8s-1.23

2022-01-18 11:47 UTC, humblec commented
ci/centos/mini-e2e-helm/k8s-1.22

2022-01-18 11:53 UTC, humblec commented
/retest ci/centos/mini-e2e-helm/k8s-1.22

2022-01-18 15:20 UTC, merged