[WIP] deploy: update csi-snapshotter sidecar to v5.0.0
ceph/ceph-csi pull request #2789
Opened 2022-01-17 13:05 UTC by humblec

This release of snapshotter has a breaking change as mentioned
in the release note:

Refer# https://github.com/kubernetes-csi/external-snapshotter/releases/tag/v5.0.0

RBAC rules are also updated with this commit.

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

2022-01-20 07:02 UTC, humblec commented
/retest ci/centos/mini-e2e/k8s-1.23

2022-01-24 10:36 UTC, nixpanic commented
snapshot component installation seems to fail?

```
error: the namespace from the provided object "kube-system" does not match the namespace "default". You must pass '--namespace=kube-system' to perform this operation.
```

2022-01-25 08:56 UTC, humblec commented
> 

Yeah, the deployment is not going through.. chceking this

2022-01-28 06:19 UTC, humblec commented
/retest ci/centos/k8s-e2e-external-storage/1.21

2022-01-28 06:19 UTC, humblec commented
/retest ci/centos/mini-e2e-helm/k8s-1.22

2022-01-28 07:26 UTC, nixpanic submitted a review, later dismissed

2022-01-28 07:27 UTC, nixpanic commented
Added to the 3.6 milestone, it is important for users to know about this change and update the RBAC rlues.

2022-01-28 07:30 UTC, Madhu-1 requested changes

2022-01-28 07:30 UTC, Madhu-1 commented on scripts/install-snapshot.sh
>      sed -i "s/canary/${SNAPSHOT_VERSION}/g" "${temp_snap_controller}"
namespace change is required for controller yaml also

2022-01-28 07:34 UTC, humblec commented on scripts/install-snapshot.sh
>      sed -i "s/canary/${SNAPSHOT_VERSION}/g" "${temp_snap_controller}"
@Madhu-1 added there as well.. ptal.

2022-01-28 07:41 UTC, Madhu-1 approved these changes

2022-01-28 07:58 UTC, humblec commented
/retest ci/centos/mini-e2e/k8s-1.21

2022-01-28 08:14 UTC, yati1998 approved these changes

2022-01-28 10:28 UTC, humblec commented
/retest ci/centos/mini-e2e/k8s-1.21

2022-01-28 10:29 UTC, humblec commented
/retest  ci/centos/mini-e2e-helm/k8s-1.22

2022-01-28 10:57 UTC, humblec commented
/retest ci/centos/mini-e2e-helm/k8s-1.22

2022-01-31 03:57 UTC, humblec commented
@Mergifyio refresh

2022-01-31 04:00 UTC, humblec commented
@Mergifyio rebase

2022-01-31 07:13 UTC, humblec commented
@Mergifyio refresh

2022-02-01 13:35 UTC, humblec commented
@Mergifyio refresh

2022-02-01 13:35 UTC, humblec commented
@Mergifyio rebase

2022-02-01 15:37 UTC, humblec commented
@Mergifyio refresh

2022-02-02 14:31 UTC, nixpanic commented
/retest all

2022-02-02 14:44 UTC, nixpanic commented
/retest ci/centos/k8s-e2e-external-storage/1.22

2022-02-03 05:16 UTC, humblec commented
@Mergifyio rebase

2022-02-03 05:17 UTC, humblec commented
@Mergifyio refresh

2022-02-03 15:04 UTC, nixpanic commented
@mergifyio rebase

2022-02-03 19:01 UTC, merged