rbd: add additionalauthdate while unwrapping the DEK
ceph/ceph-csi pull request #2865
Opened 2022-02-07 14:01 UTC by humblec

As we are using optional additional auth data while wrapping
the DEK, we have to send the same additionally while unwrapping.

Additional Info:
Tested manually and everything works as expected.

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

2022-02-07 14:59 UTC, nixpanic requested changes
`additionalauthdata` in the PR description and commit message is a very strange word, CamelCase it?

2022-02-07 14:59 UTC, nixpanic commented on internal/kms/keyprotect.go
> +	aadVolID := []string{volumeID}
nit: keep the empty line please

2022-02-07 15:00 UTC, nixpanic commented
It might be useful to have the error message in the commit description too?

2022-02-07 15:09 UTC, humblec commented on internal/kms/keyprotect.go
> +	aadVolID := []string{volumeID}
done.. thanks.

2022-02-07 15:27 UTC, nixpanic submitted a review, later dismissed

2022-02-07 15:51 UTC, humblec commented
@nixpanic while adding the empty line,  there was en extra space which I corrected now.. :) ,  however the refresh caused the approval to go away. appreciate if you can bring it back :), `contenarized-test` pass on the last refresh too.

2022-02-07 16:19 UTC, nixpanic approved these changes

2022-02-07 16:20 UTC, yati1998 approved these changes

2022-02-08 02:35 UTC, humblec commented
@Mergifyio refresh

2022-02-08 02:36 UTC, humblec commented
@Mergifyio rebase

2022-02-08 03:06 UTC, merged