helm-charts: Add selinuxMount flag to enable/disable /etc/selinux host mount
ceph/ceph-csi pull request #2883
Opened 2022-02-15 23:30 UTC by Aste88

# Describe what this PR does #

Add selinuxMount flag to enable/disable /etc/selinux host mount inside pods to support selinux-enabled filesystems

Is the change backward compatible?

Yes, selinuxMount default is true (the previous behaviour)

Are there concerns around backward compatibility?

None I'm aware of

## Related issues ##

Fixes: #2876

2022-02-16 06:39 UTC, Madhu-1 requested changes
@Aste88 Thanks for the PR. can you fix DCO and commit lint problem. please refer to https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#code-contribution-workflow for any help

2022-02-16 06:39 UTC, Madhu-1 commented on charts/ceph-csi-cephfs/README.md
> +| `selinuxMounnt`                                | Mount the host /etc/selinux inside pods to support selinux-enabled filesystems
`selinuxMounnt` to `selinuxMount`

2022-02-16 11:34 UTC, Madhu-1 approved these changes

2022-02-16 11:38 UTC, Rakshith-R approved these changes

2022-02-16 12:48 UTC, merged

2022-02-17 08:27 UTC, humblec commented
@Aste88 @Madhu-1 @Rakshith-R @nixpanic I doubt this was the right fix we need , That said, here we are defaulting to `true` and consuming it from the host. If the PODs are running in host which does not support, this could cause issues? or did I miss anything in helm deployment here?

2022-02-17 08:29 UTC, Madhu-1 commented
@humblec this was done to support the backward compatibility and now the user is having an option to turn it on and off which was not present at all.

2022-02-17 08:35 UTC, humblec commented
> @humblec this was done to support the backward compatibility and now the user is having an option to turn it on and off which was not present at all.

Getting a knob done is fine, but a couple of things , like 
1) Default to `true
2) HostPath 

All new deployments will try to pick the hostmount now being this value default to true and if we are on NON selinux system it could cause issues.

Instead of this, I was thinking we could have gone ahead with `DirectoryOrCreate` instead of HostPath.. I believe its the better solution . Please let me know what you folks think.. I can drop a PR accordingly.

2022-02-17 08:39 UTC, Madhu-1 commented
> > @humblec this was done to support the backward compatibility and now the user is having an option to turn it on and off which was not present at all.
> 
> Getting a knob done is fine, but a couple of things , like
> 
> 1. Default to `true
> 2. HostPath
> 
> All new deployments will try to pick the hostmount now being this value default to true and if we are on NON selinux system it could cause issues.
> 

Yes correctly its the existing behaviour for both helm and deployments with kube templates.

> Instead of this, I was thinking we could have gone ahead with `DirectoryOrCreate` instead of HostPath.. I believe its the better solution . Please let me know what you folks think. I can drop a PR accordingly.

 Is it allowed to create a Directory on `/etc` folder on the nodes? If possible looks good.