csi-common: remove unimplemented controller expand,snapshot RPCs
ceph/ceph-csi pull request #2928
Opened 2022-03-10 10:40 UTC by humblec

These RPCs ( controller expand, create and delete snapshots) are
no longer unimplmented and we dont have to declare these as with
`unimplemented` states. This commit remove the same.

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

2022-03-10 11:57 UTC, Madhu-1 requested changes
Any specific reason for removing this one? If yes please remove unimplemented in nodeserver-default.go also

2022-03-10 13:05 UTC, humblec commented
/retest ci/centos/mini-e2e-helm/k8s-1.21

2022-03-14 15:23 UTC, nixpanic commented
**go-test** ci job fails. Can you run this locally before posting the next revision of this PR?

2022-03-15 12:28 UTC, humblec commented
> Any specific reason for removing this one? If yes please remove unimplemented in nodeserver-default.go also

Sure, removed the implemented RPCs from the nodeserver too. ptal ..Thanks

2022-03-15 12:29 UTC, Madhu-1 approved these changes

2022-03-15 12:31 UTC, yati1998 approved these changes

2022-03-16 11:10 UTC, humblec commented
/retest ci/centos/mini-e2e/k8s-1.23

2022-03-16 11:10 UTC, humblec commented
/retest ci/centos/k8s-e2e-external-storage/1.23

2022-03-16 14:37 UTC, Rakshith-R commented
Was trying to push the other prs which passed all tests  in queue to the top. 
:sweat_smile:  seems like merigfyio single queue may not be that great.

2022-03-16 15:27 UTC, merged