[WIP for release 3.6 branch] Release 3.6.0 template changes
ceph/ceph-csi pull request #2985
Opened 2022-04-04 08:49 UTC by humblec

deploy: change image versions to v3.6.0 instead of canary
    
    This commit change the required image tag to release 3.6 instead
    of canary for v3.6 release

    helm: update image tag for release 3.6 instead of canary
    
    This commit change the image tag for release v3.6 instead of
    canary.
    
    Signed-off-by: Humble Chirammal <hchiramm@redhat.co

2022-04-04 10:02 UTC, Madhu-1 commented on deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
> +          # for stable functionality replace v3.6.0 with latest release version
this is not required as its a comment which is expected

2022-04-04 10:03 UTC, Madhu-1 requested changes
@humblec this should go for release-3.6 branch, not for devel branch

2022-04-04 10:03 UTC, Madhu-1 commented on deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
> +          # for stable functionality replace v3.6.0 with latest release version
this is not required as its a comment which is expected

2022-04-04 10:03 UTC, Madhu-1 commented on deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
> +          # for stable functionality replace v3.6.0 with latest release version
this is not required as its a comment which is expected

2022-04-04 10:10 UTC, humblec commented
> @humblec this should go for release-3.6 branch, not for devel branch

True.. thats why I added that in PR title for now as the release branch is not cut yet.. thanks for the review @Madhu-1 :+1:

2022-04-04 11:39 UTC, Madhu-1 reviewed
changes LGTM, will approve once the base branch is changed to release-3.6

2022-04-04 11:41 UTC, humblec commented
Thanks @Madhu-1 , a couple more PRs in , we will cut the release branch.

2022-04-05 09:00 UTC, Madhu-1 approved these changes

2022-04-05 09:00 UTC, humblec commented
Thanks @Madhu-1 :+1:

2022-04-05 09:44 UTC, yati1998 approved these changes

2022-04-05 11:29 UTC, humblec commented
/retest  ci/centos/mini-e2e-helm/k8s-1.21

2022-04-05 11:29 UTC, humblec commented
/retest ci/centos/mini-e2e-helm/k8s-1.23

2022-04-05 11:30 UTC, humblec commented
/retest ci/centos/upgrade-tests-cephfs

2022-04-05 11:30 UTC, humblec commented
/retest ci/centos/mini-e2e-helm/k8s-1.21

2022-04-05 14:25 UTC, merged