add allowPrivilegeEscalation: true to containerSecurityContext to nodeplugin daemonset
ceph/ceph-csi pull request #2993
Opened 2022-04-06 05:45 UTC by losil

# Describe what this PR does #

When running the kubernetes cluster with one single privileged PodSecurityPolicy which is allowing everything the nodeplugin daemonset can fail to start. To be precise the problem is the `defaultAllowPrivilegeEscalation: false` configuration in the PSP. Containers of the nodeplugin daemonset won't start when they have `privileged: true` but no `allowPrivilegeEscalation` in their container securityContext.

Kubernetes will not schedule if this mismatch exists `cannot set allowPrivilegeEscalation to false and privileged to true`:
```
[Warning  FailedCreate  7s (x3 over 14s)  daemonset-controller  (combined from similar events): Error creating: Pod "ceph-csi-nodeplugin-rbd-7qm9f" is invalid: [spec.containers[0].securityContext: Invalid value: core.SecurityContext{Capabilities:(*core.Capabilities)(nil), Privileged:(*bool)(0xc04f579a0c), SELinuxOptions:(*core.SELinuxOptions)(nil), WindowsOptions:(*core.WindowsSecurityContextOptions)(nil), RunAsUser:(*int64)(nil), RunAsGroup:(*int64)(nil), RunAsNonRoot:(*bool)(nil), ReadOnlyRootFilesystem:(*bool)(nil), AllowPrivilegeEscalation:(*bool)(0xc04d20ce50), ProcMount:(*core.ProcMountType)(nil), SeccompProfile:(*core.SeccompProfile)(nil)}: cannot set `allowPrivilegeEscalation` to false and `privileged` to true, spec.containers[2].securityContext: Invalid value: core.SecurityContext{Capabilities:(*core.Capabilities)(nil), Privileged:(*bool)(0xc04f579a0f), SELinuxOptions:(*core.SELinuxOptions)(nil), WindowsOptions:(*core.WindowsSecurityContextOptions)(nil), RunAsUser:(*int64)(nil), RunAsGroup:(*int64)(nil), RunAsNonRoot:(*bool)(nil), ReadOnlyRootFilesystem:(*bool)(nil), AllowPrivilegeEscalation:(*bool)(0xc04d20ce50), ProcMount:(*core.ProcMountType)(nil), SeccompProfile:(*core.SeccompProfile)(nil)}: cannot set `allowPrivilegeEscalation` to false and `privileged` to true]]()
``` 

The default PodSecurityPolicy for every workload in the k8s cluster is the following:
```yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
  name: system-unrestricted-psp
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  defaultAllowPrivilegeEscalation: false
  fsGroup:
    rule: RunAsAny
  hostIPC: true
  hostNetwork: true
  hostPID: true
  hostPorts:
  - max: 65535
    min: 0
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
```

The daemonsets run when the `allowPrivilegeEscalation` parameter is added to the container securityContext config. In detail this is needed for the containers:
* driver-registrar
* liveness-prometheus

Updating the helm chart templates for `ceph-csi-rbd` and `ceph-csi-cephfs`solve the problem when using `defaultAllowPrivilegeEscalation: true` in global privileged PodSecurityPolicy. For example:

```yaml
{{- if .Values.nodeplugin.httpMetrics.enabled }}
        - name: liveness-prometheus
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          image: "{{ .Values.nodeplugin.plugin.image.repository }}:{{ .Values.nodeplugin.plugin.image.tag }}"
``` 

## Is there anything that requires special attention ##

Do you have any questions? No

Is the change backward compatible? Yes

Are there concerns around backward compatibility? No

Provide any external context for the change, if any.

For example:

https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

## Related issues ##

Mention any github issues relevant to this PR. Adding below line
will help to auto close the issue once the PR is merged.

None

## Future concerns ##

List items that are not part of the PR and do not impact it's
functionality, but are work items that can be taken up subsequently.

None

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

2022-04-06 06:21 UTC, yati1998 commented
@losil please check the DCO failure. We have specific guidelines for the commit messages.

2022-04-06 08:27 UTC, humblec commented
@losil as you know  PSP  ( PodSecurityPolicy)  is getting deprecated in upstream.

2022-04-06 08:52 UTC, losil commented
> @losil as you know PSP ( PodSecurityPolicy) is getting deprecated in upstream. Regardless we could have this in chart 👍

@humblec of course I am aware of the PSPs deprecation and honestly look forward to getting rid of them.
But since we are still running our clusters with k8s `1.21.10` we still rely on the PSPs.

2022-04-06 10:33 UTC, humblec commented
Yeah , please correct the commit lint error @losil .. it should be good to go..

2022-04-06 14:02 UTC, Madhu-1 commented
@losil Please check https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#commit-messages standard followed for commit message.

it should be something like below

```
helm: allowPrivilegeEscalation: true in containerSecurityContext

When running the kubernetes cluster with one single privileged 
PodSecurityPolicy which is allowing everything the nodeplugin 
daemonset can fail to start. To be precise the problem is the 
defaultAllowPrivilegeEscalation: false configuration in the PSP.
 Containers of the nodeplugin daemonset won't start when they 
have privileged: true but no allowPrivilegeEscalation in their c
ontainer securityContext.

Kubernetes will not schedule if this mismatch exists cannot set 
allowPrivilegeEscalation to false and privileged to true:

Signed-off-by: Silvan Loser <silvan.loser@hotmail.ch>
```

2022-04-06 15:23 UTC, losil commented
> @losil Please check https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#commit-messages standard followed for commit message.
> 
> it should be something like below
> 
> ```
> helm: allowPrivilegeEscalation: true in containerSecurityContext
> 
> When running the kubernetes cluster with one single privileged 
> PodSecurityPolicy which is allowing everything the nodeplugin 
> daemonset can fail to start. To be precise the problem is the 
> defaultAllowPrivilegeEscalation: false configuration in the PSP.
>  Containers of the nodeplugin daemonset won't start when they 
> have privileged: true but no allowPrivilegeEscalation in their c
> ontainer securityContext.
> 
> Kubernetes will not schedule if this mismatch exists cannot set 
> allowPrivilegeEscalation to false and privileged to true:
> 
> Signed-off-by: Silvan Loser <silvan.loser@hotmail.ch>
> ```

Thanks for the hint!

2022-04-07 04:37 UTC, humblec commented
/retest ci/centos/k8s-e2e-external-storage/1.21

2022-04-07 04:37 UTC, humblec commented
/retest ci/centos/mini-e2e-helm/k8s-1.21

2022-04-07 04:37 UTC, humblec submitted a review, later dismissed

2022-04-07 04:46 UTC, yati1998 approved these changes, later dismissed

2022-04-07 10:46 UTC, humblec commented
@Mergifyio rebase

2022-04-11 06:41 UTC, humblec commented
@Mergifyio rebase

2022-04-11 06:41 UTC, humblec commented
@Mergifyio refresh

2022-04-11 14:56 UTC, Madhu-1 requested changes
@losil Sorry for the late review on this one.

Same changes are required in the below files

deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
deploy/rbd/kubernetes/csi-rbdplugin.yaml

2022-04-12 05:58 UTC, Madhu-1 submitted a review, later dismissed

2022-04-12 05:59 UTC, Madhu-1 commented
@losil can you please change `Signed-off-by: Silvan Loser <33911078+losil@users.noreply.github.com>` to `Signed-off-by: Silvan Loser <silvan.loser@hotmail.ch>` in your 2nd commit?

2022-04-19 08:47 UTC, humblec commented
@losil can you please revisit this PR mainly for correcting `DCO`?

2022-04-21 08:40 UTC, Madhu-1 commented
@mergifyio rebase

2022-04-21 09:34 UTC, humblec approved these changes

2022-04-21 12:13 UTC, Madhu-1 commented
@mergifyio rebase

2022-04-21 12:14 UTC, Madhu-1 reviewed
@losil changes LGTM, can you please rebase the PR, PR is having 3 commits, it should have only 2

2022-04-22 08:20 UTC, Madhu-1 commented
/retest ci/centos/mini-e2e/k8s-1.23

2022-04-22 08:31 UTC, humblec submitted a review, later dismissed

2022-04-22 09:10 UTC, Madhu-1 approved these changes

2022-04-22 09:11 UTC, Madhu-1 commented
>This branch cannot be rebased due to conflicts

This PR is having merge conflicts needs to be addressed with manual rebase

2022-04-22 09:11 UTC, Madhu-1 requested changes
https://github.com/ceph/ceph-csi/pull/2993#issuecomment-1106223019

2022-04-22 09:45 UTC, humblec commented
> > This branch cannot be rebased due to conflicts
> 
> This PR is having merge conflicts needs to be addressed with manual rebase

@Madhu-1 where do you see the conflict?

2022-04-22 09:46 UTC, Madhu-1 commented
> > > This branch cannot be rebased due to conflicts
> > 
> > 
> > This PR is having merge conflicts needs to be addressed with manual rebase
> 
> @Madhu-1 where do you see the conflict?

After PR approval it is showing conflict and cannot be merged.

2022-04-22 09:48 UTC, Madhu-1 commented
@mergifyio rebase

2022-04-22 09:48 UTC, Madhu-1 commented
@mergifyio rebase

2022-04-22 09:49 UTC, Madhu-1 commented
> > rebase
> 
> ####  Base branch update has failed

@humblec please see here.

2022-04-22 09:55 UTC, humblec commented
I am not able to find @losil in ceph csi slack too.. Lets go ahead without this PR then.. :+1:

2022-04-22 12:09 UTC, losil commented
Hey @Madhu-1 

Hope it's fine now.. Sorry for the delay... I'm on vacation.

Cheers

2022-04-22 12:12 UTC, Madhu-1 approved these changes

2022-04-22 12:13 UTC, Madhu-1 commented
@losil no worries, Thanks for updating the PR. Will add backport label once 3.6.1 is released.

2022-04-22 12:36 UTC, humblec approved these changes

2022-04-22 23:36 UTC, merged

2022-04-26 05:15 UTC, Madhu-1 commented
@mergifyio refresh