rbd: use leases for leader election
ceph/ceph-csi pull request #3011
Opened 2022-04-11 08:05 UTC by Madhu-1

use leases for leader election instead of the deprecated configmap based leader election.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

2022-04-11 08:08 UTC, humblec approved these changes, later dismissed

2022-04-11 08:41 UTC, yati1998 submitted a review, later dismissed

2022-04-11 08:41 UTC, nixpanic requested changes
Could you link to the deprecation notice?

This now imports a Kubernetes package, making the CSi-driver more dependent on that single CO. Not sure this is the preferred solution.

2022-04-11 09:02 UTC, Madhu-1 commented
> Could you link to the deprecation notice?
> 
This PR is making leases as default leader election https://github.com/kubernetes-sigs/controller-runtime/pull/1773, default from configmap to configmap leases was done with https://github.com/kubernetes-sigs/controller-runtime/pull/1144 https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.7.0

All the kubernetes sidecars are based on the leases based leader election, configmap is deprecated long back.

> This now imports a Kubernetes package, making the CSi-driver more dependent on that single CO. Not sure this is the preferred solution.

The whole controller is written using the controller runtime it's only meant for kubernetes and it exists for a long time. This PR is just changing the leader type.

2022-04-11 11:49 UTC, humblec approved these changes

2022-04-13 08:22 UTC, nixpanic approved these changes

2022-04-14 06:46 UTC, Madhu-1 commented
@mergifyio refresh

2022-04-14 06:46 UTC, merged