rbd: check nbd tool features only for rbd driver
ceph/ceph-csi pull request #3012
Opened 2022-04-11 08:12 UTC by Madhu-1

calling setRbdNbdToolFeatures inside an init gets called in main.go for both cephfs and rbd driver. instead of calling it in init function call this in rbd driver.go as this is specific to rbd.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

2022-04-11 08:43 UTC, nixpanic requested changes
This only needs to be done for the node-plugin, the controller/provisioner does not need to check for it

2022-04-11 08:46 UTC, Madhu-1 commented
> This only needs to be done for the node-plugin, the controller/provisioner does not need to check for it

is controller/provisioner checking this one? i am calling this function https://github.com/ceph/ceph-csi/blob/3ae65c6b22aa1c9c2d0e72cc11682e68a8e615f3/internal/rbd/driver/driver.go#L136-L158 if its a nodesever only. am i missing anything?

2022-04-11 10:19 UTC, nixpanic approved these changes

2022-04-11 10:20 UTC, Rakshith-R approved these changes

2022-04-11 10:22 UTC, pkalever approved these changes
Good catch Madhu :+1:

2022-04-11 14:16 UTC, Madhu-1 commented
Rook deployment failed in 3 out of 4 tests. adding retry label as this should not cause any functional regressions.

2022-04-11 21:18 UTC, merged

2022-04-14 06:48 UTC, Madhu-1 commented
@mergifyio refresh