e2e: Add Skip() in Context() for disabled tests
ceph/ceph-csi pull request #3043
Opened 2022-04-19 09:28 UTC by nixpanic

Some parts of the Context() seem to get executed, even when BeforeEach()
did a Skip() for the test. By adding a Skip() inside the Context(), the
tests should not get executed at all.

This was noticed in a failed test, where upgrade was running, eventhough
the job was executed as a nornal non-upgrade one.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

2022-04-19 09:28 UTC, nixpanic commented
Noticed in https://github.com/ceph/ceph-csi/pull/3036#issuecomment-1102367073

2022-04-19 10:27 UTC, Rakshith-R submitted a review, later dismissed

2022-04-19 10:30 UTC, yati1998 submitted a review, later dismissed

2022-04-20 06:35 UTC, nixpanic commented
/retest ci/centos/k8s-e2e-external-storage/1.23

2022-04-20 06:41 UTC, nixpanic commented
> /retest ci/centos/k8s-e2e-external-storage/1.23

Failed to deploy Rook:
```
Error from server: error when creating "/tmp/tmp.ReO6yPSmaf/operator.yaml": etcdserver: request timed out
```

2022-04-20 06:56 UTC, Rakshith-R approved these changes, later dismissed

2022-04-20 07:09 UTC, Madhu-1 approved these changes

2022-04-20 07:10 UTC, Madhu-1 requested changes
nit: @nixpanic commit title needs to be adjusted.

2022-04-20 09:17 UTC, Madhu-1 approved these changes

2022-04-20 09:32 UTC, Rakshith-R approved these changes

2022-04-20 11:18 UTC, nixpanic commented
/retest ci/centos/mini-e2e-helm/k8s-1.21

2022-04-20 11:19 UTC, nixpanic commented
> /retest ci/centos/mini-e2e-helm/k8s-1.21

Failed with
```
Apr 20 11:00:15.519: FAIL: backend images not matching kubernetes resource count,image count 23 kubernetes resource count 21
```

2022-04-20 12:32 UTC, humblec approved these changes

2022-04-20 17:34 UTC, merged