chore: Included githubactions in the dependabot config
ceph/ceph-csi pull request #3077
Opened 2022-05-03 14:21 UTC by naveensrinivasan

This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.

Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot

GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

2022-05-03 14:24 UTC, naveensrinivasan commented
@nixpanic 👀

2022-05-03 18:11 UTC, nixpanic submitted a review, later dismissed
great, thanks again!

2022-05-04 05:17 UTC, Madhu-1 commented
@naveensrinivasan Thanks for the contribution, can you please fix CI failures?

2022-05-04 06:00 UTC, humblec commented
@naveensrinivasan ```
https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
✖   body's lines must not be longer than 80 characters [body-max-line-length]```

2022-05-04 06:47 UTC, nixpanic commented
CI failures are addressed with https://github.com/nixpanic/ceph-csi/commit/49b84bbe0d0d01d186e58bef0800d65b80926bf8

@naveensrinivasan, let me know if you want me to take this forward. Thanks!

2022-05-04 13:03 UTC, naveensrinivasan commented
> CI failures are addressed with [nixpanic@49b84bb](https://github.com/nixpanic/ceph-csi/commit/49b84bbe0d0d01d186e58bef0800d65b80926bf8)
> 
> @naveensrinivasan, let me know if you want me to take this forward. Thanks!

I have pushed the changes for commit message length.

2022-05-04 13:10 UTC, nixpanic commented on .github/dependabot.yml
> +     - "rebase"
this probably needs an extra indention?

2022-05-04 13:10 UTC, nixpanic approved these changes

2022-05-04 13:16 UTC, yati1998 requested changes
Please check the commitlint and extralint errors.

2022-05-04 13:20 UTC, naveensrinivasan commented
> CI failures are addressed with [nixpanic@49b84bb](https://github.com/nixpanic/ceph-csi/commit/49b84bbe0d0d01d186e58bef0800d65b80926bf8)
> 
> @naveensrinivasan, let me know if you want me to take this forward. Thanks!

@nixpanic  I would appreciate if you can please take care of this.

2022-05-04 13:47 UTC, nixpanic commented
> @nixpanic I would appreciate if you can please take care of this.

Sure! #3084 is a replacement for this.

2022-05-04 13:47 UTC, closed without merging