rebase: bump nfsplugin to v4.0.0
ceph/ceph-csi pull request #3101
Opened 2022-05-08 13:46 UTC by nixpanic

Several bugs have been fixed and new features have been added.

See-also: https://github.com/kubernetes-csi/csi-driver-nfs/releases/tag/v4.0.0

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

2022-05-08 13:47 UTC, nixpanic commented
Both @humblec and me got our 1st contribution to the csi-driver-nfs with the v4.0.0 release included :partying_face:

2022-05-08 13:48 UTC, nixpanic commented
No e2e tests for NFS yet, so added the `ci/e2e/skip` label (hopefully not too late)

2022-05-09 02:55 UTC, Yuggupta27 approved these changes

2022-05-09 03:07 UTC, yati1998 requested changes
@nixpanic please check the commitlint

2022-05-09 03:09 UTC, yati1998 commented
> @nixpanic please check the commitlint

oh I see another PR for this error, I will approve it once that PR is merged.

2022-05-09 03:10 UTC, Madhu-1 approved these changes

2022-05-09 03:11 UTC, Madhu-1 commented
@mergifyio rebase

2022-05-09 03:33 UTC, humblec approved these changes

2022-05-09 05:01 UTC, yati1998 approved these changes

2022-05-09 05:59 UTC, nixpanic commented
@mergifyio rebase

2022-05-09 06:34 UTC, merged