ci: fix commitlint problem
ceph/ceph-csi pull request #3102
Opened 2022-05-09 04:43 UTC by Madhu-1

Still seeing the issue of the commitlint as below

fatal: unsafe repository ('/go/src/github.com/ceph/ceph-csi' is owned by someone else) To add an exception for this directory,
call:

git config --global --add safe.directory /go/src/github.com/ceph/ceph-csi

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

This is not fixed yet happening at https://github.com/ceph/ceph-csi/runs/6345425683?check_suite_focus=true#step:3:1419

2022-05-09 04:48 UTC, Rakshith-R requested changes
Let's add it within the script

https://github.com/ceph/ceph-csi/blob/9533889b643f8274e8a0aae5583b022ddb1f5ee3/Makefile#L153

The step needs to be executed within the container
https://github.com/ceph/ceph-csi/runs/6346056638?check_suite_focus=true

2022-05-09 04:49 UTC, Madhu-1 commented
> Let's add it within the script
> 
> https://github.com/ceph/ceph-csi/blob/9533889b643f8274e8a0aae5583b022ddb1f5ee3/Makefile#L153

Am still testing this one. I don't see the problem in the local setup. if adding to a workflow does not help. will add it there as the last option.

2022-05-09 05:22 UTC, yati1998 submitted a review, later dismissed

2022-05-09 05:30 UTC, Rakshith-R approved these changes

2022-05-09 05:31 UTC, yati1998 approved these changes

2022-05-09 05:53 UTC, nixpanic approved these changes

2022-05-09 05:57 UTC, merged

2022-05-10 04:16 UTC, Madhu-1 commented
@mergifyio backport release-v3.6