chore(deps): Included dependency review
ceph/ceph-csi pull request #3127
Opened 2022-05-19 03:14 UTC by naveensrinivasan

> Dependency Review GitHub Action in your repository to enforce dependency reviews on your pull requests. 
> The action scans for vulnerable versions of dependencies introduced by package version changes in pull requests,
> and warns you about the associated security vulnerabilities. 
> This gives you better visibility of what's changing in a pull request, 
> and helps prevent vulnerabilities being added to your repository.

https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement

2022-05-19 03:16 UTC, naveensrinivasan commented
@nixpanic  👀

2022-05-19 06:44 UTC, yati1998 requested changes
Please check the CI errors. You need to check the commit messgae.

2022-05-19 11:43 UTC, naveensrinivasan commented
> Please check the CI errors. You need to check the commit messgae.

I took care of PTAL. Thanks

2022-05-19 11:52 UTC, naveensrinivasan commented
I am not trying to be hard. The commit message length is an issue because my DCO is longer than `80` characters. How do you address those issues?

2022-05-23 05:50 UTC, nixpanic commented
> I am not trying to be hard. The commit message length is an issue because my DCO is longer than `80` characters. How do you address those issues?

It seems I used "Naveen" as name in 09f8ee0f3fcc8a51effe19039637d646ecd7dc9e earlier. If you want, I can take this PR forward as well.

2022-05-23 11:22 UTC, naveensrinivasan commented
> > I am not trying to be hard. The commit message length is an issue because my DCO is longer than `80` characters. How do you address those issues?
> 
> It seems I used "Naveen" as name in [09f8ee0](https://github.com/ceph/ceph-csi/commit/09f8ee0f3fcc8a51effe19039637d646ecd7dc9e) earlier. If you want, I can take this PR forward as well.

Please do. Thanks

2022-05-23 15:52 UTC, nixpanic approved these changes

2022-05-23 15:53 UTC, nixpanic approved these changes

2022-05-23 16:00 UTC, nixpanic approved these changes, later dismissed

2022-05-24 03:34 UTC, Madhu-1 approved these changes

2022-05-24 03:35 UTC, Madhu-1 commented
@yati1998 PTAL

2022-05-24 04:32 UTC, yati1998 approved these changes

2022-05-24 06:48 UTC, merged