deploy: make use of latest attacher release v3.5.0
ceph/ceph-csi pull request #3170
Opened 2022-06-09 05:21 UTC by humblec

attacher sidecar has a new release:
https://github.com/kubernetes-csi/external-attacher/releases/tag/v3.5.0

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

# Describe what this PR does #

Provide some context for the reviewer

## Is there anything that requires special attention ##

Do you have any questions?

Is the change backward compatible?

Are there concerns around backward compatibility?

Provide any external context for the change, if any.

For example:

* Kubernetes links that explain why the change is required
* CSI spec related changes/catch-up that necessitates this patch
* golang related practices that necessitates this change

## Related issues ##

Mention any github issues relevant to this PR. Adding below line
will help to auto close the issue once the PR is merged.

Fixes: #issue_number

## Future concerns ##

List items that are not part of the PR and do not impact it's
functionality, but are work items that can be taken up subsequently.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

2022-06-09 07:04 UTC, humblec commented
the attacher image still in syncing phase in the registry.. will remove the `WIP` once its synced.

2022-06-09 14:16 UTC, humblec commented
@Mergifyio rebase

2022-06-09 14:17 UTC, humblec commented
> the attacher image still in syncing phase in the registry.. will remove the `WIP` once its synced.

Available now :+1:

2022-06-09 14:29 UTC, Madhu-1 requested changes

2022-06-09 14:29 UTC, Madhu-1 commented on charts/ceph-csi-rbd/values.yaml
> +      tag: v3.5.0
update helm doc for this one.

2022-06-09 15:04 UTC, humblec commented on charts/ceph-csi-rbd/values.yaml
> +      tag: v3.5.0
Done.

2022-06-13 11:14 UTC, humblec commented
@Mergifyio rebase

2022-06-14 16:39 UTC, nixpanic submitted a review, later dismissed

2022-06-15 03:40 UTC, yati1998 approved these changes, later dismissed

2022-06-16 06:21 UTC, humblec commented
@Madhu-1 rebase to devel, ptal.. thanks.

2022-06-16 06:52 UTC, Madhu-1 approved these changes

2022-06-16 07:38 UTC, yati1998 approved these changes

2022-06-17 07:00 UTC, nixpanic commented
@mergifyio rebase

CI jobs seem to be stuck, and an other PR was merged recently (I think)

2022-06-17 11:39 UTC, nixpanic commented
@mergifyio rebase

An other PR was merged, no need to keep retrying before rebasing.

2022-06-17 15:46 UTC, merged