rbd: have dummy attacher implementation
ceph/ceph-csi pull request #3199
Opened 2022-06-21 09:21 UTC by humblec

This commit add dummy implementation for attacher.

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

2022-06-21 10:46 UTC, nixpanic commented
Why?

2022-06-23 09:42 UTC, humblec commented
/retest all

2022-06-23 13:08 UTC, nixpanic commented
> /retest all

Please don't do this for PRs that are not completely ready, or do not require exhaustive testing yet. The CI environment is rather busy already, re-testing like this just prevents other PRs from getting merged sooner.

2022-06-24 05:28 UTC, humblec commented
/retest ci/centos/mini-e2e/k8s-1.22

2022-06-24 05:29 UTC, humblec commented
/retest ci/centos/k8s-e2e-external-storage/1.23

2022-06-24 08:06 UTC, humblec commented
/retest ci/centos/mini-e2e/k8s-1.22

2022-06-24 08:06 UTC, humblec commented
/retest ci/centos/mini-e2e-helm/k8s-1.22

2022-06-24 10:12 UTC, humblec commented
@nixpanic added the details to the commit and PR. Also tests are passing ! ptal.. thanks..

2022-06-29 07:59 UTC, nixpanic requested changes

2022-06-29 07:59 UTC, nixpanic commented on internal/cephfs/controllerserver.go
> +// ControllerPublishVolume publish volume on node.
Why include this in CephFS if it does not need it? Keep it in the `DefaultControllerServer` instead.

2022-06-29 07:59 UTC, nixpanic commented on internal/rbd/controllerserver.go
> +	// A dummy publish implementation to mimic a successful attach operation being a NOOP
a description of the function should be above the function, that counts for `ControllerUnpublishVolume` too.

2022-06-29 07:59 UTC, nixpanic commented on internal/rbd/controllerserver.go
> +		PublishContext: map[string]string{},
add a comment why this map is (or needs to be) empty, please

2022-06-29 07:59 UTC, nixpanic commented on internal/rbd/controllerserver.go
> +	if req.VolumeId == "" {
use functions like `req.GetVolumeId()` instead of accessing the attribute directly.

2022-07-21 09:56 UTC, humblec commented
all the test failures are on ```Errors during downloading metadata for repository 'tcmu-runner':

  - Status code: 404 for https://3.chacra.ceph.com/r/tcmu-runner/master/245914c1446dddf07d5b58b0a7b2060b50fde4d7/centos/8/flavors/default/x86_64/repodata/repomd.xml (IP: 158.69.93.173)

Error: Failed to download metadata for repo 'tcmu-runner': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

Error: error building at STEP "RUN dnf -y install 	librados-devel librbd-devel 	/usr/bin/cc 	make 	git 	&& dnf clean all 	&& rm -rf /var/cache/yum     && true": error while running runtime: exit status 1

make: *** [Makefile:233: image-cephcsi] Error 1

script returned exit code 2```

2022-07-21 09:56 UTC, humblec commented
@Mergifyio rebase

2022-07-22 07:15 UTC, humblec commented
@nixpanic comments are addressed.. ptal.. thanks

2022-07-22 07:57 UTC, humblec commented
/retest ci/centos/k8s-e2e-external-storage/1.22

2022-07-22 07:57 UTC, humblec commented
/retest ci/centos/mini-e2e/k8s-1.23

2022-07-22 10:18 UTC, humblec commented
/retest ci/centos/k8s-e2e-external-storage/1.22

2022-07-25 07:44 UTC, humblec commented
@nixpanic can you revisit as I have addressed the changes requested here ?

2022-07-25 08:45 UTC, nixpanic commented
Is there a reason to keep `ControllerPublishVolume` in `internal/csi-common/controllerserver-default.go`? Or does it make sense to move this dummy implementation there instead?

If `ControllerPublishVolume` is only needed for NBD support, it should probably be reported as a feature only for NBD backed volumes. But, I guess the controller does not report the capabilities depending on the parameters for the volume?

2022-07-27 09:14 UTC, humblec commented
> Is there a reason to keep `ControllerPublishVolume` in `internal/csi-common/controllerserver-default.go`? Or does it make sense to move this dummy implementation there instead?

in this case, it default to not `implemented` ( inherited for cephfs) and only get an implementation in case of RBD. 
> 
> If `ControllerPublishVolume` is only needed for NBD support, it should probably be reported as a feature only for NBD backed volumes. But, I guess the controller does not report the capabilities depending on the parameters for the volume?

Yeah, this return fall into get caps call for the controller..

2022-07-27 09:15 UTC, humblec commented
@nixpanic I have answered the queries.. ptal. thanks.

2022-07-29 13:21 UTC, humblec commented
@nixpanic ptal

2022-08-02 09:21 UTC, humblec commented
@nixpanic ptal. Thanks

2022-08-02 10:36 UTC, nixpanic approved these changes

2022-08-02 10:56 UTC, pkalever commented
@humblec is this a preparation for removing the `registry.k8s.io/sig-storage/csi-attacher` sidecar from RBD provisioner in the future?

2022-08-02 11:04 UTC, humblec commented
> @humblec is this a preparation for removing the `registry.k8s.io/sig-storage/csi-attacher` sidecar from RBD provisioner in the future?

This is not related to that @pkalever

2022-08-02 11:06 UTC, yati1998 approved these changes

2022-08-02 11:06 UTC, humblec commented
@Mergifyio refresh

2022-08-02 11:07 UTC, humblec commented
@Mergifyio rebase

2022-08-02 11:12 UTC, pkalever commented
> > @humblec is this a preparation for removing the `registry.k8s.io/sig-storage/csi-attacher` sidecar from RBD provisioner in the future?
> 
> This is not related to that @pkalever

Then I'm confused.

> previously, it was a requirement to have attacher sidecar for CSI
> drivers and there had an implementation of dummy mode of operation.

Well even now we have the csi-attacher sidecar, right?
Don't know what I'm missing here, could you please help me understand?

2022-08-03 00:25 UTC, merged