revert: rbd: consider remote image health for primary
ceph/ceph-csi pull request #3216
Opened 2022-06-27 13:12 UTC by Madhu-1

When the image is force promoted to primary on the cluster the remote image might not be in a replaying
state because due to the split-brain state. This PR reverts back the commit c3c87f2ef33e8d8ad08d7d9f28b59d1aedc4ef31. Which we added to check the remote image status.

closes: #3215 

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

2022-06-27 13:13 UTC, Madhu-1 commented
skipping CI as we dont have E2E testing for Mirroring

2022-06-27 13:18 UTC, ShyamsundarR submitted a review, later dismissed
LGTM, tested with similar changes as well...

2022-06-27 14:29 UTC, nixpanic requested changes
By reverting this, won't you re-introduce the problem that the change addressed? The original commit points to https://bugzilla.redhat.com/show_bug.cgi?id=2014495.

Can you explain why this is not an issue?

I also expect to see some unit testing for different image/mirroring statuses. This code seems fragile enough that breakage is not easily spotted or detected. The change that introduced the regression was only detected months after is has been merged. Breaking this code in the future should be of the highest priority.

2022-06-28 04:38 UTC, Madhu-1 commented
> By reverting this, won't you re-introduce the problem that the change addressed? The original commit points to https://bugzilla.redhat.com/show_bug.cgi?id=2014495.
> 

It was not a problem, it's an enhancement we did, as this is getting reverted back I will move the BZ to the next release (downstream )

> Can you explain why this is not an issue?
>

As I mentioned above its an enhancement we tried to due but introduced a regression in a corner case. AFAIK, so revert back is fine 
 
> I also expect to see some unit testing for different image/mirroring statuses. This code seems fragile enough that breakage is not easily spotted or detected. 

Unit testing is not possible as `checkHealthyPrimary` makes a ceph call to get the mirroring image details.

> The change that introduced the regression was only detected months after is has been merged. Preventing breaking this code in the future should be of the highest priority.

not all the cases can be covered in the happy path testing, as you know testing DR is always hard we get new bugs in different areas when we started exploring different areas.

2022-06-28 07:56 UTC, nixpanic reviewed
> > By reverting this, won't you re-introduce the problem that the change addressed? The original commit points to https://bugzilla.redhat.com/show_bug.cgi?id=2014495.
> 
> It was not a problem, it's an enhancement we did, as this is getting reverted back I will move the BZ to the next release (downstream )

Ok! It would be good to have the enhancement documented in this project too. Please create an issue for that.

> > Can you explain why this is not an issue?
> 
> As I mentioned above its an enhancement we tried to due but introduced a regression in a corner case. AFAIK, so revert back is fine

Thanks for considering, that was not clear to me by reading the PR description or commit message.

> > I also expect to see some unit testing for different image/mirroring statuses. This code seems fragile enough that breakage is not easily spotted or detected.
> 
> Unit testing is not possible as `checkHealthyPrimary` makes a ceph call to get the mirroring image details.

It is important to find a way for testing this, at least minimally. A regression was introduced because of missing tests, and there is no guarantee that a future _enhancement_ like this will not break things again.

> > The change that introduced the regression was only detected months after is has been merged. Preventing breaking this code in the future should be of the highest priority.
> 
> not all the cases can be covered in the happy path testing, as you know testing DR is always hard we get new bugs in different areas when we started exploring different areas.

Unit testing is not only about happy-path testing. Specially for features that can not be tested in e2e (yet), unit-tests are important. Can you consider re-structuring the code a bit, so that the mirror status and planned actions can be validated?

2022-06-28 08:31 UTC, nixpanic submitted a review, later dismissed
much appreciated, thanks!

2022-06-28 08:34 UTC, Madhu-1 commented
> much appreciated, thanks!

Fixed CI test failure, PTAL

2022-06-28 12:21 UTC, ShyamsundarR approved these changes

2022-06-28 12:28 UTC, nixpanic approved these changes

2022-06-28 12:59 UTC, nixpanic commented
@mergifyio requeue

2022-06-28 13:17 UTC, Madhu-1 commented
@mergifyio refresh

2022-06-28 13:17 UTC, merged