logging: reduce systemd related errors while mounting
ceph/ceph-csi pull request #3225
Opened 2022-06-29 14:00 UTC by nixpanic

There are regular reports that identify a non-error as the cause of
failures. The Kubernetes mount-utils package has detection for systemd
based environments, and if systemd is unavailable, the following error
is logged:

    Cannot run systemd-run, assuming non-systemd OS
    systemd-run output: System has not been booted with systemd as init
    system (PID 1). Can't operate.
    Failed to create bus connection: Host is down, failed with: exit status 1

Because of the `failed` and `exit status 1` error message, users might
assume that the mounting failed. This does not need to be the case. The
container-images that the Ceph-CSI projects provides, do not use
systemd, so the error will get logged with each mount attempt.

By using the newer MountSensitiveWithoutSystemd() function from the
mount-utils package where we can, the number of confising logs get
reduced.

See-also: #2890

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

2022-06-29 14:03 UTC, humblec requested changes
`mount-utils package where we can, the number of confising logs get
reduced.` -> confusing ..

2022-06-29 14:53 UTC, humblec commented
lgtm. if you can correct the commitlint failure.

2022-06-29 16:51 UTC, humblec approved these changes

2022-07-01 05:23 UTC, yati1998 approved these changes

2022-07-04 05:53 UTC, Rakshith-R commented
@mergifyio rebase

2022-07-04 10:02 UTC, merged