build: add mergify rule for backport PRs in release 3.7 branch
ceph/ceph-csi pull request #3319
Opened 2022-08-18 09:57 UTC by humblec

This commit add rule for backporting to release 3.7 branch with
label `backport-to-release-v3.7`

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

2022-08-18 10:20 UTC, Rakshith-R submitted a review, later dismissed

2022-08-18 12:44 UTC, nixpanic requested changes
probably good to remove the rules for v3.5 now too?

2022-08-18 12:48 UTC, humblec commented
> probably good to remove the rules for v3.5 now too?

sure, make sense.. updated the PR with the removal

2022-08-18 13:14 UTC, Rakshith-R approved these changes

2022-08-18 16:01 UTC, humblec commented
@nixpanic can you take a look at the new version ?

2022-08-18 16:44 UTC, nixpanic approved these changes

2022-08-19 02:41 UTC, humblec commented
@Mergifyio refresh

2022-08-19 02:42 UTC, merged