deploy: update resizer to v1.6.0 version
ceph/ceph-csi pull request #3391
Opened 2022-09-14 08:40 UTC by humblec

This commit make deployment changes to consume v1.6.0 version of the resizer controller.

Reference:
https://github.com/kubernetes-csi/external-resizer/releases/tag/v1.6.0

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

2022-09-14 10:55 UTC, Madhu-1 approved these changes

2022-09-14 10:56 UTC, Madhu-1 requested changes
update in helm readme for both cephfs and rbd is missing

2022-09-14 10:56 UTC, Madhu-1 commented
@humblec, any reason to backport this to 3.7?

2022-09-19 06:20 UTC, humblec commented
> @humblec, any reason to backport this to 3.7?

its ok to not backport too. I have removed the label and also changed the readme. That readme has to be updated for other sidecars but I will put it as a seperate PR. @Madhu-1 ptal.. thanks

2022-09-19 06:27 UTC, Madhu-1 approved these changes

2022-09-19 07:15 UTC, yati1998 approved these changes

2022-09-20 10:32 UTC, merged