Revert "deploy: change image versions to v3.7.1"
ceph/ceph-csi pull request #3405
Opened 2022-09-29 03:45 UTC by humblec

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

2022-09-29 08:22 UTC, nixpanic approved these changes, later dismissed

2022-09-29 08:26 UTC, Rakshith-R approved these changes

2022-09-29 08:29 UTC, Rakshith-R requested changes
Helm values.yaml and minikube.sh needs update too?
https://github.com/ceph/ceph-csi/pull/3330/files

2022-09-29 11:28 UTC, humblec commented
> Helm values.yaml and minikube.sh needs update too? https://github.com/ceph/ceph-csi/pull/3330/files

minikube.sh is already on `canary`. ptal.. thanks. @Rakshith-R

2022-09-29 11:32 UTC, Rakshith-R approved these changes
Thanks

2022-09-30 16:19 UTC, nixpanic approved these changes

2022-09-30 20:49 UTC, merged