add commonLabels value
ceph/ceph-csi pull request #3438
Opened 2022-10-14 15:05 UTC by bastienbosser

Signed-off-by: BOSSER, Bastien <bastien.bosser@atos.net>

# Describe what this PR does #

Add a commonLabels variable in the values.yml file that allows to add additional labels on all helm chart resources.

As you know, labels can be used to organize and to select subsets of objects. In my case of use it allows me to group the applications by category and to check by a simple command the status of it.

As examples, for all security applications, I put a label "my-cluster-name/application_group: security". Then I just have to make the command "kubectl get all -A -l my-cluster-name/application_group=security" to know the status of all applications that provide security.

## Related issues ##

Fixes: #3437

2022-10-17 07:25 UTC, nixpanic requested changes
Looks reasonable to me, thanks for the PR!

You will need to force-push a correction though. The subject of the commit should have a topic, and that is missing at the moment. I recommend using

    deploy: add commonLabels value

or similar. The commit message itself can also have a few more details, basically copy/paste from the PR description.

2022-10-17 07:36 UTC, Madhu-1 reviewed
please add some test labels here https://github.com/ceph/ceph-csi/blob/devel/scripts/install-helm.sh#L172-L182 so that this will be get tested in CI

2022-10-26 14:32 UTC, bastienbosser commented
@nixpanic I changed the commit message.
@Madhu-1 What type of test would you like me to develop? Should I just add the customLabels value in the helm deploy?

2022-10-26 14:34 UTC, Madhu-1 commented
> @nixpanic I changed the commit message. @Madhu-1 What type of test would you like me to develop? Should I just add the customLabels value in the helm deploy?

Just add some sample custom labels to the above script

2022-10-26 15:15 UTC, bastienbosser commented
@Madhu-1 Are the tests suitable for you?

2022-10-26 15:24 UTC, Madhu-1 commented on scripts/install-helm.sh
> +    "${HELM}" install --namespace ${NAMESPACE} --set provisioner.fullnameOverride=csi-rbdplugin-provisioner --set nodeplugin.fullnameOverride=csi-rbdplugin --set configMapName=ceph-csi-config --set p
looks good, can you please add some meaningful names (choose whatever you like something specific to cephcsi)
```
--set-json='commonLabels={"component": "ceph", "sub-component": "rbd"}'
```

2022-10-26 16:11 UTC, Madhu-1 reviewed
changes LGTM, please squash the commits.

2022-10-27 04:59 UTC, humblec requested changes, later dismissed

2022-10-27 04:59 UTC, humblec commented on scripts/install-helm.sh
> +    "${HELM}" install --namespace ${NAMESPACE} --set provisioner.fullnameOverride=csi-rbdplugin-provisioner --set nodeplugin.fullnameOverride=csi-rbdplugin --set configMapName=ceph-csi-config --set p
change below to ```"app.kubernetes.io/name": "ceph-csi-rdb"``` to ```"app.kubernetes.io/name": "ceph-csi-rbd"```

2022-10-27 06:02 UTC, bastienbosser commented on scripts/install-helm.sh
> +    "${HELM}" install --namespace ${NAMESPACE} --set provisioner.fullnameOverride=csi-rbdplugin-provisioner --set nodeplugin.fullnameOverride=csi-rbdplugin --set configMapName=ceph-csi-config --set p
Done

2022-10-27 06:21 UTC, bastienbosser commented
> changes LGTM, please squash the commits.

Normally you can do this directly during the merge @Madhu-1

2022-10-27 06:29 UTC, Rakshith-R commented
> > changes LGTM, please squash the commits.
> 
> Normally you can do this directly during the merge @Madhu-1

@bastienbosser 
This is currently automated in cephcsi repo.
[merigfyio](https://mergify.com/) bot will be merging this pr with `rebase and merge` logic after approvals and successful ci runs.
It'll be cleaner to have one commit for this pr.

Thanks !

2022-10-27 14:16 UTC, bastienbosser commented
> > > changes LGTM, please squash the commits.
> > 
> > 
> > Normally you can do this directly during the merge @Madhu-1
> 
> @bastienbosser This is currently automated in cephcsi repo. [merigfyio](https://mergify.com/) bot will be merging this pr with `rebase and merge` logic after approvals and successful ci runs. It'll be cleaner to have one commit for this pr.
> 
> Thanks !

Done

2022-10-27 14:57 UTC, Madhu-1 submitted a review, later dismissed

2022-10-28 14:03 UTC, nixpanic submitted a review, later dismissed

2022-10-28 14:04 UTC, nixpanic commented
After other PRs are done with their CI runs, this can be rebased by Mergify and de `ok-to-test` label can be added

2022-10-28 19:49 UTC, Madhu-1 commented
@mergifyio rebase

2022-10-31 13:16 UTC, bastienbosser commented
There are a lot of failed tests but I'm having a little trouble relating these errors to the changes made. Can any of you (@nixpanic @Madhu-1) help me?

2022-10-31 14:58 UTC, nixpanic reviewed
It seems the deploying through Helm is not working. All CI jobs fail in a similar way:

- job: https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/k8s-e2e-external-storage-1.25/detail/k8s-e2e-external-storage-1.25/31/pipeline/96
- logs: https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/rest/organizations/jenkins/pipelines/k8s-e2e-external-storage-1.25/runs/31/nodes/96/log/?start=0

Snippet:
```
Fri Oct 28 20:20:37 UTC 2022: 'kubectl_retry label node/minikube test.failure-domain/zone=testzone' done (ret=0)
node/minikube labeled
Error: unknown flag: --set-json
...
```

Maybe `--set-json` is something of a newer Helm version? You can change the Helm version in the `build.env` file.

2022-11-01 12:02 UTC, Madhu-1 commented
> It seems the deploying through Helm is not working. All CI jobs fail in a similar way:
> 
> * job: https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/k8s-e2e-external-storage-1.25/detail/k8s-e2e-external-storage-1.25/31/pipeline/96
> * logs: https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/rest/organizations/jenkins/pipelines/k8s-e2e-external-storage-1.25/runs/31/nodes/96/log/?start=0
> 
> Snippet:
> 
> ```
> Fri Oct 28 20:20:37 UTC 2022: 'kubectl_retry label node/minikube test.failure-domain/zone=testzone' done (ret=0)
> node/minikube labeled
> Error: unknown flag: --set-json
> ...
> ```
> 
> Maybe `--set-json` is something of a newer Helm version? You can change the Helm version in the `build.env` file.

Yes, because of the missing flag, deployment was not successful and csi pods are not running as expected. Can you please use some other existing flag to set it or we need to update the helm version in the build.env?

2022-11-02 07:09 UTC, bastienbosser commented
I changed the helm version in the build.env file to make the tests work.

2022-11-02 07:46 UTC, Madhu-1 commented
> I changed the helm version in the build.env file to make the tests work.

How this value can be set if someone is using an older helm version? Do you have the sample command?

2022-11-02 07:46 UTC, Madhu-1 commented
/test ci/centos/mini-e2e/k8s-1.25

2022-11-02 07:47 UTC, Madhu-1 commented
/test ci/centos/mini-e2e/k8s-1.25

2022-11-02 08:57 UTC, nixpanic commented
> /test ci/centos/mini-e2e/k8s-1.25

Seems to run well now!

2022-11-02 08:57 UTC, nixpanic approved these changes

2022-11-02 08:59 UTC, Madhu-1 approved these changes

2022-11-02 09:01 UTC, humblec approved these changes

2022-11-02 09:48 UTC, nixpanic commented
@mergifyio rebase

2022-11-02 11:28 UTC, merged