Cleanup snapshots before removing rbd image
ceph/ceph-csi pull request #3456
Opened 2022-10-19 11:24 UTC by ruslanloman

Hello!

# Describe what this PR does #

Ceph csi couldn't remove pvc with snapshots that was created directly in
ceph using rbd or other clients. As a result, the rbd image remains permanently in the trash.
As solution we can cleanup snapshots before removing rbd image.

## Related issues ##

Fixes: #3416

2022-10-19 11:49 UTC, nixpanic reviewed
I am not sure this is what all users want. Some users might still want to use the snapshot, even when someone/thing else deleted the volume. Having the snapshot available, and the parent rbd image in the trash makes it possible to undo unintentional deletions (for example).

2022-10-19 11:49 UTC, nixpanic commented on internal/rbd/rbd_util.go
> +		log.DebugLog(ctx, "rbd: failed to get list of snapshots %v", err)
return the error?

2022-10-19 11:54 UTC, Madhu-1 commented
> ceph using rbd or other clients. As a result, the rbd image remains permanently in the trash.

why cephcsi need to handle the user created snapshots? if user is creating the snapshot its user responsibility to delete it also https://github.com/ceph/ceph-csi/issues/3416, having this feature can also lead to similar changes for others also like Replication, cephfs subvolume deletion etc (just an example).

2022-10-19 11:59 UTC, Rakshith-R requested changes
We still had discussions going on the issue thread?

>why does cephcsi need to handle the user created snapshots? if user is creating the snapshot its user responsibility to delete it also

+1
We cannot guarantee such behavior, when another external entity acts on cephcsi managed images.

We cannot purge snapshots of a pvc having k8s snapshot and clone. These preserve the link between parent and child

2022-10-19 13:55 UTC, ruslanloman commented
Hi, thank you for your comments!

With this PR i'm trying to find some solution for this issue. Because right now cephcsi couldn't remove the ceph rdb image with snapshots and we can consider it as a bug.
There are 3 solutions that i have in my mind.
1. Purge snapshots before image removing (this approach is  in PR)
2. In case we are trying to remove pvc with rbd snapshots then we just return an error and let the client clean it up manually.
3. Same as item #1 but we can add a config option to allow snapshot cleanup.

2022-10-19 16:38 UTC, nixpanic commented
> With this PR i'm trying to find some solution for this issue. Because right now cephcsi couldn't remove the ceph rdb image with snapshots and we can consider it as a bug. There are 3 solutions that i have in my mind.

I don't think this is a bug, I would probably call it _intentional behaviour_. It might be unexpected for some users, but Ceph-CSI should not, and does not delete volumes or snapshots that were created by others.

>     1. Purge snapshots before image removing (this approach is  in PR)
> 
>     2. In case we are trying to remove pvc with rbd snapshots then we just return an error and let the client clean it up manually.
> 
>     3. Same as item 1 but we can add a config option to allow snapshot cleanup.

I think option 2 is the most reasonable. Ceph-CSI should not (never) be able to get blamed for data-loss, and wrongly configuring a "force snapshot removal" option invites that (even if it is an admin/user error).

Option 2 makes sure that the user/admin notices their unbalanced usage of Ceph-CSI and other tools. The user/admin should then decide to correct the cooperation of the tools/procedures.

2022-10-20 08:08 UTC, ruslanloman commented
Hi @nixpanic I got your point. I'm going to close this PR as invalid.

2022-10-20 08:08 UTC, closed without merging