ci: disable e2e tests by default in CI
ceph/ceph-csi pull request #3469
Opened 2022-10-25 11:34 UTC by Madhu-1

Disable e2e tests by default in CI to save resources. cephcsi maintainers or contributors can add the `ok-to-test` label to trigger the e2e tests.

depends on #3468

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

2022-10-25 11:36 UTC, nixpanic approved these changes

2022-10-25 11:37 UTC, nixpanic requested changes

2022-10-25 11:37 UTC, nixpanic commented on jobs/upgrade-tests.yaml
> +      only_run_on_request: true
indention causes issues, needs to be fixed

2022-10-25 11:52 UTC, nixpanic approved these changes

2022-10-26 04:43 UTC, Rakshith-R approved these changes

2022-10-26 04:43 UTC, merged