rbd: fix namespace name update in metadata and rados object
ceph/ceph-csi pull request #3477
Opened 2022-10-27 14:54 UTC by Madhu-1

If a PV is reattached to a new PVC in a different namespace, we need to update the namespace name in the rbd image metadata.
If a PV is reattached to a new PVC in a different namespace, we need to update the namespace name in the rados object.

* Create a RBD PVC in default namespace
```bash
[🎩︎]mrajanna@fedora rbd $]kubectl get pvc
NAME      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
rbd-pvc   Bound    pvc-2e85eed4-b13a-478b-afb0-3217069d5ca7   1Gi        RWO            rook-ceph-block   76s
```
* check metadata of the image
```bash
sh-4.4$ rbd image-meta ls replicapool/csi-vol-333a1bdc-55fb-11ed-b453-be69662ea197
There are 4 metadata on this image:

Key                               Value                                   
csi.ceph.com/cluster/name         my-prod-cluster                         
csi.storage.k8s.io/pv/name        pvc-2e85eed4-b13a-478b-afb0-3217069d5ca7
csi.storage.k8s.io/pvc/name       rbd-pvc                                 
csi.storage.k8s.io/pvc/namespace  default         
```

* Attach same PV to different PVC in new namespace

```bash
[🎩︎]mrajanna@fedora rbd $]kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                   STORAGECLASS      REASON   AGE
pvc-2e85eed4-b13a-478b-afb0-3217069d5ca7   1Gi        RWO            Retain           Bound    rook-ceph/rbd-pvc-new   rook-ceph-block            3m47s
[🎩︎]mrajanna@fedora rbd $]
[🎩︎]mrajanna@fedora rbd $]
[🎩︎]mrajanna@fedora rbd $]kuberc get pvc
NAME          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
rbd-pvc-new   Bound    pvc-2e85eed4-b13a-478b-afb0-3217069d5ca7   1Gi        RWO            rook-ceph-block   13s
```
* Check metadata of the image
```bash
sh-4.4$ rbd image-meta ls replicapool/csi-vol-333a1bdc-55fb-11ed-b453-be69662ea197
There are 4 metadata on this image:

Key                               Value                                   
csi.ceph.com/cluster/name         my-prod-cluster                         
csi.storage.k8s.io/pv/name        pvc-2e85eed4-b13a-478b-afb0-3217069d5ca7
csi.storage.k8s.io/pvc/name       rbd-pvc-new                             
csi.storage.k8s.io/pvc/namespace  default                                 
sh-4.4$ 
```
```
sh-4.4$ rados listomapvals csi.volume.333a1bdc-55fb-11ed-b453-be69662ea197 --pool=replicapool
csi.imageid
value (12 bytes) :
00000000  31 31 35 32 32 39 30 30  33 63 66 35              |115229003cf5|
0000000c

csi.imagename
value (44 bytes) :
00000000  63 73 69 2d 76 6f 6c 2d  33 33 33 61 31 62 64 63  |csi-vol-333a1bdc|
00000010  2d 35 35 66 62 2d 31 31  65 64 2d 62 34 35 33 2d  |-55fb-11ed-b453-|
00000020  62 65 36 39 36 36 32 65  61 31 39 37              |be69662ea197|
0000002c

csi.volname
value (40 bytes) :
00000000  70 76 63 2d 32 65 38 35  65 65 64 34 2d 62 31 33  |pvc-2e85eed4-b13|
00000010  61 2d 34 37 38 62 2d 61  66 62 30 2d 33 32 31 37  |a-478b-afb0-3217|
00000020  30 36 39 64 35 63 61 37                           |069d5ca7|
00000028

csi.volume.owner
value (7 bytes) :
00000000  64 65 66 61 75 6c 74                              |default|
00000007
```
As we can notice here, only the PVC name got updated not the namespace name in both metadata and in rados object also.

With this fix even the namespace name also got updated

```bash
sh-4.4$ rbd image-meta ls replicapool/csi-vol-333a1bdc-55fb-11ed-b453-be69662ea197
There are 4 metadata on this image:

Key                               Value                                   
csi.ceph.com/cluster/name         my-prod-cluster                         
csi.storage.k8s.io/pv/name        pvc-2e85eed4-b13a-478b-afb0-3217069d5ca7
csi.storage.k8s.io/pvc/name       rbd-pvc-new                             
csi.storage.k8s.io/pvc/namespace  rook-ceph                               
```
```
sh-4.4$ rados listomapvals csi.volume.333a1bdc-55fb-11ed-b453-be69662ea197  --pool=replicapool
csi.imageid
value (12 bytes) :
00000000  31 31 35 32 32 39 30 30  33 63 66 35              |115229003cf5|
0000000c

csi.imagename
value (44 bytes) :
00000000  63 73 69 2d 76 6f 6c 2d  33 33 33 61 31 62 64 63  |csi-vol-333a1bdc|
00000010  2d 35 35 66 62 2d 31 31  65 64 2d 62 34 35 33 2d  |-55fb-11ed-b453-|
00000020  62 65 36 39 36 36 32 65  61 31 39 37              |be69662ea197|
0000002c

csi.volname
value (40 bytes) :
00000000  70 76 63 2d 32 65 38 35  65 65 64 34 2d 62 31 33  |pvc-2e85eed4-b13|
00000010  61 2d 34 37 38 62 2d 61  66 62 30 2d 33 32 31 37  |a-478b-afb0-3217|
00000020  30 36 39 64 35 63 61 37                           |069d5ca7|
00000028

csi.volume.owner
value (9 bytes) :
00000000  72 6f 6f 6b 2d 63 65 70  68                       |rook-ceph|
00000009
```

2022-10-27 14:59 UTC, pkalever commented
@Madhu-1 Would it be good to have a testcase for this?

2022-10-27 15:00 UTC, Madhu-1 commented
> @Madhu-1 Would it be good to have a testcase for this?

i thought about it, but it required namespace creation, currently we dont create new namespaces in our E2E tests

2022-10-27 15:15 UTC, Madhu-1 commented
> @Madhu-1 Would it be good to have a testcase for this?

@pkalever Added now. PTAL

2022-10-28 07:41 UTC, Madhu-1 commented
/test ci/centos/mini-e2e-helm/k8s-1.22

2022-10-28 08:00 UTC, nixpanic requested changes
just some minor comments, looks good functionally

2022-10-28 08:00 UTC, nixpanic commented on e2e/rbd.go
> +				reattachPVCNamespace := "reattach-cephfs"
Can you take the current name of the namespace , and append it with `-2` or something instead?

2022-10-28 08:00 UTC, nixpanic commented on internal/journal/voljournal.go
> +// ResetVolumeOwner update the owner in the rados object.
nit/typo: ... updates ...

2022-10-28 08:00 UTC, nixpanic commented on internal/journal/voljournal.go
> +	err := setOMapKeys(ctx, conn, pool, conn.config.namespace, conn.config.cephUUIDDirectoryPrefix+reservedUUID,
maybe just `return setOMapKeys(...)`?

2022-10-28 08:00 UTC, nixpanic commented on internal/rbd/rbd_journal.go
> +		return rbdVol.VolID, err
`err` will always be `nil` here. I prefer to have an explicit **no error** case, and returning `err` here make it look like there could be still an error lingering, in which case the `rbdVol.VolID` should not be trusted.

2022-10-28 08:28 UTC, nixpanic approved these changes, later dismissed

2022-10-28 10:38 UTC, pkalever commented
@Madhu-1 the changes look good, but the 3rd commit (e2e one) does address Niels previous review comments rather than the 1st and 2nd. Will it be good to merge the changes to respective commits?

2022-10-28 10:43 UTC, Madhu-1 commented
> @Madhu-1 the changes look good, but the 3rd commit (e2e one) does address Niels previous review comments rather than the 1st and 2nd. Will it be good to merge the changes to respective commits?

done now, PTAL

2022-10-28 10:45 UTC, Madhu-1 commented
/test ci/centos/mini-e2e/k8s-1.24

2022-10-28 11:00 UTC, nixpanic approved these changes

2022-10-28 11:05 UTC, pkalever approved these changes

2022-10-28 12:37 UTC, Madhu-1 commented
/test ci/centos/upgrade-tests

2022-10-28 12:37 UTC, Madhu-1 commented
/test ci/centos/mini-e2e/k8s-1.23

2022-10-28 12:37 UTC, Madhu-1 commented
/test ci/centos/mini-e2e/k8s-1.22

2022-10-28 12:37 UTC, Madhu-1 commented
/test ci/centos/mini-e2e-helm

2022-10-28 12:38 UTC, Madhu-1 commented
/test ci/centos/k8s-e2e-external-storage/k8s-1.22

2022-10-28 12:40 UTC, Madhu-1 commented
/test ci/centos/k8s-e2e-external-storage/1.22

2022-10-28 12:40 UTC, Madhu-1 commented
/test ci/centos/k8s-e2e-external-storage/1.23

2022-10-28 12:41 UTC, Madhu-1 commented
/test ci/centos/k8s-e2e-external-storage/1.24

2022-10-28 13:59 UTC, nixpanic commented
@mergifyio rebase

2022-10-28 15:50 UTC, merged