rbd: return error if last sync time not present
ceph/ceph-csi pull request #3489
Opened 2022-11-01 13:56 UTC by Madhu-1

As per the csiaddon spec, last sync time is a required parameter in the GetVolumeReplicationInfo if we are failed to parse the description, we return an error message instead of nil which is an empty response.

Signed-off-by: Madhu Rajanna [madhupr007@gmail.com](mailto:madhupr007@gmail.com)

Note:- skipping E2E as we dont have CI for DR

Note:- Replacement for https://github.com/ceph/ceph-csi/pull/3478 after discussion in csiaddons spec.

2022-11-01 14:07 UTC, Madhu-1 commented on go.mod
> +	golang.org/x/crypto v0.1.0
this got updated as part of `go get`

2022-11-01 14:17 UTC, ShyamsundarR reviewed
LGTM

2022-11-01 15:04 UTC, Madhu-1 commented
@ShyamsundarR PTAL at last commit. This check was missing, and cephcsi was returning an empty response.

2022-11-01 15:21 UTC, Madhu-1 commented
@mergifyio rebase

2022-11-01 15:39 UTC, ShyamsundarR commented
> @ShyamsundarR PTAL at last commit. This check was missing, and cephcsi was returning an empty response.

Thanks, I am only looking at overall structural correctness (hence not hitting the approved button). @yati1998 assuming you are taking a closer look?

2022-11-01 16:27 UTC, nixpanic requested changes
I think this looks good, but (a nit) the formatting of the error messages should be nicer.

2022-11-01 16:27 UTC, nixpanic commented on internal/rbd/replicationcontrollerserver.go
> +		return nil, fmt.Errorf("%w empty description", ErrLastSyncTimeNotFound)
missing `:` after `%w`?

2022-11-01 16:27 UTC, nixpanic commented on internal/rbd/replicationcontrollerserver.go
> +		return nil, fmt.Errorf("%w no local snapshot timestamp", ErrLastSyncTimeNotFound)
same here, formatting of error messages matter

2022-11-02 08:41 UTC, nixpanic submitted a review, later dismissed

2022-11-02 17:22 UTC, yati1998 approved these changes
LGTM

2022-11-02 17:31 UTC, Madhu-1 commented
@mergifyio rebase

2022-11-03 04:49 UTC, Rakshith-R approved these changes

2022-11-03 08:09 UTC, nixpanic approved these changes

2022-11-03 08:10 UTC, merged