rebase: update node driver registar to latest version
ceph/ceph-csi pull request #3491
Opened 2022-11-02 09:12 UTC by humblec

v2.6.0 is the latest version of the same and this commit update it.

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

2022-11-02 09:16 UTC, Madhu-1 requested changes

2022-11-02 09:16 UTC, Madhu-1 commented on charts/ceph-csi-cephfs/values.yaml
> +      tag: v2.6.0
update it in the helm documentation also

2022-11-02 09:16 UTC, Madhu-1 commented on charts/ceph-csi-rbd/values.yaml
> +      tag: v2.6.0
update it in the helm documentation also

2022-11-02 10:54 UTC, Madhu-1 approved these changes

2022-11-02 12:55 UTC, nixpanic approved these changes

2022-11-03 04:56 UTC, humblec commented
@Mergifyio refresh

2022-11-03 04:59 UTC, humblec commented
@Mergifyio rebase

2022-11-03 07:56 UTC, humblec commented
@Mergifyio requeue

2022-11-03 14:31 UTC, merged