e2e: use CurrentSpecReport for failed spec run
ceph/ceph-csi pull request #3506
Opened 2022-11-09 05:12 UTC by humblec

CurrentGinkgoTestDescription() has been deprecated in favor of CurrentSpecReport and this commit address the same.

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

2022-11-09 06:44 UTC, Rakshith-R commented
> CurrentGinkgoTestDescription() has been deprecated in favor of CurrentSpecReport and this commit address the same.
> 
> Signed-off-by: Humble Chirammal [hchiramm@redhat.com](mailto:hchiramm@redhat.com)

Can you please add link to where this is mentioned in the commit msg/ pr description please ?

2022-11-09 06:53 UTC, humblec commented
> > CurrentGinkgoTestDescription() has been deprecated in favor of CurrentSpecReport and this commit address the same.
> > Signed-off-by: Humble Chirammal [hchiramm@redhat.com](mailto:hchiramm@redhat.com)
> 
> Can you please add link to where this is mentioned in the commit msg/ pr description please ?

Done @Rakshith-R

2022-11-09 06:56 UTC, Rakshith-R requested changes
Needs similar in e2e/cephfs.go.

2022-11-09 07:00 UTC, humblec commented
> Needs similar in e2e/cephfs.go.

updated there too @Rakshith-R

2022-11-09 07:02 UTC, Rakshith-R approved these changes

2022-11-09 07:06 UTC, Madhu-1 approved these changes

2022-11-09 15:41 UTC, Madhu-1 commented
@mergifyio rebase

2022-11-10 07:08 UTC, humblec commented
@Mergifyio rebase

2022-11-10 07:09 UTC, humblec commented
@Mergifyio refresh

2022-11-10 09:30 UTC, merged