vendor: pin dynamic-resource-allocation to v0.26.1
ceph/ceph-csi pull request #3664
Opened 2023-02-14 06:15 UTC by Madhu-1

ping dynamic-resource-allocation dependency to v0.26.1 as the build sometimes fails with the below error message

```
k8s.io/dynamic-resource-allocation/@v/v0.0.0.info:
 404 Not Found
```

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

2023-02-14 07:07 UTC, yati1998 submitted a review, later dismissed

2023-02-14 08:29 UTC, nixpanic requested changes
I'm a little bit confused... This doesn't seem to fail in recent PRs? Where have you seen this failure?

2023-02-14 08:31 UTC, Rakshith-R submitted a review, later dismissed

2023-02-15 07:09 UTC, Madhu-1 commented
This was done to fix offline builds and some dependency check, i updated it in commit message forgot to update PR description, this is similar to https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1725

2023-02-15 08:10 UTC, nixpanic reviewed
If the command `go list -mod=readonly -m all` can trigger the problem, can you include it in the `make mod-check` target in the `Makefile`?

2023-02-15 08:22 UTC, Madhu-1 commented
> go list -mod=readonly -m all

Without fix

```
[🎩︎]mrajanna@fedora ceph-csi $]make mod-check 
cephcsi image settings: quay.io/cephcsi/cephcsi version canary
running: go mod verify
all modules verified
running: go list -mod=readonly -m all
go: k8s.io/dynamic-resource-allocation@v0.0.0: invalid version: unknown revision v0.0.0
make: *** [Makefile:110: mod-check] Error 1
```

2023-02-15 09:23 UTC, nixpanic approved these changes

2023-02-15 09:30 UTC, Madhu-1 commented
@mergifyio rebase

2023-02-15 09:35 UTC, Rakshith-R approved these changes

2023-02-15 10:02 UTC, yati1998 approved these changes

2023-02-15 10:09 UTC, merged