ci: fix modified gha-mergify-merge-queue-labels-copier Action
ceph/ceph-csi pull request #3836
Opened 2023-05-16 05:19 UTC by Rakshith-R

The `if` statement should end with `fi`.

I ran the script locally after fixing it,
the script added label in #3835

```
rakshith:ceph-csi$ export REPOSITORY_URL=https://github.com/ceph/ceph-csi
rakshith:ceph-csi$ export MERGE_QUEUE_PR_URL="https://github.com/ceph/ceph-
csi/pull/3835"
rakshith:ceph-csi$ gh pr view --json body -q ".body" $MERGE_QUEUE_PR_URL | sed -n -e '/```yaml/,/```/p' | sed -e '1d;$d' | yq '.pull_requests[]|.number' | while read pr_number ; do     gh pr view --json labels -q '.labels[]|.name' ${REPOSITORY_URL}/pull/$pr_number | while read label ; do       if [[ -z "$labels" ]] || [[ ",$labels," =~ ",$label," ]]; then         gh pr edit --add-label "$label" $MERGE_QUEUE_PR_URL;       fi;     done;   done
https://github.com/ceph/ceph-csi/pull/3835
https://github.com/ceph/ceph-csi/pull/3835
https://github.com/ceph/ceph-csi/pull/3835
```

2023-05-16 05:44 UTC, Rakshith-R commented
https://github.com/ceph/ceph-csi/pull/3835#issuecomment-1549020177

The second commit was also verified from my local ci.
```
rakshith:ceph-csi$         gh pr view --json body -q ".body" $MERGE_QUEUE_PR_URL | sed -n -e '/```yaml/,/```/p' | sed -e '1d;$d' | yq '.pull_requests[]|.number' | while read pr_number ; do
          gh pr view --json labels -q '.labels[]|.name' ${REPOSITORY_URL}/pull/$pr_number | while read label ; do
            if [[ -z "$labels" ]] || [[ ",$labels," =~ ",$label," ]]; then
              gh pr edit --add-label "$label" $MERGE_QUEUE_PR_URL
            fi
          done
          gh pr edit --add-label "ok-to-test" $MERGE_QUEUE_PR_URL  
        done
https://github.com/ceph/ceph-csi/pull/3835
https://github.com/ceph/ceph-csi/pull/3835
https://github.com/ceph/ceph-csi/pull/3835
https://github.com/ceph/ceph-csi/pull/3835
```

2023-05-16 06:39 UTC, Madhu-1 approved these changes, later dismissed

2023-05-16 08:16 UTC, nixpanic requested changes
The `ok-to-test` label should get added by a rule in the Mergify configuration, not hardcoded in an action.

2023-05-16 08:16 UTC, nixpanic commented on actions/gha-mergify-merge-queue-labels-copier/action.yaml
> +          gh pr edit --add-label "ok-to-test" $MERGE_QUEUE_PR_URL
This should not be needed. Ideally we fix the upstream Mergify action and this can not be included there.

2023-05-16 09:58 UTC, Rakshith-R commented
> The `ok-to-test` label should get added by a rule in the Mergify configuration, not hardcoded in an action.

The full set of configuration does not run on draft merge queue pr for it to add `ok-to-test`

and the label copier may miss the `ok-to-test` label since we have an action that removes it after commenting.

@nixpanic , Let's get this in now and later replace it with the original action when it is functioning as expected ?

2023-05-16 10:34 UTC, nixpanic commented
> and the label copier may miss the `ok-to-test` label since we have an action that removes it after commenting.

The label copier is not expected to add `ok-to-test`, as it will not be set (anymore) on the original PR.

This Mergify rule is expected to add the `ok-to-test` label (but it is not working?):

https://github.com/ceph/ceph-csi/blob/c67517109809e549265b24c9c57c4bbb312cd424/.mergify.yml#L52-L65

2023-05-16 10:44 UTC, Rakshith-R commented
> > and the label copier may miss the `ok-to-test` label since we have an action that removes it after commenting.
> 
> The label copier is not expected to add `ok-to-test`, as it will not be set (anymore) on the original PR.
> 
> This Mergify rule is expected to add the `ok-to-test` label (but it is not working?):
> 
> https://github.com/ceph/ceph-csi/blob/c67517109809e549265b24c9c57c4bbb312cd424/.mergify.yml#L52-L65

Yup, only the subset in the pr description is run.
https://github.com/ceph/ceph-csi/pull/3835#issuecomment-1549020177

2023-05-17 07:19 UTC, nixpanic commented
Shall we drop `"check-pending=Queue: Embarked in merge train"` from the Mergify rule, so that any PR created by Mergify gets the `ok-to-test` label automatically?

If you do this in this PR, you can drop it from the `action.yaml` and things will be cleaner.

2023-05-17 08:45 UTC, Rakshith-R commented
Made some changes to the action instead of hard coding required labels. 

Sent a patch pr to the upstream action repo too https://github.com/Mergifyio/gha-mergify-merge-queue-labels-copier/pull/2/files

cc @nixpanic

2023-05-17 10:12 UTC, Rakshith-R commented
The official action now has all the fixes and new feature, we can use that now.

https://github.com/Mergifyio/gha-mergify-merge-queue-labels-copier/pulls?q=is%3Apr+is%3Aclosed

2023-05-17 10:30 UTC, Madhu-1 submitted a review, later dismissed

2023-05-17 13:51 UTC, nixpanic requested changes
a little more cleanup is needed. thanks for upstreaming the changes!

2023-05-17 13:51 UTC, nixpanic commented on .github/workflows/mergify-copy-labels.yaml
>          uses: actions/checkout@v3
this checkout is not needed anymore now

2023-05-17 13:56 UTC, Madhu-1 approved these changes

2023-05-19 07:38 UTC, nixpanic approved these changes

2023-05-19 07:40 UTC, merged