ci: remove k8s 1.24 support
ceph/ceph-csi pull request #3909
Opened 2023-06-15 12:09 UTC by Rakshith-R

K8s 1.24 will be End of Life on 2023-07-28.
Therefore, this commit removes support
for k8s 1.24.

refer:
https://kubernetes.io/releases/#release-v1-24

2023-06-16 06:39 UTC, Rakshith-R commented
https://jenkins-ceph-csi.apps.ocp.cloud.ci.centos.org/blue/organizations/jenkins/jjb-validate/detail/jjb-validate/264/pipeline/

The new jenkins-jobs python package needs dataclasses but dataclasses are present by default only in python 3.7.

https://forums.fast.ai/t/modulenotfounderror-no-module-named-dataclasses/24499/5

I've edited the dockerfile to install it but don't know how to trigger new build of image

@nixpanic Can you please take a look?
```
HEAD is now at 15d6d90 Merge 0b2cf3ffc0cfc322bf069c42c3ca315def1bff5b into f7942edc6ceb4d2e013ceb5c138be2740574f5ab

make: Entering directory '/opt/build/deploy'

cd /opt/build/deploy/../ && jenkins-jobs test -o /opt/build/deploy/..//_output/ jobs

Traceback (most recent call last):

  File "/usr/local/bin/jenkins-jobs", line 7, in <module>

    from jenkins_jobs.cli.entry import main

  File "/usr/local/lib/python3.6/site-packages/jenkins_jobs/cli/entry.py", line 25, in <module>

    from jenkins_jobs.errors import JenkinsJobsException

  File "/usr/local/lib/python3.6/site-packages/jenkins_jobs/errors.py", line 4, in <module>

    from dataclasses import dataclass

ModuleNotFoundError: No module named 'dataclasses'

make: *** [Makefile:5: test] Error 1
```

2023-06-21 08:04 UTC, nixpanic commented
/retest ci/centos/jjb-validate

2023-06-21 08:06 UTC, nixpanic requested changes

2023-06-21 08:06 UTC, nixpanic commented on deploy/Dockerfile
> + && pip3 install dataclasses \
this is not needed, see #3926 for a cleaner solution.

2023-06-21 08:54 UTC, Madhu-1 approved these changes

2023-06-21 08:56 UTC, riya-singhal31 approved these changes

2023-06-21 10:53 UTC, nixpanic approved these changes

2023-06-21 10:53 UTC, merged