cephfs: add CSI-Addons support to the cephfs
ceph/ceph-csi pull request #3991
Opened 2023-07-11 15:23 UTC by riya-singhal31

this commit adds CSI-Addons support to the
cephfs provisioner

Updates: #3969

2023-07-12 06:53 UTC, Madhu-1 requested changes
This doesn't look complete, please make sure you also implement the services for completeness.

2023-07-12 06:53 UTC, Madhu-1 commented on internal/csi-addons/cephfs/identity.go
> +					},
Do we support this for cephfs csi driver?

2023-07-12 06:53 UTC, Madhu-1 commented on internal/csi-addons/cephfs/identity.go
> +				},
do we support reclaimspace for cephfs?

2023-07-12 08:32 UTC, riya-singhal31 commented
Thanks for the review Madhu, updated the capabilities supported by cephfs. 
PTAL.

2023-07-12 09:16 UTC, nixpanic commented on internal/cephfs/driver.go
> +func (fs *Driver) setupCSIAddonsServer(conf *util.Config) error {
Looks quite complete to me, but you still need to call this function from the main `Run()` one somewhere.

2023-07-12 09:35 UTC, riya-singhal31 commented on internal/cephfs/driver.go
> +func (fs *Driver) setupCSIAddonsServer(conf *util.Config) error {
Thanks for the review Niels, just missed it. Updated. PTAL.

2023-07-13 08:27 UTC, nixpanic approved these changes

2023-07-14 11:33 UTC, riya-singhal31 commented
The below shows that the csi-addons command is running in the csi-addons-sidecar container of a cephfs provisioner pod.

[ndevos@ibm.com ~]$ oc -n openshift-storage rsh -c csi-addons csi-cephfsplugin-jwtfd
sh-5.1# csi-addons -h
  -drivername string
        name of the CSI driver
  -endpoint string
        CSI-Addons endpoint (default "unix:///tmp/csi-addons.sock")
  -legacy
        use legacy format for old Kubernetes versions
  -operation string
        csi-addons operation
  -persistentvolume string
        name of the PersistentVolume
  -stagingpath string
        staging path (default "/var/lib/kubelet/plugins/kubernetes.io/csi/")

The following operations are supported:
 - GetIdentity
 - GetCapabilities
 - Probe
 - ControllerReclaimSpace
 - NodeReclaimSpace
sh-5.1# csi-addons -endpoint unix:///csi/csi-addons.sock -operation GetIdentity
identity: name:"openshift-storage.cephfs.csi.ceph.com"  vendor_version:"canary"
sh-5.1# csi-addons -endpoint unix:///csi/csi-addons.sock -operation GetCapabilities
capabilities: 

Thank you @nixpanic for helping out. 
cc: @Madhu-1

2023-07-14 11:35 UTC, Madhu-1 approved these changes

2023-07-14 11:39 UTC, riya-singhal31 commented
@mergifyio queue

2023-07-14 13:24 UTC, merged