doc:add reference to CSI snapshot deployment guide
ceph/ceph-csi pull request #4119
Opened 2023-09-12 05:39 UTC by iPraveenParihar

- doc: Update README.md and fix typo
- rebase: Bump the k8s-dependencies group with 1 update
- rebase: Bump actions/checkout from 3 to 4
- rbd: fixed csi-rbdplugin crashes when decoding volume ID failed
- rebase: Bump the github-dependencies group with 1 update
- rebase: Bump golang.org/x/sys from 0.11.0 to 0.12.0
- rbd: fixed all potential crashing when decoding volume ID failed
- doc: add info about csi snapshot deployment

# Describe what this PR does #

Provide some context for the reviewer

## Is there anything that requires special attention ##

Do you have any questions?

Is the change backward compatible?

Are there concerns around backward compatibility?

Provide any external context for the change, if any.

For example:

* Kubernetes links that explain why the change is required
* CSI spec related changes/catch-up that necessitates this patch
* golang related practices that necessitates this change

## Related issues ##

Mention any github issues relevant to this PR. Adding below line
will help to auto close the issue once the PR is merged.

Fixes: #issue_number

## Future concerns ##

List items that are not part of the PR and do not impact it's
functionality, but are work items that can be taken up subsequently.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)

</details>

2023-09-12 06:01 UTC, Rakshith-R requested changes

2023-09-12 06:01 UTC, Rakshith-R commented on docs/deploy-cephfs.md
> +If you intend to use the snapshot functionality in your Kuberenetes cluster, please refer [deployment guide](./snap-clone.md#prerequisite)
```suggestion
**Deploy prerequisites for CSI Snapshot:**

If you intend to use the snapshot functionality in your Kuberenetes cluster, please refer to [snap-clone.md](./snap-clone.md#prerequisite) 
```

2023-09-12 06:48 UTC, Madhu-1 requested changes

2023-09-12 06:48 UTC, Madhu-1 commented on docs/deploy-cephfs.md
> +**Deploy prerequisites for  CSI Snapshot:**
```suggestion
**Deploy prerequisites for CSI Snapshot:**
```

2023-09-12 06:48 UTC, Madhu-1 commented on docs/deploy-cephfs.md
> +If you intend to use the snapshot functionality in your Kuberenetes cluster,
```suggestion
If you intend to use the snapshot functionality in  Kubernetes cluster,
```

2023-09-12 07:03 UTC, Madhu-1 approved these changes, later dismissed

2023-09-12 07:04 UTC, Madhu-1 commented on docs/deploy-cephfs.md
> +If you intend to use the snapshot functionality in Kuberenetes cluster,
still you have typo in Kubernetes

2023-09-12 07:18 UTC, iPraveenParihar commented on docs/deploy-cephfs.md
> +If you intend to use the snapshot functionality in Kuberenetes cluster,
Ahh, missed it!

2023-09-12 08:31 UTC, Rakshith-R submitted a review, later dismissed

2023-09-12 08:32 UTC, riya-singhal31 approved these changes, later dismissed

2023-09-12 09:19 UTC, Madhu-1 approved these changes, later dismissed

2023-09-12 09:57 UTC, Rakshith-R commented
@mergifyio queue

2023-09-14 05:14 UTC, Rakshith-R commented
@mergifyio refresh

2023-09-14 05:26 UTC, Rakshith-R commented
@mergifyio rebase

2023-09-14 06:44 UTC, Madhu-1 commented
@Mergifyio requeue default

2023-09-14 06:45 UTC, Madhu-1 commented
@Mergifyio refresh

2023-09-14 06:54 UTC, Madhu-1 approved these changes, later dismissed

2023-09-14 06:55 UTC, Rakshith-R submitted a review, later dismissed

2023-09-14 06:56 UTC, Madhu-1 commented
@mergifyio queue

2023-09-14 10:14 UTC, Madhu-1 commented
@mergifyio refresh

2023-09-14 11:00 UTC, Madhu-1 commented
@mergifyio rebase

2023-09-14 11:23 UTC, Madhu-1 commented
@Mergifyio rebase

2023-09-14 12:31 UTC, Madhu-1 commented
@Mergifyio dequeue

2023-09-14 13:42 UTC, Rakshith-R commented
@Mergifyio unqueue

2023-09-14 13:44 UTC, Rakshith-R commented
@mergifyio unqueue

2023-09-14 13:46 UTC, Rakshith-R commented
@iPraveenParihar please rebase this pr manually after this pr https://github.com/ceph/ceph-csi/pull/4124 merges.

2023-09-14 14:34 UTC, Rakshith-R approved these changes

2023-09-14 14:47 UTC, Rakshith-R commented
@Mergifyio requeue

2023-09-14 14:48 UTC, Rakshith-R commented
@Mergifyio queue

2023-09-14 14:53 UTC, Madhu-1 approved these changes

2023-09-14 14:53 UTC, Madhu-1 commented
@Mergifyio queue

2023-09-14 14:53 UTC, merged