deploy: update CSI sidecars to latest versions available
ceph/ceph-csi pull request #4132
Opened 2023-09-14 12:18 UTC by iPraveenParihar

# Describe what this PR does #

Below sidecars are updated with latest available versions

csi-node-driver-registrar: v2.9.0
csi-resizer: v1.9.0
csi-provisioner: v3.6.0

Closes: #4128 
CC @Madhu-1 

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)

</details>

2023-09-14 12:57 UTC, iPraveenParihar commented
There is no release from `csi-attacher` and `csi-snapshotter`

2023-09-15 05:06 UTC, Rakshith-R submitted a review, later dismissed

2023-09-15 05:32 UTC, Madhu-1 commented
@iPraveenParihar also update the  snapshotter and attacher as there is a new version of both of them.

2023-09-19 07:15 UTC, Madhu-1 requested changes

2023-09-19 07:15 UTC, Madhu-1 commented on deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
> +          image: gcr.io/k8s-staging-sig-storage/csi-resizer:v1.9.0
provisioner update is missing

2023-09-19 11:17 UTC, iPraveenParihar commented on deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
> +          image: gcr.io/k8s-staging-sig-storage/csi-resizer:v1.9.0
Updated!

2023-09-19 11:19 UTC, Madhu-1 approved these changes

2023-09-20 05:03 UTC, Rakshith-R approved these changes

2023-09-20 05:19 UTC, Rakshith-R commented
@mergifyio queue

2023-09-20 06:12 UTC, Rakshith-R commented
@mergifyio rebase

2023-09-20 06:20 UTC, Rakshith-R commented
@mergifyio queue

2023-09-20 08:20 UTC, merged