doc: add/mark the in-tree migration path to deprecation
ceph/ceph-csi pull request #4221
Opened 2023-10-31 13:22 UTC by humblec

The in-tree migration path in Kubernetes has been deprecated in v1.28 and this has to be marked in ceph csi docs too.

The alternative mechanism to use here is the persistent-volume-migrator

# Describe what this PR does #

Provide some context for the reviewer

## Is there anything that requires special attention ##

Do you have any questions?

Is the change backward compatible?

Are there concerns around backward compatibility?

Provide any external context for the change, if any.

For example:

* Kubernetes links that explain why the change is required
* CSI spec related changes/catch-up that necessitates this patch
* golang related practices that necessitates this change

## Related issues ##

Mention any github issues relevant to this PR. Adding below line
will help to auto close the issue once the PR is merged.

Fixes: #issue_number

## Future concerns ##

List items that are not part of the PR and do not impact it's
functionality, but are work items that can be taken up subsequently.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)

</details>

2023-11-01 08:29 UTC, nixpanic commented on docs/intree-migrate.md
> +
please remove the initial empty line

2023-11-01 08:29 UTC, nixpanic commented on docs/intree-migrate.md
> +likely been developed to facilitate the migration process and ensure a smoother
_likely_? Please clear your doubts about that, and of anyone reading this warning.

2023-11-01 08:29 UTC, nixpanic commented on docs/intree-migrate.md
> +the previous/below mentioned method.**
maybe replace: _previous/below mentioned method_ -> the method described in this document

2023-11-01 11:20 UTC, humblec commented on docs/intree-migrate.md
> +
Done

2023-11-01 11:20 UTC, humblec commented on docs/intree-migrate.md
> +likely been developed to facilitate the migration process and ensure a smoother
rephrased

2023-11-01 11:20 UTC, humblec commented on docs/intree-migrate.md
> +the previous/below mentioned method.**
done

2023-11-01 12:22 UTC, nixpanic approved these changes

2023-11-01 12:27 UTC, Madhu-1 commented on docs/intree-migrate.md
> +[this](https://github.com/ceph/persistent-volume-migrator). This utility has
The migration tool talks abouts migrating from flex to csi (more specifically Rook and CSI) it doesn't mention about in-tree in the Readme doc

2023-11-02 12:17 UTC, Madhu-1 requested changes
I looked at the code of volume-migrator, it doesn't work with standalone cephcsi

2023-12-16 21:01 UTC, closed without merging