revert: revert to 3.11-canary
ceph/ceph-csi pull request #4536
Opened 2024-04-02 15:11 UTC by Rakshith-R

# Describe what this PR does #

This commit makes template changes for
3.11 release branch to use 3.11-canary tag.

**Checklist:**

* [ ] **Commit Message Formatting**: Commit titles and messages follow
  guidelines in the [developer
  guide](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#commit-messages).
* [ ] Reviewed the developer guide on [Submitting a Pull
  Request](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#development-workflow)
* [ ] [Pending release
  notes](https://github.com/ceph/ceph-csi/blob/devel/PendingReleaseNotes.md)
  updated with breaking and/or notable changes for the next major release.
* [ ] Documentation has been updated, if necessary.
* [ ] Unit tests have been added, if necessary.
* [ ] Integration tests have been added, if necessary.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

* `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)

</details>

2024-04-02 15:17 UTC, nixpanic approved these changes, later dismissed

2024-04-03 03:31 UTC, iPraveenParihar approved these changes, later dismissed

2024-04-03 05:30 UTC, Rakshith-R commented
@mergifyio queue

2024-04-03 06:23 UTC, Madhu-1 requested changes

2024-04-03 06:23 UTC, Madhu-1 commented on deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
> +          image: quay.io/cephcsi/cephcsi:v3.11-canary
same change is required in value.yaml for both helm charts can you please check?

2024-04-03 06:24 UTC, Madhu-1 commented on deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
> +          image: quay.io/cephcsi/cephcsi:v3.11-canary
what about nfs plugin ds yaml?

2024-04-03 08:11 UTC, Rakshith-R commented
corrected, sorry for missing it.

2024-04-03 08:23 UTC, Madhu-1 approved these changes

2024-04-03 08:35 UTC, nixpanic approved these changes

2024-04-03 08:36 UTC, nixpanic commented
@mergifyio queue

2024-04-04 06:08 UTC, Madhu-1 commented
/retest ci/centos/mini-e2e/k8s-1.29

2024-04-04 06:09 UTC, Madhu-1 commented
@mergifyio queue

2024-04-04 07:51 UTC, merged