util: add support to configure mirror daemon count
ceph/ceph-csi pull request #4566
Opened 2024-04-18 12:08 UTC by Madhu-1

# Describe what this PR does #

Currently, we are assuming that only one rbd mirror daemon running on the ceph cluster but that is not true for many cases and it can be more than one, this PR makes this a configurable parameter.

## Is there anything that requires special attention ##

Do you have any questions?

Is the change backward compatible?

yes 

Are there concerns around backward compatibility?

No

Fixes: #4312

2024-04-18 15:17 UTC, nixpanic requested changes

2024-04-18 15:17 UTC, nixpanic commented on internal/util/csiconfig.go
> +		"mirrorDaemonCount": "1"
Great test case, but unfortunately missing in the unit tests.

Please add a test-case that expects an error when the argument is a number as `"string"` (maybe convert it?) or even an invalid number.

2024-04-19 07:28 UTC, nixpanic approved these changes

2024-04-22 07:35 UTC, Rakshith-R approved these changes

2024-04-22 07:35 UTC, Rakshith-R commented
@megifyio rebase
@mergifyio queue

2024-04-22 07:52 UTC, Madhu-1 commented
@mergifyio rebase

2024-04-22 07:52 UTC, Madhu-1 commented
@Mergifyio queue

2024-04-22 09:49 UTC, merged