ci: Use temporary directory for unit tests
ceph/ceph-csi pull request #4626
Opened 2024-05-18 04:17 UTC by mayankpall

ci: Use temporary directory for unit tests

This commit implements the use of a temporary directory for unit tests in order to ensure a clean and isolated environment for testing purposes.

Signed-off-by: Mayank <mayankpal9654@gmail.com>

2024-05-18 04:29 UTC, mayankpall commented
@iPraveenParihar  Hopefully now it meets the requirement

2024-05-19 09:23 UTC, iPraveenParihar commented
> @iPraveenParihar Hopefully now it meets the requirement

@mayankpall, please look at the following error and update the commit body.

✖   body's lines must not be longer than 80 characters [body-max-line-length]

2024-05-19 11:18 UTC, mayankpall commented
<img width="536" alt="Screenshot 2024-05-19 at 4 45 26 PM" src="https://github.com/ceph/ceph-csi/assets/91751515/8311d7c0-3f1a-4fa2-9571-9dd7d919f093">

edited it to shortest as possible.

2024-05-19 15:00 UTC, mayankpall commented
@iPraveenParihar all checks have passed

2024-05-21 05:33 UTC, iPraveenParihar submitted a review, later dismissed

2024-05-21 06:11 UTC, Madhu-1 requested changes

2024-05-21 06:11 UTC, Madhu-1 commented on internal/rbd/nodeserver_test.go
>  	err = os.Mkdir("/etc/ceph-csi-config", 0o600)
`err = os.Mkdir("/etc/ceph-csi-config", 0o600)` remove this one as its not required any more

2024-05-21 10:18 UTC, mayankpall commented
@Madhu-1  removed err = os.Mkdir("/etc/ceph-csi-config", 0o600)

2024-05-21 10:25 UTC, Madhu-1 requested changes
Please squash all the commits into a single commit.

2024-05-21 10:25 UTC, Madhu-1 commented on internal/rbd/nodeserver_test.go
>  	}
Please remove this check as its not required

2024-05-21 10:50 UTC, mayankpall commented
@Madhu-1  removed and squashed all the commits

2024-05-21 10:59 UTC, Madhu-1 approved these changes

2024-05-21 11:06 UTC, iPraveenParihar approved these changes

2024-05-21 11:30 UTC, iPraveenParihar commented
@Madhu-1, can we skip e2e tests for this PR? Since changes are in unit tests?

2024-05-21 11:38 UTC, Madhu-1 commented
> @Madhu-1, can we skip e2e tests for this PR? Since changes are in unit tests?

yes that make sense, we can skip multi-arch buil and E2E for this kind of PR's

2024-05-22 04:17 UTC, iPraveenParihar commented
@Mergifyio queue

2024-05-22 06:07 UTC, iPraveenParihar commented
@mergifyio rebase

2024-05-22 06:26 UTC, iPraveenParihar commented
@Mergifyio queue

2024-05-22 06:27 UTC, iPraveenParihar commented
@Mergifyio refresh

2024-05-22 06:28 UTC, iPraveenParihar commented
@Mergifyio queue default

2024-05-22 06:35 UTC, iPraveenParihar commented
@Rakshith-R, can you take look at this?

Mergifyio can't queue due to
```
The merge queue pull request can't be updated
Details:

Unable to update: user mayankpall is unknown.
```

2024-05-27 05:51 UTC, Rakshith-R commented
@mergifyio rebase

2024-05-27 05:52 UTC, Rakshith-R commented
@mergifyio queue

2024-05-27 05:57 UTC, merged