cephfs: add examples for volumegroupsnapshot
ceph/ceph-csi pull request #4814
Opened 2024-08-29 10:58 UTC by yati1998

this commit add yaml exampl files for creation of
volumegroupsnapshotclass and volumegroupsnapshot for cephfs driver

2024-08-29 11:13 UTC, Madhu-1 requested changes

2024-08-29 11:13 UTC, Madhu-1 commented on examples/cephfs/groupsnapshotclass.yaml
> +driver: rook-ceph.cephfs.csi.ceph.com # csi-provisioner-name
use the cephcsi driver name (not specific to Rook)

2024-08-29 11:13 UTC, Madhu-1 commented on examples/cephfs/groupsnapshotclass.yaml
> +  # for example "rook-ceph".
Please remove this one  or update as per cephcsi doc clusterID

2024-08-29 11:13 UTC, Madhu-1 commented on examples/cephfs/groupsnapshotclass.yaml
> +  csi.storage.k8s.io/group-snapshotter-secret-namespace: rook-ceph # namespace:cluster
remove rook from the secret and remove comments related to Rook

2024-08-29 12:30 UTC, nixpanic commented
Looks good to me. Just make sure to address the YAML linter issue too

https://github.com/ceph/ceph-csi/actions/runs/10614805727/job/29421527358?pr=4814#step:3:1138

2024-08-29 13:22 UTC, nixpanic approved these changes

2024-09-02 06:36 UTC, yati1998 commented
@Madhu-1 @Rakshith-R can you please review the PR

2024-09-02 08:42 UTC, Madhu-1 approved these changes

2024-09-02 08:42 UTC, Madhu-1 commented
@mergifyio queue

2024-09-02 08:47 UTC, merged