doc: update doc for disaster recovery
ceph/ceph-csi pull request #4905
Opened 2024-10-14 03:24 UTC by yati1998

Volume Replication has been added to csi-addons
as a feature in it sometime back. But the doc still uses the volume replication operator to enable
mirroring and create related resources for
disaster recovery.
this commit updates the document to use csi-addons instead of creating volumereplication sidecar.

2024-10-14 10:37 UTC, Madhu-1 requested changes

2024-10-14 10:37 UTC, Madhu-1 commented on docs/disaster-recovery.md
> + kubectl edit cm rook-ceph-operator-config -nrook-ceph
cephcsi doesnt should not use Rook

2024-10-14 10:37 UTC, Madhu-1 commented on docs/disaster-recovery.md
> +kubectl create -f https://raw.githubusercontent.com/csi-addons/kubernetes-csi-addons/main/deploy/controller/setup-controller.yaml
use release version instead of main

2024-10-14 10:37 UTC, Madhu-1 commented on docs/disaster-recovery.md
> -              mountPath: /csi
Need to remove line 90 and 91 which is pointing to volume-replication-operator.

2024-10-14 10:37 UTC, Madhu-1 commented on docs/disaster-recovery.md
>  >:bulb: For more information, please refer to the
point to the csi-addons operator replication doc

2024-10-15 13:15 UTC, yati1998 commented on docs/disaster-recovery.md
>  >:bulb: For more information, please refer to the
do you mean this: https://github.com/csi-addons/kubernetes-csi-addons/blob/main/docs/volumereplication.md

2024-10-17 08:13 UTC, nixpanic commented on docs/disaster-recovery.md
> +## Enable CSI-ADDONS Sidecar
The name of the project is **CSI-Addons**, please use the correct capitalization.

2024-10-17 08:13 UTC, nixpanic commented on docs/disaster-recovery.md
> +> See [releases](https://github.com/csi-addons/kubernetes-csi-addons/branches)
maybe point to the releases instead of branches?

https://github.com/csi-addons/kubernetes-csi-addons/releases

2024-11-04 07:39 UTC, Madhu-1 commented on docs/csi-addons/disaster-recovery.md
>  > [volume-replication-operator](https://github.com/csi-addons/volume-replication-operator).
This is still pointing to the volume-replication-operator which is replaced by csi-addons, can you please change this to point to replication doc in kubernetes-csi-addons

2024-11-04 11:13 UTC, yati1998 commented on docs/csi-addons/disaster-recovery.md
>  > [volume-replication-operator](https://github.com/csi-addons/volume-replication-operator).
there is no proper documentation which covers the volume replication functionality, it is just the doc that has yaml structure. We will first need to update that.

2024-11-04 11:51 UTC, Madhu-1 commented on docs/csi-addons/disaster-recovery.md
>  > [volume-replication-operator](https://github.com/csi-addons/volume-replication-operator).
Lets update the required documentation in kuberenetes-csi-addons(copy/paste) and remove the reference from here?

2024-11-04 11:56 UTC, yati1998 commented on docs/csi-addons/disaster-recovery.md
>  > [volume-replication-operator](https://github.com/csi-addons/volume-replication-operator).
works, will update

2025-01-02 07:24 UTC, Madhu-1 approved these changes

2025-01-21 08:42 UTC, nixpanic approved these changes

2025-01-21 08:43 UTC, nixpanic commented
@mergifyio queue

2025-01-21 10:31 UTC, merged